databrickslabs/ucx

src/databricks/labs/ucx/framework/crawlers.py, src/databricks/labs/ucx/framework/tasks.py, src/databricks/labs/ucx/hive_metastore/grants.py, src/databricks/labs/ucx/hive_metastore/tables.py, src/databricks/labs/ucx/runtime.py, src/databricks/labs/ucx/workspace_access/manager.py, tests/unit/framework/mocks.py, tests/unit/framework/test_crawlers.py, tests/unit/workspace_access/test_manager.py
=> Simplify `SqlBackend` and table creation logic

src/databricks/labs/ucx/hive_metastore/tables.scala, src/databricks/labs/ucx/install.py, tests/integration/test_installation.py
=> Fix configuration path in job task install code

CONTRIBUTING.md, README.md, src/databricks/labs/ucx/install.py, src/databricks/labs/ucx/runtime.py
Tune up the documentation #199
=> Improve user-facing documentation

src/databricks/labs/ucx/install.py
In the previous setup, the jobs of the app were overridden by other users
=> Allow installing UCX by multiple different users

src/databricks/labs/ucx/hive_metastore/grants.py, tests/unit/hive_metastore/test_grants.py
Adding a safe return for grants to handle corner cases
=> Adding safe return on grants

src/databricks/labs/ucx/hive_metastore/data_objects.py, tests/integration/assessment/test_external_locations.py, tests/integration/hive_metastore/test_external_locations.py
Created unit testing
Still seeing weird behavior of the Row class.
Possibly related to Python version.
Fix #256
=> Fixed `guess_external_locations` failure with `AttributeError: as_dict` and added an integration test

src/databricks/labs/ucx/runtime.py
=> documentation Format issue corrected

README.md
=> Add tutorial links to the landing page of documentation

src/databricks/labs/ucx/assessment/queries/count_table_failures.sql, src/databricks/labs/ucx/hive_metastore/tables.scala
=> Record errors from `crawl_tables` step in `$inventory.table_failures` table and display counter on the dashboard

docs/table_persistence.md
Generated the table persistence document in docs
=> Ported internal document about UCX persistence schema

src/databricks/labs/ucx/framework/parallel.py, tests/unit/framework/test_parallel.py
=> Added logging of errors during threadpool operations.

src/databricks/labs/ucx/install.py
Fixes: #382 
```
Select PRO or SERVERLESS SQL warehouse to run assessment dashboards on
[0] Shared Endpoint (475b...cd5211, Serverless, RUNNING)
[1] [Create new PRO SQL warehouse]
...
Enter a number between 0 and 7: 
```
=> Show difference between serverless and PRO warehouses during installation

src/databricks/labs/ucx/framework/crawlers.py, tests/integration/hive_metastore/test_external_locations.py
Fixed the external location test. Modified crawler to reference dataclass instead of type.
=> Fixed integration tests for crawlers

tests/integration/test_installation.py
Added asserts to e2e tests to verify that the backup groups get deleted
=> Added integration test to check backup groups get deleted

src/databricks/labs/ucx/install.py, tests/integration/conftest.py, tests/integration/test_installation.py
=> Run integration tests on shared clusters for a faster devloop

src/databricks/labs/ucx/assessment/queries/all_tables.sql, src/databricks/labs/ucx/assessment/queries/database_summary.sql
=> Improved dashboard queries to show unsupported storage types.

README.md
simple inclusion of hyperlink to releases.
=> Added hyperlink to UCX releases in the main readme

src/databricks/labs/ucx/assessment/crawlers.py, tests/integration/assessment/test_assessment.py, tests/unit/assessment/test_assessment.py
=> Add exception handling for secret scope not found.

src/databricks/labs/ucx/install.py
=> Replace plus char with minus in version tag for GCP dev installation of UCX

src/databricks/labs/ucx/assessment/crawlers.py, tests/unit/assessment/test_assessment.py
=> Added checking for index out of range.

src/databricks/labs/ucx/config.py, src/databricks/labs/ucx/framework/tasks.py, src/databricks/labs/ucx/install.py, src/databricks/labs/ucx/runtime.py, tests/unit/assessment/test_dashboard.py, tests/unit/test_install.py
=> Improve README.py and logging messages

src/databricks/labs/ucx/framework/parallel.py, src/databricks/labs/ucx/framework/tasks.py, src/databricks/labs/ucx/hive_metastore/grants.py, src/databricks/labs/ucx/mixins/fixtures.py, src/databricks/labs/ucx/runtime.py, src/databricks/labs/ucx/workspace_access/generic.py, src/databricks/labs/ucx/workspace_access/groups.py, src/databricks/labs/ucx/workspace_access/migration.py, tests/integration/test_installation.py, tests/integration/workspace_access/test_groups.py, tests/integration/workspace_access/test_workspace_access.py, tests/unit/framework/test_logger.py, tests/unit/framework/test_parallel.py, tests/unit/workspace_access/conftest.py, tests/unit/workspace_access/test_base.py, tests/unit/workspace_access/test_groups.py, tests/unit/workspace_access/test_listing.py, tests/unit/workspace_access/test_tacl.py
=> Removed thread pool for any IAM Group removals and additions

tests/unit/workspace_access/test_generic.py
Added unit tests for load_as_dict func.
=> Added unit tests for generic permissions

README.md
Added pre-req to README to match go/uc/upgrade and added links to our public documentation
=> Added pre-req section to README

src/databricks/labs/ucx/assessment/queries/all_tables.sql, src/databricks/labs/ucx/assessment/queries/database_summary.sql
=> Fix casing in `all_tables.sql` query.

src/databricks/labs/ucx/hive_metastore/grants.py, tests/integration/hive_metastore/test_grants.py, tests/unit/hive_metastore/test_grants.py
=> Fixed missed scans for empty databases and views in `crawl_grants`

src/databricks/labs/ucx/framework/logger.py
=> Improve logging colors for dark terminal backgrounds

src/databricks/labs/ucx/install.py
=> Fix spelling issue in install.py

src/databricks/labs/ucx/framework/dashboards.py
=> Fixed handling of keys with and without values.

src/databricks/labs/ucx/workspace_access/generic.py, src/databricks/labs/ucx/workspace_access/redash.py, src/databricks/labs/ucx/workspace_access/scim.py, tests/unit/workspace_access/test_generic.py, tests/unit/workspace_access/test_redash.py, tests/unit/workspace_access/test_scim.py
Duplicated from: https://github.com/databrickslabs/ucx/pull/507
=> Retry set/update permissions when possible and assess the changes in the workspace

src/databricks/labs/ucx/workspace_access/generic.py, tests/unit/workspace_access/test_generic.py
=> Introduced Safer access to workspace objects' properties.

tests/integration/workspace_access/test_groups.py
=> Fixed integration test failures related to concurrent group delete

src/databricks/labs/ucx/install.py, tests/integration/test_installation.py
=> Added failure injection for job failure message propagation 

.github/workflows/acceptance.yml, .github/workflows/push.yml, CONTRIBUTING.md, Makefile, pyproject.toml, src/databricks/labs/ucx/assessment/crawlers.py, src/databricks/labs/ucx/framework/crawlers.py, src/databricks/labs/ucx/framework/dashboards.py, src/databricks/labs/ucx/framework/install_state.py, src/databricks/labs/ucx/hive_metastore/grants.py, src/databricks/labs/ucx/install.py, src/databricks/labs/ucx/mixins/sql.py, src/databricks/labs/ucx/workspace_access/groups.py, src/databricks/labs/ucx/workspace_access/listing.py, src/databricks/labs/ucx/workspace_access/migration.py, tests/integration/assessment/test_assessment.py, tests/integration/conftest.py, tests/integration/hive_metastore/test_grants.py, tests/integration/hive_metastore/test_tables.py, tests/integration/test_installation.py, tests/integration/workspace_access/test_groups.py, tests/integration/workspace_access/test_tacl.py, tests/integration/workspace_access/test_workspace_access.py, tests/unit/assessment/test_assessment.py, tests/unit/framework/test_crawlers.py, tests/unit/test_install.py, ucx.iml
This PR fixes the bugs in the code that prevented a successful integration testing pass
=> Improve integration test stability

src/databricks/labs/ucx/hive_metastore/tables.py, src/databricks/labs/ucx/mixins/fixtures.py, tests/integration/conftest.py, tests/integration/hive_metastore/test_migrate.py
This PR adds integration tests for EXTERNAL and MANAGED table migrations on Azure
=> Enable integration tests for `EXTERNAL` table migrations

README.md
Add details on what's required for your desktop computer to run the UCX installer and what's required in the Databricks workspace.
=> Add detailed UCX pre-requisite information to README.md

src/databricks/labs/ucx/framework/tasks.py, src/databricks/labs/ucx/install.py, src/databricks/labs/ucx/runtime.py, tests/unit/assessment/test_assessment.py, tests/unit/test_install.py, tests/unit/test_runtime.py
=> Added filters to run only cloud specific task

pyproject.toml, src/databricks/labs/ucx/install.py, src/databricks/labs/ucx/workspace_access/generic.py, src/databricks/labs/ucx/workspace_access/scim.py
=> Enforce `mypy` validation

pyproject.toml, src/databricks/labs/ucx/install.py, src/databricks/labs/ucx/workspace_access/groups.py, tests/unit/test_install.py, tests/unit/workspace_access/test_groups.py
This PR reduces the size of `install.py` file
=> Decouple group configuration from `install.py`

pyproject.toml, src/databricks/labs/ucx/framework/install_state.py, src/databricks/labs/ucx/install.py, src/databricks/labs/ucx/mixins/fixtures.py, tests/integration/test_installation.py, tests/integration/workspace_access/test_groups.py, tests/unit/framework/test_wheels.py
This PR adds a level of parallelism to installer component and improves the speed of execution for installer-related integration test
=> Speedup installer execution

src/databricks/labs/ucx/hive_metastore/grants.py, src/databricks/labs/ucx/workspace_access/generic.py, src/databricks/labs/ucx/workspace_access/tacl.py, tests/unit/workspace_access/test_generic.py
* Retry internal error when getting permissions 
* Remove unused code
* Minor code refactorization to remove duplication
* Added comments
=> Retry internal error when getting permissions and update legacy table ACL documentation

tests/integration/workspace_access/test_groups.py
Addressed Error with Group Testing test_group_name_change_substitute by generating group names randomly.
=> Fixed flaky 'test_group_name_change_substitute'

tests/unit/assessment/test_dashboard.py
* Corrected unit test setup as per PR [740](https://github.com/databrickslabs/ucx/pull/740)
* Fixed corrupted state warning
=> Increased installation test coverage

.github/pull_request_template.md
This PR adds linked issues section to PR description
=> Added linked issues to PR template

src/databricks/labs/ucx/install.py
Fixed import in generated DEBUG.py notebook to work with new package layout.
Fixes #790
=> Fixed logger import path for DEBUG notebook

.github/ISSUE_TEMPLATE/bug.yml
Make it more clear that we don't want PII in issues.
=> Update `bug` issue template

tests/unit/test_cli.py
Increase the unit test coverage for `cli.py` to 99%
=> Increase the unit test coverage for cli.py

src/databricks/labs/ucx/queries/views/objects.sql
Changed classification of `DELTASHARING` table formats.
Resolves #789
=> Fixed handling of `DELTASHARING` table format.

src/databricks/labs/ucx/queries/assessment/main/00_5_count_total_views.sql
Adding the total View counts in the assessment dashboard.
closes #829 
Resolves #829
=> Adding the total View counts in the assessment dashboard

src/databricks/labs/ucx/assessment/clusters.py
Fixed and issue introduced with PR #825
=> Addressed integration test issue

src/databricks/labs/ucx/assessment/clusters.py, src/databricks/labs/ucx/assessment/jobs.py
Unified cluster handling. Changed _check_cluster_failures to a single type argument (ClusterDetails)
closes #838
=> Changed _check_cluster_failures to be more resilient.

tests/integration/hive_metastore/test_grants.py, tests/integration/workspace_access/test_tacl.py
Relates to #894
Resolves #..
Removed use of "default" HMS database in integration tests.
=> Make all tests use an ephemeral database per every run

tests/unit/test_cli.py
=> Fixed AWS CLI tests

docs/assessment.md
=> Updated assessment documentation

src/databricks/labs/ucx/assessment/azure.py, src/databricks/labs/ucx/assessment/crawlers.py, src/databricks/labs/ucx/assessment/secrets.py, tests/integration/assessment/test_azure.py
- Add client secret detection logic to Azure service principal crawler, this is needed for #874
=> Add secret detection logic to Azure service principal crawler

.github/workflows/acceptance.yml, tests/integration/conftest.py, tests/integration/hive_metastore/test_grants.py, tests/integration/test_installation.py, tests/integration/workspace_access/test_redash.py, tests/integration/workspace_access/test_tacl.py
This PR should fundamentally fix flaky tests
=> Run integration tests via `databrickslabs/sandbox/acceptance`

README.md
[![lines of code](https://tokei.rs/b1/github/databrickslabs/ucx)]([https://codecov.io/github/databrickslabs/ucx](https://github.com/databrickslabs/ucx))
=> Added tokei.rs lines of code badge

.github/workflows/acceptance.yml
Tested on https://github.com/databrickslabs/blueprint
=> Run integration tests only for pull requests ready for review

src/databricks/labs/ucx/framework/dashboards.py
Handles widget delete error from SDK
=> Handle widget delete on upgrade platform bug

install.sh
=> Deprecate legacy installer

pyproject.toml, src/databricks/labs/ucx/account.py, src/databricks/labs/ucx/assessment/jobs.py, src/databricks/labs/ucx/assessment/pipelines.py, src/databricks/labs/ucx/framework/dashboards.py, src/databricks/labs/ucx/hive_metastore/locations.py, src/databricks/labs/ucx/hive_metastore/table_migrate.py, src/databricks/labs/ucx/hive_metastore/tables.py, src/databricks/labs/ucx/hive_metastore/udfs.py, src/databricks/labs/ucx/mixins/sql.py, src/databricks/labs/ucx/workspace_access/listing.py
No logic changes, just for readability and to spare code reviewer's sanity.
=> Make code more readable by enforcing `max-nested-blocks = 3` with `pylint`

src/databricks/labs/ucx/assessment/aws.py, src/databricks/labs/ucx/cli.py, tests/unit/assessment/test_aws.py, tests/unit/test_cli.py
Added functionality to create all the missing External Location, pending a credential was created.
closes #1006
=> Added AWS S3 support for `migrate-locations` command

tests/unit/test_cli.py
=> Addressed issues and fix tests.

.github/workflows/acceptance.yml
See https://docs.github.com/en/actions/using-jobs/using-concurrency
=> Run only one `acceptance` job at a time

src/databricks/labs/ucx/cli.py, tests/unit/test_cli.py
Refactoring `@ucx.command` to avoid the need for `mocker.patch("databricks...)` in unit tests.
This resolves some TODO on #1037
=> Removed `mocker.patch("databricks...)` from `test_cli`

src/databricks/labs/ucx/framework/crawlers.py, src/databricks/labs/ucx/hive_metastore/table_migrate.py, src/databricks/labs/ucx/install.py, tests/integration/hive_metastore/test_migrate.py, tests/unit/hive_metastore/test_table_migrate.py
=> Added `migration_status` table to capture a snapshot of migrated tables

pyproject.toml
Updates the requirements on [databricks-labs-blueprint](https://github.com/databrickslabs/blueprint) to permit the latest version.
Pre-req for #1056, #1057
=> Update databricks-labs-blueprint requirement from ~0.4.1 to ~0.4.3

pyproject.toml, src/databricks/labs/ucx/mixins/fixtures.py, tests/integration/workspace_access/test_generic.py
=> Bump Databricks SDK to v0.22.0

tests/unit/assessment/test_clusters.py, tests/unit/assessment/test_dashboard.py, tests/unit/assessment/test_init_scripts.py, tests/unit/azure/test_access.py, tests/unit/azure/test_resources.py, tests/unit/hive_metastore/test_table_migrate.py, tests/unit/test_account.py
clean up unnecessary mocker usage
=> clean up unnecessary mocker usage

.github/workflows/push.yml
Related PR:
- https://github.com/databrickslabs/remorph/pull/191
=> Fail the build if `pylint` checks are disabled

src/databricks/labs/ucx/installer/policy.py, tests/unit/installer/test_policy.py, tests/unit/test_install.py
Fixes #1096
This is a quickfix. The long-term solution is tracked in #1098
=> Rely UCX on the latest 14.3 LTS DBR instead of 15.x

src/databricks/labs/ucx/hive_metastore/tables.py, src/databricks/labs/ucx/hive_metastore/tables.scala, src/databricks/labs/ucx/queries/assessment/main/05_0_all_tables.sql, src/databricks/labs/ucx/upgrades/v0.19.0_add_is_partitioned_column.py, tests/integration/test_installation.py
Resolves #871 
Related PR:
- https://github.com/databrickslabs/ucx/pull/985
=> Add `is_partitioned` column

src/databricks/labs/ucx/mixins/fixtures.py, src/databricks/labs/ucx/workspace_access/groups.py, tests/integration/workspace_access/test_generic.py, tests/integration/workspace_access/test_redash.py, tests/integration/workspace_access/test_scim.py, tests/integration/workspace_access/test_secrets.py, tests/performance/test_performance.py
Applied remaining feedback for #1080
Follow up for #1080
=> Simplify `migrated_group` permission migration fixture

CONTRIBUTING.md, README.md
- Add some details about writing testing fixtures to CONTRIBUTING.md
- Minor formatting changes
=> Added testing fixtures guidelines to `CONTRIBUTING.md`

pyproject.toml, tests/unit/source_code/test_files.py
This PR pins the versions of build dependencies
=> Pin versions of build toolchain

tests/unit/test_install.py
The original PR got merged but was low on coverage, so adding a quick fix to increase coverage
#1072
=> Increase coverage for new helper function

tests/unit/hive_metastore/test_mapping.py, tests/unit/test_install.py
2 unit tests failed after pytest upgrade due to incorrect error matching
=> Fixed failing unit tests

src/databricks/labs/ucx/runtime.py
Remove this leftover from #1160 
Resolves #..
=> Remove unused AclMigrationWhat import

tests/integration/workspace_access/test_groups.py
Added retry on Timeout error for the test failure
Resolves #1147
=> Added retry for test failing due to Timeout error

src/databricks/labs/ucx/hive_metastore/tables.scala
Added a fix for Views that are having NULL in table_format column instead of UNKNOWN 
Fixes https://github.com/databrickslabs/ucx/issues/1153
=> Fixed `NULL` values in `ucx.views.table_format` to have `UNKNOWN` value instead

tests/unit/hive_metastore/test_mapping.py
Fix failing test caused by change in underlying implementation
Resolves #1173 
Fixed unit test
=> fix issue by extracting the original exception

tests/unit/test_install.py
Fix failing test caused by change in underlying implementation
Resolves #1174 
Fixed unit test
=> Improved unit test for creating database

src/databricks/labs/ucx/framework/dashboards.py
Remove explicit warning for handling TypeError related to [ES-1061370](https://databricks.atlassian.net/browse/ES-1061370)
Resolves #1206
=> Remove explicit warning for handling TypeError

src/databricks/labs/ucx/hive_metastore/table_migrate.py
isolate grants computation when migrating tables 
fix pylint warnings
None
ran unit tests successfully
=> Isolate grants computation when migrating tables

src/databricks/labs/ucx/install.py, src/databricks/labs/ucx/installer/workflows.py, tests/integration/test_installation.py, tests/unit/test_install.py
Refactoring required for https://github.com/databrickslabs/ucx/pull/1209
=> Decouple `InstallState` from `WorkflowsDeployment` constructor

README.md
Add document for table migration workflow
Resolves #..
=> Add document for table migration workflow

src/databricks/labs/ucx/install.py, src/databricks/labs/ucx/installer/mixins.py, src/databricks/labs/ucx/installer/workflows.py
Refactoring required for https://github.com/databrickslabs/ucx/pull/1209
=> Inject `_TASKS` via constructor to `WorkflowsDeployment` instead of a global variable

docs/assessment.md
Fix assessment.md table of contents for the 300 series findings
Resolves #..
Tested in github browser.
=> Fix assessment.md table of contents for the 300 series findings

README.md
Update README file, to add a missing step "sync-workspace-info" in the Table Migration Workflow
=> Add missing step sync-workspace-info

src/databricks/labs/ucx/framework/tasks.py
=> Log more often from workflows

src/databricks/labs/ucx/assessment/workflows.py, src/databricks/labs/ucx/contexts/workflow_task.py, src/databricks/labs/ucx/framework/tasks.py, src/databricks/labs/ucx/hive_metastore/verification.py, src/databricks/labs/ucx/install.py, src/databricks/labs/ucx/installer/logs.py, src/databricks/labs/ucx/installer/workflows.py, src/databricks/labs/ucx/runtime.py, src/databricks/labs/ucx/workspace_access/generic.py, src/databricks/labs/ucx/workspace_access/redash.py, src/databricks/labs/ucx/workspace_access/tacl.py, src/databricks/labs/ucx/workspace_access/workflows.py, tests/integration/installer/test_logs.py, tests/integration/test_installation.py, tests/unit/assessment/test_workflows.py, tests/unit/framework/test_tasks.py, tests/unit/installer/test_logs.py, tests/unit/test_install.py, tests/unit/workspace_access/test_generic.py, tests/unit/workspace_access/test_redash.py, tests/unit/workspace_access/test_tacl.py
=> Forward remote logs on `run_workflow` and removed `destroy-schema` workflow in favour of `databricks labs uninstall ucx`

README.md, labs.yml, src/databricks/labs/ucx/cli.py, src/databricks/labs/ucx/install.py, src/databricks/labs/ucx/installer/logs.py, src/databricks/labs/ucx/installer/workflows.py, tests/unit/test_cli.py
=> Added `databricks labs ucx logs` command 

tests/unit/source_code/test_dbfs.py
- Extra test to cover the case of a constant not being a str
Resolves #..
=> feat: 1104 adds an extra test

NOTICE, pyproject.toml, src/databricks/labs/ucx/hive_metastore/table_migrate.py, src/databricks/labs/ucx/hive_metastore/tables.py, src/databricks/labs/ucx/hive_metastore/view_migrate.py, src/databricks/labs/ucx/mixins/fixtures.py, src/databricks/labs/ucx/source_code/queries.py, tests/integration/conftest.py, tests/integration/hive_metastore/test_migrate.py, tests/unit/hive_metastore/test_table_migrate.py, tests/unit/source_code/test_queries.py
Added a lookup based on "SHOW CREATE TABLE" to retrieve the list of columns from the create script.
=> Enhanced migrate views task to support views created with explicit column list

src/databricks/labs/ucx/source_code/python_linter.py, tests/unit/source_code/test_python_linter.py
implement required methods in PythonLinter
#1202 
Resolves #1379
=> Detect `sys.path` manipulation

src/databricks/labs/ucx/source_code/dependencies.py
=> document decision

src/databricks/labs/ucx/source_code/notebook.py, tests/unit/source_code/samples/notebook-with-pip-cell.py.txt, tests/unit/source_code/test_notebook.py
add PIP CellLanguage
https://github.com/databrickslabs/ucx/issues/1202
Resolves #1358
=> Added support for %pip cells

src/databricks/labs/ucx/mixins/fixtures.py, tests/integration/framework/test_fixtures.py
- Switch to Command Execution API on AWS
Resolves #1378
=> Fixed `make_dbfs_data_copy` fixture on AWS

src/databricks/labs/ucx/source_code/notebook_migrator.py
Add comment
https://github.com/databrickslabs/ucx/issues/1327
=> comment decision

tests/integration/test_installation.py
Wait for the group to be deleted.
Resolves #1324
=>  Fix test failure: `test_running_real_remove_backup_groups_job`

docs/external_hms_glue.md
Full end-user documentation for external HMS support
Part of #337
=> Expand documentation for end to end workflows with external HMS

src/databricks/labs/ucx/hive_metastore/grants.py, src/databricks/labs/ucx/hive_metastore/tables.py, src/databricks/labs/ucx/hive_metastore/udfs.py, src/databricks/labs/ucx/installer/logs.py, src/databricks/labs/ucx/workspace_access/manager.py, tests/unit/hive_metastore/test_tables.py
- This fixes `test_permission_for_files_anonymous_func` flakiness
=> Add error handling to udf crawling

tests/integration/conftest.py, tests/integration/hive_metastore/test_migrate.py
- Refactor `test_mapping_reverts_table` to not use `StaticTableMapping`.
=> remove `StaticTableMapping` class

tests/unit/hive_metastore/tables/tables_and_views.json, tests/unit/hive_metastore/test_views_sequencer.py
Improved chained circular dependency test case
Added new views to represent a chained circular dependency
=> Improved chain circular dependency test case

pyproject.toml, src/databricks/labs/ucx/source_code/dbfs.py, src/databricks/labs/ucx/source_code/python_linter.py
Configure pylint for est visitor callbacks
Drop corresponding pylint disable comments
None
=> configure pylint for ast visit_XXX callbacks

labs.yml, src/databricks/labs/ucx/cli.py, tests/unit/test_cli.py
Add two CLI commands to trigger table migration workflows
closes #670
=> Add CLI commands to trigger table migration workflow

tests/integration/test_installation.py
- The error message is now different
Resolves #1550
=> Fix `test_uninstallation`

tests/integration/azure/test_access.py
- This test should not run
Resolves #1543
=> Fix `test_create_global_spn`

src/databricks/labs/ucx/mixins/fixtures.py, src/databricks/labs/ucx/mixins/wspath.py, tests/integration/mixins/test_wspath.py
This PR allows for more unified work with workspace notebooks and files
Fix #1455
=> Added `.suffix` override for notebooks in `WorkspacePath`

README.md
Add missing step validate-external-locations to the flowchart
=> Add validate-external-locations to the flowchart

src/databricks/labs/ucx/assessment/clusters.py, src/databricks/labs/ucx/installer/workflows.py
Improved exception handling in the following cases:
- Write-protected dbfs
- Init script path is invalid
Resolves #1585
=> Improved exception handling

README.md
Document the `migrate-tables` command, and the relevant workflows
=> improved table migration documentation

labs.yml, src/databricks/labs/ucx/account/metastores.py, src/databricks/labs/ucx/account/workspaces.py, src/databricks/labs/ucx/cli.py, src/databricks/labs/ucx/contexts/application.py, src/databricks/labs/ucx/contexts/cli_command.py, src/databricks/labs/ucx/hive_metastore/mapping.py, tests/integration/test_account.py, tests/unit/account/test_metastores.py, tests/unit/account/test_workspaces.py, tests/unit/hive_metastore/test_mapping.py, tests/unit/test_cli.py
This PR splits `account.py` into few more modules, so that we can avoid circular dependencies the more work we do on the account level.
=> Convert `account.py` into `account` package

src/databricks/labs/ucx/account/aggregate.py
Small refactoring to enable things like:
- https://github.com/databrickslabs/ucx/issues/673
=> Added federated query

labs.yml
Labs commands failing due to small bug
=> Mapping values are not allowed in this context

src/databricks/labs/ucx/workspace_access/generic.py, tests/unit/workspace_access/test_generic.py
- Added error handling when listing serving endpoints, as it will raise NotFound error if the feature is disabled.
Resolves #1617
=> Addressed issue with disabled features in certain regions

pyproject.toml, src/databricks/labs/ucx/framework/dashboards.py
- upgrade databricks-sdk to 0.27, with refreshed API spec for Redash objects
=> Upgraded `databricks-sdk` to 0.27

labs.yml
- Added missing flags for `migrate-locations`
- Corrected description for `assign-metastore`
Resolves #1619
=> Fixed `migration-locations` and `assign-metastore` definition in `labs.yml`

src/databricks/labs/ucx/hive_metastore/udfs.py, src/databricks/labs/ucx/mixins/fixtures.py, src/databricks/labs/ucx/queries/assessment/main/00_6_count_total_udfs.sql, src/databricks/labs/ucx/queries/assessment/main/10_0_all_tables.sql, src/databricks/labs/ucx/queries/assessment/main/10_0_all_udfs.sql, src/databricks/labs/ucx/upgrades/v0.23.0_add_assessment_to_udf.py, tests/integration/hive_metastore/test_udfs.py, tests/unit/hive_metastore/test_grants.py, tests/unit/hive_metastore/test_udfs.py
- Added UDF function assessment
Resolves #884, #1118
=> Added UDFs assessment

README.md, docs/table_persistence.md, docs/table_upgrade.md
- Refreshed ToC & fixed some grammar errors
=> Small updates to documentation

docs/assessment.md, src/databricks/labs/ucx/assessment/clusters.py, src/databricks/labs/ucx/assessment/crawlers.py, src/databricks/labs/ucx/assessment/init_scripts.py, tests/unit/assessment/test_clusters.py, tests/unit/assessment/test_jobs.py
- Clarified unsupported config in compute crawler that they are related to Hive metastore. Expanded the error message, and the recommended remediate approach
Resolves #1658
=> Clarified unsupported config in compute crawler

src/databricks/labs/ucx/hive_metastore/table_migrate.py, tests/unit/hive_metastore/test_table_migrate.py
- As we are migrating multiple tables & views in parallel, any error in SQL execution should not fail the workflow. Added error handling to all `sql_backend.execute` commands
Resolves #1676
=> Improved error handling for all queries executed during table migration

src/databricks/labs/ucx/source_code/jobs.py, tests/integration/source_code/test_jobs.py, tests/unit/source_code/test_jobs.py
Emit the problems with the code belonging to a job during the lin job
Relates to #1542
=> Emit problems with code belonging to job

README.md
README addition for incompatibility with Standard Workspaces.
=> README update about Standard workspaces

pyproject.toml
Exclude samples from make verify
=> Exclude samples from make verify

src/databricks/labs/ucx/hive_metastore/locations.py, tests/unit/hive_metastore/test_locations.py
- Add s3a/s3n to list of supported prefix
Resolves #1722
=> Support for s3a/ s3n protocols when using mount point

src/databricks/labs/ucx/mixins/fixtures.py, tests/integration/framework/test_fixtures.py
Add RemoveAfter property to additional artifacts
Add it as property to:
tables
schemas
Party introduces #977
=> [internal] Add RemoveAfter property to additional testing artifacts

tests/integration/source_code/test_jobs.py
relay logs when test_running_real_workflow_linter_job fails
#1738
=> [internal] Improve logs when test_running_real_workflow_linter_job fails

tests/integration/hive_metastore/test_workflows.py
relay logs when assertions fail
#1739
=> [internal] Improve logs when test_table_migration_job_refreshes_migration_status fails

src/databricks/labs/ucx/source_code/jobs.py
Add logs when running jobs
None
=> More longs for triggering workflows

src/databricks/labs/ucx/contexts/application.py, src/databricks/labs/ucx/source_code/graph.py, src/databricks/labs/ucx/source_code/python_libraries.py, tests/unit/source_code/notebooks/test_cells.py, tests/unit/source_code/test_dependencies.py, tests/unit/source_code/test_files.py, tests/unit/source_code/test_graph.py, tests/unit/source_code/test_jobs.py, tests/unit/source_code/test_notebook.py, tests/unit/source_code/test_path_lookup_simulation.py, tests/unit/source_code/test_s3fs.py
This PR reduces unnecessary code indirection
=> Simplify library resolution logic

src/databricks/labs/ucx/contexts/workspace_cli.py
=> Fix crasher when running migrate-local-code

src/databricks/labs/ucx/source_code/jobs.py, tests/integration/source_code/test_jobs.py
=> Added workflow linter for spark python tasks

src/databricks/labs/ucx/source_code/jobs.py, tests/integration/source_code/test_jobs.py, tests/unit/source_code/test_jobs.py
=> Add workflow linter for delta live tables task

tests/integration/test_installation.py
Add retry annotations
Resolves #1827
=> Fix flaky test 1827

tests/integration/workspace_access/test_groups.py
Retry on ResourceConflict
Resolves #1831
=> Fix flaky test #1831

src/databricks/labs/ucx/source_code/graph.py
=> Fix incorrect import

src/databricks/labs/ucx/source_code/graph.py
Remove finished TODO #1643 from code
=> Remove finished TODO #1643 from code

src/databricks/labs/ucx/installer/workflows.py, tests/integration/test_installation.py, tests/unit/conftest.py, tests/unit/installer/test_workflows.py
Remove test jobs created in CI after twelve hours
Helps with investigating #1857
=> Remove test jobs created during nightly builds after twelve hours

src/databricks/labs/ucx/source_code/graph.py, src/databricks/labs/ucx/source_code/linters/imports.py, tests/unit/source_code/conftest.py, tests/unit/source_code/linters/test_python_imports.py, tests/unit/source_code/samples/sys-path-with-fstring.py, tests/unit/source_code/test_dependencies.py
Infer value of sys.path.xxx() calls and raise advice if unresolved
Progresses #1205
Replaces PR #1863
=> Support inferred values when linting sys path

src/databricks/labs/ucx/source_code/linters/pyspark.py, tests/unit/source_code/linters/test_pyspark.py, tests/unit/source_code/samples/functional/file-access/direct-fs2.py
Infer value of tables spark.sql() calls and raise advice if unresolved
Progresses #1205
=> Support inferred values when linting spark.sql

src/databricks/labs/ucx/assessment/crawlers.py, src/databricks/labs/ucx/source_code/base.py, src/databricks/labs/ucx/source_code/jobs.py, tests/unit/source_code/test_jobs.py
This PR adds propagation of named parameters from jobs to current session state. Additionally, we also check for DBFS paths as named and positional parameters.
=> Propagate widget parameters and data security mode to `CurrentSessionState`

NOTICE
Adding proper notices forgotten in https://github.com/databrickslabs/ucx/pull/1835
=> Added `astroid` to `NOTICE` file

src/databricks/labs/ucx/source_code/notebooks/cells.py
This PR fixes a docstring mistake introduced in #1855.
=> Fix incorrect example in docstring.

tests/integration/source_code/test_libraries.py, tests/unit/source_code/samples/pip_install_multiple_packages.py
Add integration test for installing multiple packages from PyPi
=> Add integration test for installing multiple packages from PyPi

src/databricks/labs/ucx/source_code/base.py, tests/unit/source_code/test_functional.py
Drop usage of typing_extensions
Resolves #1875
=> drop usage of typing_extensions

src/databricks/labs/ucx/source_code/linters/dbfs.py, src/databricks/labs/ucx/source_code/queries.py, tests/unit/source_code/linters/test_dbfs.py, tests/unit/source_code/test_queries.py
Generate Failure when sqlglot fails to parse query
None
=> catch sqlglot exceptions and convert them to advices

src/databricks/labs/ucx/source_code/queries.py, tests/unit/source_code/test_queries.py
Fix crasher and update test suite
None
None
=> Fix crasher with latest sqlglot

tests/integration/source_code/solacc.py
Provides structured details of missing imports
Progresses #1912
=> Improve solacc script output

src/databricks/labs/ucx/source_code/known.json
=> Analyse `hyperopt`

src/databricks/labs/ucx/source_code/known.json
=> whitelist glow

src/databricks/labs/ucx/source_code/known.json
=> whitelist sklearn

src/databricks/labs/ucx/source_code/known.json
manually whitelist solacc.companion
None
=> manually whitelist solacc.companion

src/databricks/labs/ucx/source_code/known.json
=> whitelist fastcluster

src/databricks/labs/ucx/source_code/known.json
=> whitelist spark-nlp

src/databricks/labs/ucx/source_code/known.json
=> whitelist dbldatagen

src/databricks/labs/ucx/source_code/known.json
=> whitelist delta-spark

src/databricks/labs/ucx/source_code/known.json
=> whitelist graphframes

src/databricks/labs/ucx/source_code/known.json
=> whitelist omegaconf

src/databricks/labs/ucx/source_code/known.json
=> whitelist johnsnowlabs

src/databricks/labs/ucx/source_code/linters/dbfs.py, src/databricks/labs/ucx/source_code/queries.py, tests/unit/source_code/linters/test_dbfs.py
use dedicated advice code for unsupported sql
None
None
Not tested
=> use dedicated advice code for unsupported sql

src/databricks/labs/ucx/install.py, tests/unit/test_collection.py
Prompt about joining a collection of ucx installs early
Resolves #1960
=> Prompt about joining a collection of ucx installs early

src/databricks/labs/ucx/source_code/known.json
remove noise in whitelist
None
=> remove noise in whitelist

src/databricks/labs/ucx/source_code/jobs.py
Log the right amount of lint problems, now it is less than the actual number. Incorrect message is introduced in #1956, fixing here.
=> Log the right amount of lint problems

src/databricks/labs/ucx/source_code/known.json
=> whitelist mmf_sa

src/databricks/labs/ucx/source_code/known.json
=> whitelist h3

src/databricks/labs/ucx/source_code/known.json
=> whitelist bioinfokit

src/databricks/labs/ucx/source_code/known.json
=> whitelist tenacity

src/databricks/labs/ucx/source_code/known.json
=> whitelist opencv-python

.spr.yml
**Stack**:
- adding stacked PR checks #2096 ⬅
- Feature 3 #2095
- Feature 2 #2094
- Feature 1 #2093
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
=> adding stacked PR checks

src/databricks/labs/ucx/source_code/known.json
=> whitelist msal

src/databricks/labs/ucx/source_code/known.json
=> whitelist momentfm

src/databricks/labs/ucx/source_code/known.py
document whitelist limitations in code
None
Not tested
=> document whitelist limitations in code

src/databricks/labs/ucx/source_code/known.json
manually whitelist legacy azure
None
=> manually whitelist legacy azure

src/databricks/labs/ucx/source_code/known.json
=> whitelist blessed

src/databricks/labs/ucx/source_code/known.json
=> whitelist distro

src/databricks/labs/ucx/source_code/known.json
=> whitelist fastprogress

src/databricks/labs/ucx/source_code/known.json
=> whitelist h11

src/databricks/labs/ucx/source_code/known.json
=> whitelist pickleshare

src/databricks/labs/ucx/source_code/known.json
=> whitelist referencing

src/databricks/labs/ucx/source_code/known.json
=> whitelist slicer

src/databricks/labs/ucx/source_code/known.json
=> whitelist xmod

src/databricks/labs/ucx/source_code/notebooks/cells.py, tests/unit/source_code/samples/root1.magic.py, tests/unit/source_code/test_dependencies.py
register child notebooks from magic lines in dependency-graph
Progresses #2155 
None
=> register child notebooks from magic lines in dependency-graph

tests/integration/install/test_installation.py
Change timeout logic
Resolves #1907 
None
None
=> tentatively fix test_running_real_remove_backup_groups_job

pyproject.toml, tests/integration/cmds.py
Added automation for programmatically collecting command and workflow names
=> [internal] script for retrieving list of workflows and commands

src/databricks/labs/ucx/installer/workflows.py, tests/unit/conftest.py, tests/unit/installer/test_workflows.py
Handle log folder does not exists
Resolves #2171
Resolves #2172
Resolves #2175
Resolves #2176
Resolves #2177
Resolves #2179
Resolves #2180
=> Handle log folder does not exists

src/databricks/labs/ucx/hive_metastore/catalog_schema.py, tests/unit/test_cli.py
CLI command create-catalogs-schemas sometimes fails if the catalog/schema already exists. The _get_missing_catalogs_schemas should help to avoid re-creating existing ones, but this seems like an edge case.
Resolves #1939
=> Adding extra error handling as already exists error occurs

src/databricks/labs/ucx/source_code/jobs.py, tests/unit/source_code/test_jobs.py
This PR corrects some grammar in logged warnings.
=> Minor grammar corrections in logged warnings

README.md, src/databricks/labs/ucx/install.py, tests/integration/conftest.py, tests/integration/install/test_installation.py, tests/unit/test_install.py
Improve error messages in case of connection errors
Partially resolves #1323
=> Improve error messages in case of connection errors

tests/integration/install/test_installation.py
Increase timeout for sequence of slow preliminary jobs
Resolves #2219 
None
Not tested
=> Increase timeout for sequence of slow preliminary jobs

src/databricks/labs/ucx/install.py, src/databricks/labs/ucx/installer/workflows.py, tests/unit/test_install.py
Stacked on top of #2224
Parallelize the install deployment as follows:
=> Update installation parallelization

src/databricks/labs/ucx/install.py, src/databricks/labs/ucx/installer/workflows.py, tests/unit/test_install.py
Database creation should be done asynchronously. Mypy probably missed this as the method did not have any type hints. Introduced in #1920
=> Fix create database in workspace installation

docs/assessment.md
This PR fixes some spelling mistakes and improves the formatting/flow for some of our documentation.
=> Documentation spelling/copy improvements

src/databricks/labs/ucx/workspace_access/groups.py
This PR contains logging improvements in the group manager to help understand (potential) causes of problems during group migration.
Relates #2227.
- modified existing workflow: `group-migration`
=> Group migration: additional logging

src/databricks/labs/ucx/install.py, src/databricks/labs/ucx/queries/assessment/main/01_0_compatibility.sql, src/databricks/labs/ucx/queries/assessment/main/01_1_count_jobs.sql, src/databricks/labs/ucx/queries/assessment/main/01_3_count_table_by_type_location_format.sql
Dashboard issues arose after formatting the quries
=> Update dashboard install using latest `lsql` release

src/databricks/labs/ucx/aws/locations.py, tests/integration/aws/test_access.py, tests/unit/aws/test_access.py
=> Use deterministic names to create AWS external locations

src/databricks/labs/ucx/framework/utils.py
Removed LRU cache from AWS command line
closes #2269
=> Removed `@lru_cache` from `run_command`

src/databricks/labs/ucx/cli.py
Improve type checking in cli command
Would have avoided #2221
None
None
=> Improve type checking in cli command

tests/integration/framework/test_fixtures.py
This PR fixes some tests that check the value of `RemoveAfter` tags: they check how far into the future the tag-value is, and this can now be up to 2 hours due to rounding upwards introduced in #2265.
@ericvergnaud observed some failing acceptance tests on #2330, which this will fix.
Resolves #2287.
Resolves #2288.
Resolves #2289.
Resolves #2290.
- updated integration tests
=> Fix tests that check the `RemoveAfter` tag values.

src/databricks/labs/ucx/cli.py
Fix `report-account-compatibility` cli command docstring as it was a copy of `sync-workspace-info`
=> Fix `report-account-compatibility` cli command docstring

README.md
Add troubleshooting guide in README for self-signed SSL certification and proxy server related error.
=> Add troubleshooting guide for self-signed SSL cert related error

src/databricks/labs/ucx/source_code/linters/files.py
rename field in LocalFileLinter
None
None
=> Rename for clarity

src/databricks/labs/ucx/mixins/fixtures.py
Lakeview names should be unique. Enforced by Lakeview internals from now onward.
Resolves #2345
=> Make Lakeview names unique

src/databricks/labs/ucx/install.py
Retry dashboard install on DeadlineExceeded
Resolves #2376 
Resolves #2377 
Resolves #2389
=> Retry dashboard install on DeadlineExceeded

src/databricks/labs/ucx/source_code/base.py
This PR updates the detection during linting of whether a file is a notebook or not for non-Workspace paths so that when performing the header-check we only read the start of the file (enough for the header) instead of loading it all. This is an optimisation rather than an issue of correctness.
- existing unit tests
=> Optimisation: when detecting if a file is a notebook only read the start instead of the whole file

docs/table_persistence.md, src/databricks/labs/ucx/assessment/workflows.py
Update the list of UCX objects and their respective metadata
Updates documentation #2121
=> Update the list of UCX objects and their respective metadata

src/databricks/labs/ucx/source_code/known.json
Installed python packages from 14.3 DBR list to be whitelisted
Adds #1931
=> Python packages from DBR 14.3+

src/databricks/labs/ucx/installer/policy.py
closes #2420 
The current setup didn't detect attribute like spark.hadoop.hive.metastore.uris
=> Update ext hms detection to include more conf attributes

src/databricks/labs/ucx/cli.py, src/databricks/labs/ucx/hive_metastore/table_migrate.py
=> Fixed support for table/schema scope for the revert table cli command

src/databricks/labs/ucx/assessment/aws.py, src/databricks/labs/ucx/aws/access.py, src/databricks/labs/ucx/aws/locations.py, tests/integration/aws/test_access.py, tests/integration/conftest.py, tests/unit/aws/test_access.py
Partially resolves #2360 (AWS)
=> Clean up left over uber principal resources for AWS

src/databricks/labs/ucx/hive_metastore/tables.py
This PR updates some changes introduced in #2477 where it looks like merging the changes from #2402 went awry. 
Progresses 2074, updates #2477.
=> Re-merge: `CrawlerBase` and `FasterTableScanCrawler`

src/databricks/labs/ucx/source_code/graph.py, src/databricks/labs/ucx/source_code/jobs.py, tests/integration/source_code/test_jobs.py, tests/unit/source_code/test_jobs.py
Use structured lineage for DependencyGraph
Resolves #2550
None
=> Use structured lineage for DependencyGraph

src/databricks/labs/ucx/hive_metastore/table_migrate.py, tests/unit/hive_metastore/test_table_migrate.py
=> Adding comment on the source tables to capture that they have been deprecated

labs.yml, src/databricks/labs/ucx/cli.py
Remove ACL type params from migrate ACL CLI command.
=> Fixed migrate acls CLI command.

src/databricks/labs/ucx/hive_metastore/grants.py, src/databricks/labs/ucx/hive_metastore/locations.py, src/databricks/labs/ucx/hive_metastore/tables.py
This PR deals with some nits that I noticed amongst the crawlers while working on #2566, but omitted to avoid distracting from the focus of that PR. These do not result in any functional changes.
=> [TECH DEBT]: Deal with some nits in the existing crawler code

tests/unit/test_cli.py
Fix tests failing locally 
None
None
=> fix tests failing locally

README.md
Improve documentation on using account profile for `sync-workspace-info` cli command
Resolves #1762
=> [DOCUMENTATION] Improve documentation on using account profile for `sync-workspace-info` cli command

src/databricks/labs/ucx/workspace_access/generic.py, tests/unit/workspace_access/test_generic.py
=> Handle `InternalError` in `Listing.__iter__`

src/databricks/labs/ucx/contexts/workflow_task.py, src/databricks/labs/ucx/hive_metastore/table_size.py, src/databricks/labs/ucx/hive_metastore/tables.py, src/databricks/labs/ucx/source_code/known.json, tests/unit/hive_metastore/test_table_size.py
We were not doing that before and now we do.
=> Speedup assessment workflow by making DBFS root table size calculation parallel

src/databricks/labs/ucx/source_code/linters/from_table.py, tests/unit/source_code/linters/test_from_table.py
=> Fix sqlglot crasher with 'drop schema ...' statement

src/databricks/labs/ucx/hive_metastore/mapping.py
Fixes incorrect error message discovered while working on something else
=> Fixes error message

src/databricks/labs/ucx/source_code/known.json
whitelist blis
Progress on #1931
=> whitelist blis

src/databricks/labs/ucx/source_code/known.json
whitelist brotli
Partly resolves #1931
=> whitelists brotli

src/databricks/labs/ucx/source_code/known.json
=> Whitelist `catalogue` library

src/databricks/labs/ucx/source_code/known.json
=> Whitelists cloudpathlib

src/databricks/labs/ucx/source_code/known.json, src/databricks/labs/ucx/source_code/python/python_analyzer.py, tests/unit/source_code/test_directfs_access.py, tests/unit/source_code/test_known.py, tests/unit/source_code/test_queries.py
Increase test coverage to avoid failing CI with code changes hat cannot be unit tested
None
None
=> [TECHDEBT] Increase test coverage

src/databricks/labs/ucx/source_code/known.json
=> Whitelists circuitbreaker

src/databricks/labs/ucx/source_code/known.json
=> Whitelists colorful

src/databricks/labs/ucx/source_code/known.json
=> Whitelists cymem

src/databricks/labs/ucx/source_code/known.json
=> Whitelists dacite

src/databricks/labs/ucx/source_code/known.json
=> Whitelists dbl-tempo

tests/integration/source_code/test_jobs.py
Fix "too many values to unpack" error in integration tests introduced in #2772
Resolves #2806
Resolves #2805
Resolves #2804
Resolves #2803
Resolves #2802
Resolves #2801
Resolves #2799
Resolves #2798
=> Fix "too many values to unpack" error in integration tests

src/databricks/labs/ucx/contexts/application.py, src/databricks/labs/ucx/source_code/linters/pyspark.py
Fix issues
Resolves #2800
Resolves #2808 
None
=> Fix integration issue when collecting tables

src/databricks/labs/ucx/source_code/known.json
=> Added `cmdstanpy` to known list

src/databricks/labs/ucx/source_code/known.json
=> Added `dm-tree` library to known list

src/databricks/labs/ucx/source_code/known.json
=> Added `diskcache` library to known list

src/databricks/labs/ucx/source_code/known.json
whitelist aiohttp-cors
Partly resolves #1931
=> Added `aiohttp-cors` library to known list

src/databricks/labs/ucx/source_code/known.json
=> Added `configparser` library to known list

src/databricks/labs/ucx/source_code/known.json
Added Farama-Notifications to known list
=> Added `Farama-Notifications` to known list

src/databricks/labs/ucx/source_code/known.json
Changes
Added google-auth-oauthlib and dependent libraries to known list
Linked issues
Partly resolve https://github.com/databrickslabs/ucx/issues/1931
=> Added `google-auth-oauthlib` and dependent libraries to known list

src/databricks/labs/ucx/source_code/known.json
Added `greenlet` to known list 
=> Added `greenlet` to known list

tests/unit/workspace_access/test_tacl.py
This PR adds some type hints to the `test_tacl` unit tests, and then:
- Resolves type-checking and linting issues.
- Drops an unused mock.
=> Type hint unit tests, drop unused mock, resolve linting issues.

src/databricks/labs/ucx/contexts/application.py, src/databricks/labs/ucx/hive_metastore/verification.py, src/databricks/labs/ucx/installer/workflows.py, src/databricks/labs/ucx/progress/workflows.py, tests/unit/conftest.py, tests/unit/contexts/test_application.py, tests/unit/hive_metastore/test_verification.py, tests/unit/progress/test_workflows.py
Verify UCX catalog is accesible at start of `migration-progress-experimental` workflow
Resolves #2577
Resolves #2848
Progresses #2816
=> Verify UCX catalog is accessible at start of `migration-progress-experimental` workflow

tests/integration/hive_metastore/test_migrate.py
Test looked to be fixed already
Resolves #2779
=> Fix test failure: `test_migrate_external_table_failed_sync`

tests/integration/source_code/test_jobs.py
Use genuinely unfond library
None
None
=> Fix test_job_dlt_task_linter_unhappy_path

tests/integration/source_code/test_jobs.py
Use genuinely unknown library
None
None
- [ x] updated integration tests
=> Fix failing test test_job_task_linter_library_not_installed_cluster

src/databricks/labs/ucx/source_code/known.json
Added google-cloud-core to known list
=> Added `google-cloud-core` to known list

src/databricks/labs/ucx/source_code/known.json
Added `gviz-api` to known list 
=> Added `gviz-api` to known list

tests/unit/source_code/samples/functional/file-access/volumes.py
Add a functional test that proves that #2850 is already fixed
Resolves #2850
None
=> Add functional test related to bug #2850

src/databricks/labs/ucx/source_code/jobs.py
=> Fixed `assessment` workflow failure for jobs running tasks on existing interactive clusters

src/databricks/labs/ucx/hive_metastore/tables.py
=> Ignore UCX inventory database in HMS while scanning tables

src/databricks/labs/ucx/source_code/known.json
=> Added `htmlmin` to known list

src/databricks/labs/ucx/source_code/jobs.py
=> Fix downloading wheel libraries from DBFS on mounted Azure Storage fail with access denied

src/databricks/labs/ucx/source_code/path_lookup.py
Comment code
None
None
Not tested
=> Comment code

labs.yml, src/databricks/labs/ucx/cli.py, src/databricks/labs/ucx/contexts/workspace_cli.py, src/databricks/labs/ucx/hive_metastore/federation.py, tests/integration/hive_metastore/test_federation.py, tests/unit/hive_metastore/test_federation.py
=> Experimental support for HMS federation

src/databricks/labs/ucx/source_code/known.json
Added `isodate` to known list 
=> Added `isodate` to known list

src/databricks/labs/ucx/source_code/linters/from_table.py, src/databricks/labs/ucx/source_code/sql/sql_parser.py, tests/unit/source_code/sql/test_sql_parser.py
This PR fixes inadequate parsing quality from SQLglot
=> Improve robustness of `sqlglot` failure handling

src/databricks/labs/ucx/hive_metastore/table_migration_status.py, tests/integration/hive_metastore/test_migrate.py
=> Fixed an issue with source table deleted after migration

src/databricks/labs/ucx/source_code/known.json
Added `jax-jumpy` to known list 
=> Added `jax-jumpy` to known list

src/databricks/labs/ucx/hive_metastore/catalog_schema.py, tests/integration/conftest.py, tests/integration/hive_metastore/test_catalog_schema.py
=> Addressing Ownership Conflict when creating catalog/schemas

src/databricks/labs/ucx/source_code/known.json
Added `joblibspark` to known list 
=> Added `joblibspark` to known list

src/databricks/labs/ucx/source_code/known.json
Added `langcodes` to known list 
=> Added `langcodes` to known list

src/databricks/labs/ucx/source_code/known.json
Added `jsonpatch` to known list
=> Added `jsonpatch` to known list

src/databricks/labs/ucx/assessment/jobs.py
=> simplify code of airflow job detection

src/databricks/labs/ucx/source_code/known.json
Added `lazy_loader` to known list
=> Added `lazy_loader` to known list

src/databricks/labs/ucx/source_code/known.json
=> Added `librosa` to known list

src/databricks/labs/ucx/source_code/known.json
=> Added `lz4` to known list

src/databricks/labs/ucx/source_code/known.json
Added `linkify-it-py` to known list 
=> Added `linkify-it-py` to known list

tests/unit/hive_metastore/test_table_migrate.py
This PR updates a unit test that monkey-patched the system `datetime` implementation but did not restore the original when the test finished. Depending on the order of test collection, execution, and allocation across pytest workers this can affect subsequent tests.
Broke (unit) tests in #2743.
=> Unit test fix: restore monkey-patched `datetime` when test finishes

src/databricks/labs/ucx/source_code/known.json
Added `mdit-py-plugins` to known list 
=> Added `mdit-py-plugins` to known list

src/databricks/labs/ucx/source_code/known.json
Added `murmurhash` to known list
=> Added `murmurhash` to known list

src/databricks/labs/ucx/source_code/known.json
Added `multimethod` to known list 
=> Added `multimethod` to known list

src/databricks/labs/ucx/source_code/known.json
Added `msal-extensions` to known list 
=> Added `msal-extensions` to known list

src/databricks/labs/ucx/source_code/known.json
Added `nvidia-ml-py` to known list 
=> Added `nvidia-ml-py` to known list

src/databricks/labs/ucx/source_code/known.json
=> Added `ninja` to known list

src/databricks/labs/ucx/contexts/workflow_task.py, src/databricks/labs/ucx/progress/jobs.py, tests/unit/progress/test_jobs.py
=> Combine static code analysis results with historical job snapshots

tests/integration/hive_metastore/test_migrate.py
There were faulty integration tests introduced by #2892, this PR temporarily disables them.
Related to #3054
Related to #3055
=> Snooze faulty integration tests introduced by #2892

src/databricks/labs/ucx/progress/grants.py, tests/unit/progress/test_grants.py
Add grant progress encoder
Resolves #3058
=> Add grant progress encoder

labs.yml, src/databricks/labs/ucx/cli.py, src/databricks/labs/ucx/contexts/application.py, src/databricks/labs/ucx/hive_metastore/grants.py, src/databricks/labs/ucx/install.py, tests/integration/hive_metastore/test_migrate.py, tests/unit/hive_metastore/test_migrate_acls.py
=> Added `--dry-run` option for ACL migrate

src/databricks/labs/ucx/assessment/clusters.py
Some clean up coming out of #3081
=> [TECH DEBT] Code clean up in cluster module

src/databricks/labs/ucx/assessment/secrets.py
=> Fixed `UnknownHostException` on the specified KeyVault

src/databricks/labs/ucx/hive_metastore/locations.py
=> Fixed `assert curr.location is not None`

pyproject.toml, src/databricks/labs/ucx/source_code/linters/directfs.py, src/databricks/labs/ucx/source_code/python/python_ast.py, tests/unit/source_code/test_directfs_access.py
this PR just increases unit test coverage on `main`
=> [chore] improve unit test coverage

tests/unit/source_code/test_directfs_access.py
Remove unused import, was blocking the CI
=> Remove unused import

src/databricks/labs/ucx/source_code/known.json
=> Added `phik` to known list

src/databricks/labs/ucx/source_code/known.json
Added `py-cpuinfo` to known list 
=> Added `py-cpuinfo` to known list

src/databricks/labs/ucx/source_code/known.json
Added `preshed` to known list 
=> Added `preshed` to known list

src/databricks/labs/ucx/source_code/graph.py, src/databricks/labs/ucx/source_code/linters/files.py, src/databricks/labs/ucx/source_code/notebooks/cells.py, src/databricks/labs/ucx/source_code/notebooks/magic.py, src/databricks/labs/ucx/source_code/notebooks/sources.py, src/databricks/labs/ucx/source_code/python/python_analyzer.py
=> bubble-up parsing problems via InheritedContext

.github/workflows/acceptance.yml
=> [internal] remove todo

tests/integration/hive_metastore/test_table_move.py
=> [internal] Bring back disabled integration tests

tests/integration/assessment/test_workflows.py, tests/integration/conftest.py
=> Introduced `make_cluster_policy` and `make_cluster_policy_permissions` to `MockInstallation`

tests/integration/workspace_access/test_generic.py
=> Skip `test_feature_tables` integration test

pyproject.toml, src/databricks/labs/ucx/workspace_access/workflows.py, tests/integration/install/test_installation.py, tests/integration/workspace_access/test_workflows.py
=> Move integration test to correct place

src/databricks/labs/ucx/cli.py
Ran into this locally, might be a locally corrupted config
=> Handle not parsing config in cli

README.md, docs/migration-progress.md
Add migration progress design documentation
Progresses #2074
Related #3067
=> Add migration progress documentation

src/databricks/labs/ucx/contexts/workflow_task.py, src/databricks/labs/ucx/progress/jobs.py, src/databricks/labs/ucx/source_code/directfs_access.py, tests/integration/conftest.py, tests/integration/progress/test_jobs.py, tests/unit/progress/test_jobs.py
Track `DirectFsAccess` on `JobsProgressEncoder`
Resolves #3059
=> Track `DirectFsAccess` on `JobsProgressEncoder`

README.md
Got lost in https://github.com/databrickslabs/ucx/pull/3211
=> Add note about running assessment once

src/databricks/labs/ucx/hive_metastore/workflows.py, src/databricks/labs/ucx/installer/workflows.py, src/databricks/labs/ucx/progress/workflows.py, src/databricks/labs/ucx/recon/workflows.py, src/databricks/labs/ucx/workspace_access/workflows.py, tests/integration/conftest.py, tests/integration/hive_metastore/test_ext_hms.py
Replaced table_migration job cluster to user_isolation job cluster. Its just a naming change and updated in all placed where there is reference
Resolves #3172
=> changing table_migration to user_isolation

src/databricks/labs/ucx/progress/jobs.py
Remove cached property from JobProgressEncoder
Resolves #3377
=> Remove cached property from `JobProgressEncoder`

src/databricks/labs/ucx/aws/access.py, src/databricks/labs/ucx/aws/locations.py, src/databricks/labs/ucx/azure/access.py, src/databricks/labs/ucx/azure/locations.py, src/databricks/labs/ucx/contexts/application.py, src/databricks/labs/ucx/hive_metastore/federation.py, src/databricks/labs/ucx/hive_metastore/locations.py, tests/unit/aws/test_access.py, tests/unit/azure/test_access.py, tests/unit/azure/test_credentials.py, tests/unit/hive_metastore/test_federation.py, tests/unit/hive_metastore/test_locations.py, tests/unit/test_cli.py
Closes #3406 
Add external location for DBFS root location
=> DBFS Root Support for HMS Federation

src/databricks/labs/ucx/hive_metastore/federation.py
Removed dependency on "packaging" package to address release issue.
=> Removed "packaging" package dependency

tests/integration/conftest.py, tests/integration/workspace_access/test_workflows.py
Add fixtures to context and change usages accordingly
Resolves #3428 and #3429
=> Adds existing fixtures to context and change usages accordingly

src/databricks/labs/ucx/assessment/pipelines.py, tests/unit/assessment/test_pipelines.py
Scope crawled pipelines in PipelineCrawler using the new include_pipeline_ids argument
Introduces #3493
=> Scope crawled pipelines in PipelineCrawler

tests/integration/install/test_installation.py
Skip integration test that compares remote and local version on release branch.
The `databricks.labs.ucx.__about__.__version__` is bumped on the release branch BEFORE the git tag is bumped. The git tag is bumped during release AFTER merging the release branch. Therefore, there this test is expected to fail on a release branch that introduces a major or minor version bump.
Resolves #3533
=> Skip integration test that compares remote and local version on release branch

labs.yml, src/databricks/labs/ucx/assessment/aws.py, src/databricks/labs/ucx/aws/access.py, src/databricks/labs/ucx/aws/credentials.py, src/databricks/labs/ucx/aws/locations.py, src/databricks/labs/ucx/cli.py, src/databricks/labs/ucx/contexts/workspace_cli.py, src/databricks/labs/ucx/hive_metastore/federation.py, src/databricks/labs/ucx/hive_metastore/grants.py, tests/integration/assessment/test_aws.py, tests/integration/aws/test_credentials.py, tests/integration/conftest.py, tests/unit/assessment/test_aws.py, tests/unit/aws/test_access.py, tests/unit/aws/test_credentials.py, tests/unit/hive_metastore/test_federation.py
=> HMS Federation Glue Support

.github/workflows/release.yml
Moved release.yml to hosted runner
=> Hosted Runner for release

src/databricks/labs/ucx/hive_metastore/mapping.py, tests/unit/hive_metastore/test_mapping.py, tests/unit/test_cli.py
=> Fixed Skip/Unskip schema functionality 

labs.yml, src/databricks/labs/ucx/cli.py, src/databricks/labs/ucx/contexts/application.py
Added cli command for migration DLT pipelines with the flags for limiting the pipelines ids
Introduces #3107
=> Added the CLI command for migrating DLT pipelines

docs/ucx/docs/process/index.mdx, docs/ucx/docs/reference/commands/index.mdx
Added documentation for the usage and detailed description for Delta Live Tables migration
Adds documentation for #2065
=> Added documentation to use Delta Live Tables migration

src/databricks/labs/ucx/source_code/folders.py, tests/unit/source_code/linters/test_files.py, tests/unit/source_code/test_folders.py, tests/unit/source_code/test_graph.py
Document and test `Folder` and `FolderLoader`
Progresses #3645
=> [TECH DEBT] Document and test `Folder` and `FolderLoader`

tests/integration/source_code/solacc.py
Print the Solacc advices so that we see the advices per solution accelerator to find interesting ones for demoing.
=> Print the Solacc advices

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature.yml
Use new type field in issue templates
=> Use new type field in issue templates

docs/ucx/docs/process/index.mdx, docs/ucx/docs/reference/commands/index.mdx, docs/ucx/docs/reference/workflows/index.mdx
Fixed broken anchors in documentation
=> Fixed broken anchors in documentation

src/databricks/labs/ucx/hive_metastore/federation.py, tests/unit/hive_metastore/test_federation.py
=> Added support for MSSQL and POSTGRESQL to HMS Federation

src/databricks/labs/ucx/queries/assessment/interactive/01_0_compute_access_mode_limitation_summary.sql, src/databricks/labs/ucx/queries/assessment/main/00_0__assessment_overview.md, src/databricks/labs/ucx/queries/assessment/main/05_0__findings_summary.md, src/databricks/labs/ucx/queries/assessment/main/10_0__data_summary.md, src/databricks/labs/ucx/queries/assessment/main/15_0__storage_summary.md, src/databricks/labs/ucx/queries/assessment/main/20_0__compute_summary.md, src/databricks/labs/ucx/queries/assessment/main/30_0_job_summary.md, src/databricks/labs/ucx/queries/assessment/main/40_0__last_summary.md, src/databricks/labs/ucx/queries/migration/groups/00_0_migration_overview.md, src/databricks/labs/ucx/queries/migration/main/00_0_migration_overview.md
Fixed the broken documentation links in dashboards
Resolves #3725
=> Fixed the broken documentation links in dashboards

tests/integration/hive_metastore/test_grant_detail.py
Add retry mechanism to wait for the grants to exists before crawling
Resolves #3758
=> Add retry mechanism to wait for the grants to exists before crawling

src/databricks/labs/ucx/cli.py, tests/unit/test_cli.py
=> [Tech Debt] standardising the error message for required parameter in cli command

tests/unit/install/test_install.py
=> [Tech Debt] removing notfound if not required in test_install.py 

src/databricks/labs/ucx/source_code/jobs.py, tests/integration/source_code/test_jobs.py, tests/unit/source_code/test_jobs.py
Added error handling while fetching pipelines in workflow linting.
Resolves #3815
=> Added error handling and tests for Workflow linter during pipeline fetch

src/databricks/labs/ucx/queries/assessment/main/20_0_clusters.sql
Add links to compute summary widgets
Resolves #3260
=> Add links to compute summary widget

docs/ucx/docs/installation/index.mdx
=> Adds option to install UCX in offline mode

src/databricks/labs/ucx/hive_metastore/locations.py
=> [TECHDEBT] Remove unused code for _resolve_dbfs_root in MountCrawler

src/databricks/labs/ucx/installer/workflows.py
=> Fix Assessment Excel Exporter

tests/integration/framework/test_owners.py
Fix the notebook ownership test
Resolves #4033
=> Add a fix for notebook ownership integration test

src/databricks/labs/ucx/install.py, tests/unit/install/test_install_dashboards.py
Quick PR to fix some nits that were missed from PR from https://github.com/databrickslabs/ucx/pull/4209
=> Fix some nits missed from the PR comments

docs/ucx/yarn.lock
This PR freshens the transitive dependencies that are used by Docusaurus, and should resolve the security issues currently reported against this repository.
- manually tested
=> Freshen documentation (docusaurus) dependencies

tests/integration/workspace_access/test_generic.py
Skipping test related to a feature that is disabled in the workspace
Skips failure in #4324 #4325
=> Skip tests related to Workspace Feature Store since it is disabled in the workspace

SECURITY.md
Add SECURITY.md for vulnerability reporting policy with details about reporting and the email to reach out to.
Resolves #4230
=> Add SECURITY.md for vulnerability reporting policy

src/databricks/labs/ucx/hive_metastore/federation.py
Fixed "create federated catalog" to scan all external locations and add their paths to the allowed paths for the federated catalog.
=> Fixed create federated catalog to add all external locations to the allowed paths.
