- src/databricks/labs/ucx/framework/tasks.py
- src/databricks/labs/ucx/hive_metastore/tables.scala
- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/runtime.py
This PR allows fetching table metadata without the need to access storage, allowing for a more straightforward configuration that no longer requires Azure storage credentials to be present in the cluster config. This notebook allows for a faster scanning performance.
Fixes #205
Co-authored by: Lars George <lars.george@databricks.com>
> Create `$inventory.tables` from Scala notebook

- src/databricks/labs/ucx/install.py
- tests/unit/test_install.py
Also fixes stripping whitespaces around groups when enters like `g1, g2, g3` etc. Previously the code expected to get no whitespaces.
Fixes #216
> Allow empty group filter in install.py (#216)

- src/databricks/labs/ucx/framework/crawlers.py
- tests/unit/framework/test_crawlers.py
By default, we execute inserts with the batch size of 1000 records. Tunable by `max_records_per_batch`
Fixes #226
> Add batched iteration for `INSERT INTO` queries in `StatementExecutionBackend` with default `max_records_per_batch=1000`

- src/databricks/labs/ucx/hive_metastore/tables.scala
> Handle errors better in tables.scala (#243)

- src/databricks/labs/ucx/runtime.py
Tune up the documentation - 5
documentation updated for new functions / methods
> Improve `README` notebook documentaiton

- src/databricks/labs/ucx/install.py
Fixes #250 
Since the packages were refactored, the debug notebook yields this: 
```
cannot import name 'logger' from 'databricks.labs.ucx' (/local_disk0/.ephemeral_nfs/envs/pythonEnv-ce5bf3ef-5751-49fc-a077-d25850790a9b/lib/python3.10/site-packages/databricks/labs/ucx/__init__.py)
```
> Fix debug notebook code with refactored package structure (#250)

- README.md
Adding introduction to set expectations on what this tooling does.
> Added comprehensive introduction user manual

- src/databricks/labs/ucx/install.py
msg - Installation completed successfully! Please refer to the README.py notebook for next steps.
> Improved installation finish messages within installer script

- src/databricks/labs/ucx/assessment/queries/all_tables.sql
- src/databricks/labs/ucx/assessment/queries/clusters.sql
- src/databricks/labs/ucx/assessment/queries/count_total_databases.sql
- src/databricks/labs/ucx/assessment/queries/count_total_tables.sql
- src/databricks/labs/ucx/assessment/queries/database_summary.sql
- src/databricks/labs/ucx/assessment/queries/external_locations.sql
- src/databricks/labs/ucx/assessment/queries/jobs.sql
- src/databricks/labs/ucx/assessment/queries/mount_points.sql
- src/databricks/labs/ucx/assessment/queries/total_tables.sql
- src/databricks/labs/ucx/assessment/queries/workspace_access_total_groups.sql
- src/databricks/labs/ucx/framework/dashboards.py
- tests/integration/framework/test_dashboards.py
> Update existing and add new SQL queries to the assessment step dashboard

- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/workspace_access/groups.py
- tests/integration/workspace_access/test_groups.py
> Use all account-level groups with matching names to workspace-level groups in case no explicit configuration

- notebooks/toolkit.py
- src/databricks/labs/ucx/account/workspaces.py
- src/databricks/labs/ucx/config.py
- src/databricks/labs/ucx/framework/tasks.py
- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/runtime.py
- src/databricks/labs/ucx/workspace_access/migration.py
- tests/integration/hive_metastore/test_mounts.py
- tests/integration/test_installation.py
- tests/integration/workspace_access/test_workspace_access.py
- tests/unit/account/test_workspaces.py
- tests/unit/test_config.py
- tests/unit/test_install.py
This PR renames `MigrationConfig` to `WorkspaceConfig` and adds `AccountConfig`, which persists configuration file at `~/.ucx/config.yml` - same homefolder, but this time on the local machine, instead of the workspace FS.
> Add support for account-level configuration and multi-cloud workspace list

- src/databricks/labs/ucx/framework/tasks.py
- src/databricks/labs/ucx/install.py
- tests/unit/test_install.py
> Keep order of tasks in the README notebook

- src/databricks/labs/ucx/assessment/crawlers.py
- tests/unit/assessment/test_assessment.py
> Added filtering out for job clusters in  clusters crawler

- src/databricks/labs/ucx/assessment/crawlers.py
- tests/integration/hive_metastore/test_tables.py
- tests/unit/assessment/test_assessment.py
> Added crawler for Azure Service principals used for direct storage access

- src/databricks/labs/ucx/assessment/crawlers.py
- tests/unit/assessment/test_assessment.py
> Fixed handling of missing but linked cluster policies.

- src/databricks/labs/ucx/runtime.py
- src/databricks/labs/ucx/workspace_access/groups.py
- src/databricks/labs/ucx/workspace_access/migration.py
- tests/unit/workspace_access/test_groups.py
> Skip group migration when no groups are available after preparation step.

- docs/table_upgrade.md
Added a table migration doc.
Let's discuss the migration process.
> Define table migration process

- src/databricks/labs/ucx/framework/crawlers.py
- tests/unit/framework/test_crawlers.py
This PR aims to fix https://github.com/databrickslabs/ucx/issues/297 and https://github.com/databrickslabs/ucx/issues/346
It adds a utility method to filter rows that have a column containing None, this will help Crawlers to not throw an error when a column is None.
it also checks if the column in the class is Nullable or not, if it's nullable and the value is None, it's ignored
> Fixed appending to tables by adding filtering of `None` rows

- src/databricks/labs/ucx/framework/dashboards.py
> Ignore errors for Redash widgets and queries redeployment during installation

- src/databricks/labs/ucx/install.py
- tests/unit/test_install.py
add test for `_configure_inventory_database()`
add test for `run_for_config()`
> Improved test coverage for installer

- src/databricks/labs/ucx/assessment/crawlers.py
- src/databricks/labs/ucx/framework/crawlers.py
- src/databricks/labs/ucx/hive_metastore/data_objects.py
- src/databricks/labs/ucx/hive_metastore/grants.py
- src/databricks/labs/ucx/hive_metastore/mounts.py
- src/databricks/labs/ucx/hive_metastore/tables.py
- src/databricks/labs/ucx/workspace_access/manager.py
- tests/unit/framework/mocks.py
- tests/unit/framework/test_crawlers.py
- tests/unit/hive_metastore/test_mounts.py
> Ensure that table exists, even when crawlers produce zero records

- src/databricks/labs/ucx/mixins/fixtures.py
- tests/integration/conftest.py
- tests/integration/framework/test_dashboards.py
- tests/integration/framework/test_fixtures.py
- tests/integration/hive_metastore/test_external_locations.py
- tests/integration/hive_metastore/test_grants.py
- tests/integration/hive_metastore/test_migrate.py
- tests/integration/hive_metastore/test_tables.py
- tests/integration/test_installation.py
- tests/integration/workspace_access/test_permissions_manager.py
- tests/integration/workspace_access/test_workspace_access.py
Make this testing framework behave the same way as in Java SDK - https://github.com/databricks/databricks-sdk-java/blob/main/databricks-sdk-java/src/test/java/com/databricks/sdk/integration/framework/EnvTest.java
> Introduce deterministic `env_or_skip` fixture for integration tests

- src/databricks/labs/ucx/__about__.py
- src/databricks/labs/ucx/install.py
Any installations that are done from unreleased versions will get a different format. For example, the latest released version is `0.24.0` and there were 15 commits to `main` branch since the last release. `./install.sh` will tell about `Installing v0.24.1+1520231006230102`.
> Detect installations of unreleased versions

- src/databricks/labs/ucx/framework/parallel.py
- src/databricks/labs/ucx/hive_metastore/grants.py
- src/databricks/labs/ucx/hive_metastore/tables.py
- src/databricks/labs/ucx/workspace_access/generic.py
- src/databricks/labs/ucx/workspace_access/groups.py
- src/databricks/labs/ucx/workspace_access/manager.py
- src/databricks/labs/ucx/workspace_access/redash.py
- src/databricks/labs/ucx/workspace_access/scim.py
- src/databricks/labs/ucx/workspace_access/secrets.py
- tests/integration/workspace_access/test_setup.py
- tests/unit/framework/test_parallel.py
- explicitly propagate thread pool errors to calling code in GoLang style
- fixed bug with data race related to progress reporter on task completions
- removed `ProgressReporter` class, which was confined only to this module anyway
- added total time reporting for all parallel tasks
- added different levels of error reporting depending on percentage of failed tasks
- ensured that collected results are always non-None
- ensured that all existing parallel code returns some value as a result. `true` is better than `void`.
Fixes #402
> Fixed broken logic in `parallel` module and applied hardened error handling design for parallel code

- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/runtime.py
- tests/unit/test_install.py
Markdown handles multiple whitespaces well anyways, and leaving in the indentation allows for formatting list etc.
Fixes #253
> Remove whitespace stripping.

- README.md
- src/databricks/labs/ucx/hive_metastore/grants.py
- src/databricks/labs/ucx/runtime.py
- src/databricks/labs/ucx/workspace_access/base.py
- src/databricks/labs/ucx/workspace_access/groups.py
- src/databricks/labs/ucx/workspace_access/manager.py
- src/databricks/labs/ucx/workspace_access/migration.py
- src/databricks/labs/ucx/workspace_access/tacl.py
- tests/integration/test_installation.py
- tests/integration/workspace_access/test_tacl.py
- tests/integration/workspace_access/test_workspace_access.py
- tests/unit/hive_metastore/test_grants.py
- tests/unit/workspace_access/test_tacl.py
When workspace-local group is replaced with account-level group, Legacy Table ACLs disappear from Hive Metastore objects. This PR plugs HMS grants with `crawler`/`applier` framework on top of `$inventory.permissions`
> Added support for migrating Legacy Table ACLs from workspace-local to account-level groups

- src/databricks/labs/ucx/workspace_access/groups.py
- tests/integration/conftest.py
- tests/integration/workspace_access/test_groups.py
This fix helps to recover from a state, where 
- the temporary groups were created, 
- the account groups were not,
- the original workspace-local groups were deleted.
The fix **recreates the original state**, with _recreating all the workspace-local groups, which does have a temp pair but not an account level pair attached to the workspace_.
This helps to recreate the state of the migration with the already existing group_manager.migration_groups_provider
> disaster recovery from temp state

- docs/local-group-migration.md
- src/databricks/labs/ucx/workspace_access/groups.py
- tests/integration/conftest.py
- tests/integration/workspace_access/test_groups.py
This fix helps to recover from a state where
- the temporary groups were created,
- the account groups were not,
- the original workspace-local groups were deleted.
- The fix recreates the original state, with recreating all the workspace-local groups, which does have a temp pair but not an account level pair attached to the workspace.
This helps to recreate the state of the migration with the already existing group_manager.migration_groups_provider
> Added recovery mode for workspace-local groups from temporary groups

- src/databricks/labs/ucx/workspace_access/groups.py
- tests/integration/workspace_access/test_groups.py
Removing recovering local groups if the corresponding account group is already attached to the workspace.
> Added check if account group already exists during failure recovery

- CONTRIBUTING.md
- src/databricks/labs/ucx/config.py
The crawl_permissions task in assessment would not respect the config value of workspace_start_path as it was not present in the 'from_dict' classmethod. Added an extraction for the config.
Removed dbconnect from Contributing README as it is no longer needed.
> Fixed `crawl_permissions` task to respect 'workspace_start_path' config

- CHANGELOG.md
- src/databricks/labs/ucx/__about__.py
- src/databricks/labs/ucx/config.py
* Added exception handling for secret scope not found. ([#418](https://github.com/databricks/ucx/pull/418)).
* Added a crawler for creating an inventory of Azure Service Principals ([#326](https://github.com/databricks/ucx/pull/326)).
* Added check if account group already exists during failure recovery ([#446](https://github.com/databricks/ucx/pull/446)).
* Added checking for index out of range. ([#429](https://github.com/databricks/ucx/pull/429)).
* Added hyperlink to UCX releases in the main readme ([#408](https://github.com/databricks/ucx/pull/408)).
* Added integration test to check backup groups get deleted ([#387](https://github.com/databricks/ucx/pull/387)).
* Added logging of errors during threadpool operations. ([#376](https://github.com/databricks/ucx/pull/376)).
* Added …
> Release v0.4.0

- CONTRIBUTING.md
- Makefile
… easier on-boarding experience
The problem was `make test` was reporting incompatible versions. The `hatch` environment needed cleaning up. Also added `make install-dev` as a convention to install the developer environment (hatch).
> Added `make install-dev` and a stronger `make clean` for easier dev on-boarding and release upgrades.

- CHANGELOG.md
- src/databricks/labs/ucx/__about__.py
* Added `make install-dev` and a stronger `make clean` for easier dev on-boarding and release upgrades ([#458](https://github.com/databricks/ucx/pull/458)).
* Added failure summary in the assessment dashboard ([#455](https://github.com/databricks/ucx/pull/455)).
* Added test for checking grants in default schema ([#470](https://github.com/databricks/ucx/pull/470)).
* Added unit tests for generic permissions ([#457](https://github.com/databricks/ucx/pull/457)).
* Enabled integration tests via OIDC for every pull request ([#378](https://github.com/databricks/ucx/pull/378)).
* Added check if permissions are up to date ([#421](https://github.com/databricks/ucx/pull/421)).
* Fixed casing in `all_tables.sql` query. ([#464](https://github.com/databricks/ucx/pull/464)).
* Fixed missed scans for …
> Release v0.5.0

- src/databricks/labs/ucx/workspace_access/generic.py
- tests/unit/workspace_access/test_generic.py
When running the assessment job, the tasks workspace listing, fails with the error "KeyError: 'object_type'"
the object_type property is not set for experiment objects and while listing it throws this error. Since scope of workspace listing is limited to Notebooks, Directories, Repos, Files, Libraries, suggesting a code change will will filter out cases where object_type is None.
> Fixed issue with workspace listing process on None type object_type

- src/databricks/labs/ucx/workspace_access/manager.py
- tests/unit/workspace_access/test_manager.py
If the apply permission task is run before the assessment task, it crashes. This PR checks if the permissions table (which is required for the apply group permission) is present if not raise a Databricks error exception
> Running apply permission task before assessment should display message

- .github/workflows/acceptance.yml
- .github/workflows/push.yml
There were many cases when GitHub bot was removing PR from the merge queue, possibly because of integration tests being flaky. This PR removes the chance of this flakiness by partitioning the integration tests into its own workflow file.
> Split integration tests from blocking the merge queue

- src/databricks/labs/ucx/framework/parallel.py
- src/databricks/labs/ucx/workspace_access/manager.py
Applying grants that belong to the same principle, object id, and object type concurrently is not supported in legacy Table ACLs currently:
> TableAcl grant/revoke operations are not atomic. When granting the permissions, the service would first get all existing permissions, append with the new permissions, and set the full list in the database. If there are concurrent grant requests, both requests might succeed and emit the audit logs, but what actually happens could be that the new permission list from one request overrides the other one, causing permission loss.
This PR will:
* Resolve issue https://github.com/databrickslabs/ucx/issues/499.
> Mitigate permissions loss in Table ACLs by running appliers with single thread

- pyproject.toml
- src/databricks/labs/ucx/mixins/fixtures.py
- src/databricks/labs/ucx/workspace_access/manager.py
- src/databricks/labs/ucx/workspace_access/tacl.py
- tests/integration/test_installation.py
- tests/integration/workspace_access/test_groups.py
- tests/integration/workspace_access/test_tacl.py
- tests/unit/workspace_access/test_tacl.py
Applying grants that belong to the same principle, object id, and object type concurrently is not supported in legacy Table ACLs currently:
> TableAcl grant/revoke operations are not atomic. When granting the permissions, the service would first get all existing permissions, append with the new permissions, and set the full list in the database. If there are concurrent grant requests, both requests might succeed and emit the audit logs, but what actually happens could be that the new permission list from one request overrides the other one, causing permission loss.
This PR will:
* Resolve issue [499](https://github.com/databrickslabs/ucx/issues/499). 
* Improve performance of migrating Table ACLs permissions
* Added tests covering objects ownership
* Increased test coverage around Table …
> Breaking change: Mitigate permissions loss in Table ACLs by folding grants belonging to the same principal, object id and object type together

- src/databricks/labs/ucx/config.py
- src/databricks/labs/ucx/install.py
- tests/integration/test_installation.py
- tests/unit/test_config.py
- tests/unit/test_install.py
> Added support for external Hive Metastores including AWS Glue

- docs/external_hms.md
Per our discussion.
Analysis of External HMS integration.
> Added documentation to describe interaction with external Hive Metastores

- src/databricks/labs/ucx/install.py
Added uniqueness in the new warehouse name to avoid name conflict
Fixes #432
> Added uniqueness in the new warehouse name to avoid name conflict

- src/databricks/labs/ucx/workspace_access/scim.py
Iterator from `self._get_groups()` consumed in the first list comprehension, leaving nothing for the second pass.
Closes #540
> Fixed missing group entitlement migration bug

- tests/integration/test_installation.py
> Make `test_jobs_with_no_inventory_database` resilient to concurrent object deletes

- src/databricks/labs/ucx/config.py
- src/databricks/labs/ucx/install.py
- tests/unit/test_install.py
> Fixing installer not being able to migrate from V1 to V2

- CHANGELOG.md
- src/databricks/labs/ucx/__about__.py
- src/databricks/labs/ucx/install.py
**Breaking changes** (existing installations need to reinstall UCX and re-run assessment jobs)
* Switched local group migration component to rename groups instead of creating backup groups ([#450](https://github.com/databricks/ucx/pull/450)).
* Mitigate permissions loss in Table ACLs by folding grants belonging to the same principal, object id and object type together ([#512](https://github.com/databricks/ucx/pull/512)).
**New features**
* Added support for the experimental Databricks CLI launcher ([#517](https://github.com/databricks/ucx/pull/517)).
* Added support for external Hive Metastores including AWS Glue ([#400](https://github.com/databricks/ucx/pull/400)).
* Added more views to assessment dashboard ([#474](https://github.com/databricks/ucx/pull/474)).
* Added rate limit for …
> Release v0.6.0

- src/databricks/labs/ucx/install.py
May fix #599. Installer going down path of checking git, and splitting a variable that wasn't tested for 'None`. Added guard, which fixed 3 broken unit tests.
> Fixed install check for git pre-release versions

- Makefile
I have `hatch` already installed via homebrew, and don't want install an additional copy of it.
> Check if the `hatch` is already installed, and install only if it isn't installed yet

- CHANGELOG.md
- src/databricks/labs/ucx/__about__.py
* Added a logo for UCX ([#605](https://github.com/databricks/ucx/pull/605)).
* Check if the `hatch` is already installed, and install only if it isn't installed yet ([#603](https://github.com/databricks/ucx/pull/603)).
* Fixed installation check for git pre-release versions ([#600](https://github.com/databricks/ucx/pull/600)).
* Temporarily remove SQL warehouse requirement from `labs.yml` ([#604](https://github.com/databricks/ucx/pull/604)).
> Release v0.6.1

- src/databricks/labs/ucx/install.py
This PR skips jobs that are still in the `~/.ucx/state.json`, but don't exist in the workspace.
> Fixed `databricks labs ucx workflows` command

- src/databricks/labs/ucx/assessment/crawlers.py
- tests/unit/assessment/test_assessment.py
May fix https://github.com/databrickslabs/ucx/issues/601 
Test for `custom`, `dlt` and add exception handling around casting to int.
Add unit tests based on observation of internal workspaces.
> Fixed `crawl_cluster` failure over custom runtimes

- CONTRIBUTING.md
- src/databricks/labs/ucx/install.py
- tests/integration/conftest.py
- tests/integration/test_conftest.py
- tests/integration/test_installation.py
- tests/integration/workspace_access/test_groups.py
Found test fixture generating 7+ local integration test failures. Adding to test in isolation.
> Fixed problematic integration test fixture make_ucx_group

- src/databricks/labs/ucx/hive_metastore/grants.py
- src/databricks/labs/ucx/workspace_access/groups.py
- tests/integration/workspace_access/test_groups.py
- tests/integration/workspace_access/test_tacl.py
- tests/unit/hive_metastore/test_grants.py
This PR fixes the bug, where ownership transfer permissions were not applied on the database level, resulting in cryptic exceptions like
```
ALTER hive_metastore.ucx_sjvoa OWNER TO `ucx_O000`
...
[TABLE_OR_VIEW_NOT_FOUND] The table or view `spark_catalog`.`hive_metastore`.`ucx_sjvoa` cannot be found. Verify the spelling and correctness of the schema and catalog.
If you did not qualify the name with a schema, verify the current_schema() output, or qualify the name with the correct schema and catalog.
To tolerate the error on drop use DROP VIEW IF EXISTS or DROP TABLE IF EXISTS.;
```
Fix #616
> Reduce runtime of `test_set_owner_permission` from 15 minutes to 44 seconds

- src/databricks/labs/ucx/framework/logger.py
- src/databricks/labs/ucx/framework/parallel.py
- src/databricks/labs/ucx/mixins/fixtures.py
- src/databricks/labs/ucx/workspace_access/manager.py
- tests/integration/conftest.py
- tests/integration/hive_metastore/test_grants.py
- tests/integration/test_installation.py
- tests/integration/workspace_access/test_groups.py
- tests/integration/workspace_access/test_tacl.py
Reduces removes 20 second of runtime on average from the integration tests involving `TablesCrawler`.
Fix #617
> Introduce `StaticTablesCrawler` for integration tests

- src/databricks/labs/ucx/hive_metastore/data_objects.py
- src/databricks/labs/ucx/hive_metastore/tables.py
- src/databricks/labs/ucx/hive_metastore/tables.scala
- tests/integration/hive_metastore/test_external_locations.py
- tests/unit/assessment/test_assessment.py
The UCX tool fetches the 'location' from the table properties while for an external location with jdbc, the host information is stored in 'storage properties'.
Add a field for Table class and fetch Storage Properties from the table. Using the host field from Storage properties, create the full jdbc url
Older PR closed due to Git issues: https://github.com/databrickslabs/ucx/pull/582
> Fixed External Location widget to return hostname for `jdbc:` locations

- CHANGELOG.md
- src/databricks/labs/ucx/__about__.py
- tests/integration/test_installation.py
* Added current version of UCX to task logs ([#566](https://github.com/databrickslabs/ucx/pull/566)).
* Fixed `'str' object has no attribute 'value'` failure on apply backup group permissions task ([#574](https://github.com/databrickslabs/ucx/pull/574)).
* Fixed `crawl_cluster` failure over custom runtimes ([#602](https://github.com/databrickslabs/ucx/pull/602)).
* Fixed `databricks labs ucx workflows` command ([#608](https://github.com/databrickslabs/ucx/pull/608)).
* Fixed problematic integration test fixture `make_ucx_group` ([#613](https://github.com/databrickslabs/ucx/pull/613)).
* Fixed internal API request retry logic by relying on concrete exception types ([#637](https://github.com/databrickslabs/ucx/pull/637)).
* Fixed `tables.scala` notebook to read inventory database from …
> Release v0.6.2

- src/databricks/labs/ucx/workspace_access/secrets.py
- tests/integration/workspace_access/test_secrets.py
- tests/unit/workspace_access/test_secrets.py
Unfortunately, both the `list_acls` and `get_acl` methods seem to be very inconsistent for checking whether a permission is applied to a given secret scope. For this reason, this PR introduces a workaround where if the permissions don't match, the acl is being applied again. From my experience of trying multiple workarounds, this was the only one that proved to be consistent.
**Fixes #627** 
- Added extra safety checks for inflight permission check logic in secrets.py
- Added integration tests in test_secrets.py
Introduced integration tests for secrets which were missing before.
> Fix for secret scope apply task always raises ValueError

- labs.yml
- src/databricks/labs/ucx/account/workspaces.py
- src/databricks/labs/ucx/cli.py
- tests/unit/account/test_workspaces.py
The account admin can upload workspace info at account level into all the UCX installations under each workspace for the account.
Removed some code no longer required during pair programming with @nfx 
Unit tests to follow.
> New CLI command for workspace mapping

- src/databricks/labs/ucx/workspace_access/generic.py
- src/databricks/labs/ucx/workspace_access/manager.py
- tests/unit/workspace_access/test_generic.py
**Change description:**
This PR makes changes to the model listing process. Currently the model listing is done serially which takes time in workspace with large number of registered models. This changes uses python threads to parallelize model listing to speed up the inventory process for models
**Changes details:**
Updates to generic.py.model_listing() to use Threads.gather to parallelize get_model function
It accepts num_threads from config.
Also updated the relevant test cases
> Added parallel fetching of registered model identifiers to speed-up assessment workflow

- labs.yml
- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/install.py
- tests/unit/installer/test_installation_manager.py
- tests/unit/test_cli.py
Closes #674 
Description:
This change adds a CLI command that performs the following logic.
1.  Check whether UCX is installed for the current user on the workspace
2. Check whether the Assessment workflow was successfully run or is still running
3. Wait for a current run to complete or start a new run and wait for it to complete.
> Added `databricks labs ucx ensure-assessment-run` to CLI commands.

- pyproject.toml
- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/framework/parallel.py
- src/databricks/labs/ucx/hive_metastore/grants.py
- src/databricks/labs/ucx/hive_metastore/locations.py
- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/workspace_access/groups.py
- src/databricks/labs/ucx/workspace_access/scim.py
- src/databricks/labs/ucx/workspace_access/tacl.py
- tests/integration/assessment/test_azure.py
- tests/integration/conftest.py
- tests/integration/hive_metastore/test_external_locations.py
- tests/integration/hive_metastore/test_migrate.py
- tests/integration/test_installation.py
- tests/integration/workspace_access/__init__.py
- tests/integration/workspace_access/test_groups.py
- tests/integration/workspace_access/test_tacl.py
- tests/unit/assessment/test_dashboard.py
- tests/unit/hive_metastore/test_grants.py
- tests/unit/test_cli.py
- tests/unit/test_install.py
- tests/unit/workspace_access/test_tacl.py
> Fixed legacy table ACL ownership migration and other integration testing issues

- CHANGELOG.md
- src/databricks/labs/ucx/__about__.py
* Added `databricks labs ucx create-table-mapping` and `databricks labs ucx manual-workspace-info` commands for CLI ([#682](https://github.com/databrickslabs/ucx/pull/682)).
* Added `databricks labs ucx ensure-assessment-run` to CLI commands ([#708](https://github.com/databrickslabs/ucx/pull/708)).
* Added `databricks labs ucx installations` command ([#679](https://github.com/databrickslabs/ucx/pull/679)).
* Added `databricks labs ucx skip --schema ... --table ...` command to mark table/schema for skipping in the table migration process ([#680](https://github.com/databrickslabs/ucx/pull/680)).
* Added `databricks labs ucx validate-external-locations` command for cli ([#715](https://github.com/databrickslabs/ucx/pull/715)).
* Added capturing `ANY FILE` and `ANONYMOUS FUNCTION` grants …
> Release v0.7.0

- src/databricks/labs/ucx/queries/assessment/main/01_1_failure_summary.sql
Failure Summary was mis-leading, where as "Assessment Summary" for the panel of found objects and assessment (e.g. DBR version) is more appropriate.
> Rename summary panel from Failure Summary to Assessment Summary

- tests/integration/test_installation.py
Change Description:
The test_running_real_assessment_job test is timing out of 5 mins due to large number of workspace listing.
This change is to pass a custom workspace_start_path of the current user folder to speed up the execution
> Increased speed of integration tests by scanning smaller number of folders

- src/databricks/labs/ucx/framework/dashboards.py
- src/databricks/labs/ucx/install.py
Fixes #730:
* Fixed installation issue when upgrading from an older version
* Improved logging messages
> Fix installation issue when upgrading from an older version of the tool and improve logs

- labs.yml
- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/install.py
- tests/integration/test_installation.py
- tests/unit/test_cli.py
- tests/unit/test_install.py
> Added `databricks labs ucx repair-run --step ...` CLI command for repair run of any failed workflows, like `assessment`, `migrate-groups` etc.

- CHANGELOG.md
- src/databricks/labs/ucx/__about__.py
* Added `databricks labs ucx repair-run --step ...` CLI command for repair run of any failed workflows, like `assessment`, `migrate-groups` etc. ([#724](https://github.com/databrickslabs/ucx/pull/724)).
* Added `databricks labs ucx revert-migrated-table` command ([#729](https://github.com/databrickslabs/ucx/pull/729)).
* Allow specifying a group list when group match options are used ([#725](https://github.com/databrickslabs/ucx/pull/725)).
* Fixed installation issue when upgrading from an older version of the tool and improve logs ([#740](https://github.com/databrickslabs/ucx/pull/740)).
* Renamed summary panel from Failure Summary to Assessment Summary ([#733](https://github.com/databrickslabs/ucx/pull/733)).
* Retry internal error when getting permissions and update legacy table ACL …
> Release v0.8.0

- src/databricks/labs/ucx/install.py
- tests/integration/test_installation.py
- tests/unit/test_install.py
This PR adds heuristics to determine the actual remote error type based on message content. This improves integration test flakiness for those that call `run_workflow`.
> Improve error message inference from failed workflow runs

- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/hive_metastore/mapping.py
- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- src/databricks/labs/ucx/hive_metastore/tables.py
- tests/integration/conftest.py
- tests/integration/hive_metastore/test_migrate.py
- tests/unit/hive_metastore/test_mapping.py
- tests/unit/hive_metastore/test_table_migrate.py
closes #754 
Added functionality to the mapping module to compile a list of tables to migrate along with the rules/mappings.
We take into account the skip property and whether the table was migrated before.
> Added get_tables_to_migrate functionality in the mapping module

- src/databricks/labs/ucx/hive_metastore/mapping.py
- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- src/databricks/labs/ucx/hive_metastore/table_size.py
- src/databricks/labs/ucx/hive_metastore/tables.py
- tests/integration/hive_metastore/test_migrate.py
- tests/unit/hive_metastore/test_table_migrate.py
- tests/unit/hive_metastore/test_tables.py
closes #334 
Change migration functionality to base migration type on whether the table is on DBFS root or not.
- If the table location on a mount, sync the table to an external UC table
- If the table points to a databrick's dataset skip it
- If the table location is on a dbfs root location (dbfs location that is not a mount or a databricks dataset) deep clone the table to a managed UC table.
- Otherwise sync the table to an external UC table
> Added functionality to determine migration method based on DBFS Root

- src/databricks/labs/ucx/workspace_access/groups.py
- tests/unit/workspace_access/test_groups.py
- Fix isssue [761](https://github.com/databrickslabs/ucx/issues/761)
In rare cases, it can happen that a group is removed from the account before we manage to reflect it in the workspace. It's usually a couple of minutes between listing the groups and reflecting it. This PR will log such cases without failing the tool.
> Improve error handling by not failing group rename step if a group was removed from account before reflecting it to workspace

- src/databricks/labs/ucx/framework/crawlers.py
- tests/integration/framework/test_crawlers.py
- tests/unit/framework/test_crawlers.py
Convert the query execution exceptions to SDK exceptions like NotFound, PermissionDenied and SyntaxError (currently used BadRequest to map syntax errors).
Integration and unit tests added.
Fixes #726
> Convert to SDK exceptions for RuntimeBackend query executions

- CHANGELOG.md
- src/databricks/labs/ucx/__about__.py
* Added assessment step to estimate the size of DBFS root tables ([#741](https://github.com/databrickslabs/ucx/pull/741)).
* Added `TableMapping` functionality to table migrate ([#752](https://github.com/databrickslabs/ucx/pull/752)).
* Added `databricks labs ucx move` command to move tables and schemas between catalogs ([#756](https://github.com/databrickslabs/ucx/pull/756)).
* Added functionality to determine migration method based on DBFS Root ([#759](https://github.com/databrickslabs/ucx/pull/759)).
* Added `get_tables_to_migrate` functionality in the mapping module ([#755](https://github.com/databrickslabs/ucx/pull/755)).
* Added retry and rate limit to rename workspace group operation and corrected rate limit for reflecting account groups to workspace …
> Release v0.9.0

- src/databricks/labs/ucx/hive_metastore/locations.py
- tests/unit/hive_metastore/test_locations.py
This pull request includes changes to the `locations.py` file in the `databricks/labs/ucx/hive_metastore` directory and the addition of a new unit test in `test_locations.py`. The changes in `locations.py` involve modifying the `_deduplicate_mounts` method in the `Mounts` class. The method now checks if the name of the `Mount` object contains the word "volume", and if so, it standardizes the name to "/Volume". This is done to ensure that mounts with different casing for the word "volume" are treated as the same mount and not duplicated in the deduplicated list.
The new unit test in `test_locations.py` verifies that the `_deduplicate_mounts` method correctly deduplicates a list of `Mount` objects with different casing for the word "volume" in their names. The test creates a list of `Mount` …
> Mount Point crawler lists /Volume with four variations which is confusing

- pyproject.toml
- src/databricks/labs/ucx/framework/crawlers.py
- src/databricks/labs/ucx/hive_metastore/mapping.py
- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- src/databricks/labs/ucx/hive_metastore/table_size.py
- src/databricks/labs/ucx/mixins/sql.py
- tests/unit/framework/test_crawlers.py
- tests/unit/hive_metastore/test_table_size.py
Extend error handling of delta issues in crawlers and hive metastore by catching: `DELTA_TABLE_NOT_FOUND` and `DELTA_MISSING_TRANSACTION_LOG`
Resolves [#778](https://github.com/databrickslabs/ucx/issues/778)
> Extend error handling of delta issues in crawlers and hive metastore

- src/databricks/labs/ucx/assessment/azure.py
- src/databricks/labs/ucx/assessment/jobs.py
- src/databricks/labs/ucx/framework/tasks.py
- tests/integration/workspace_access/test_redash.py
- tests/unit/assessment/test_jobs.py
1. Changed writing of the readme log in a multiprocess safe way. Without this the assessment tasks are occasionally failing with error: `FileExistsError: [Errno 17] File exists: '/Workspace/Users/jni4fe@xxx.com/.ucx/logs/assessment/run-340934288146817/README.md'`
2. Skip long running integration test for Redash
3. Check if job settings and tasks are present while crawling
> Writing log readme in multiprocess safe way

- src/databricks/labs/ucx/install.py
Fixed listing of workflows via the CLI, listing all jobs with better details
Resolves #786
> Fixed listing of workflows via CLI

- src/databricks/labs/ucx/install.py
- tests/unit/test_install.py
Fixing the issue for repair run CLI `databricks labs ucx repair-run` . When a CLI  tries to repair run a job before if updates its response json to either FAILED or SUCCESS it was failing with NoneType exception.
Added a check in `repair_run` inside `install.py` to check the status of the response and wait for 20 seconds to get it updated .
Enhanced the code to repair run already repaired job.  
closes #787 
Resolves #787 
- modified the cli command `databricks labs ucx repair-run` which was failing in regression testing
- This has been manually tested
- added unit tests `test_repair_run_result_state` in `test_install.py`
- This was tested using integration test
- <img width="1394" alt="Screenshot 2024-01-17 at 11 08 42 AM" src="https://github.com/databrickslabs/ucx/assets/127273819/0f54b7 …
> Fixed `databricks labs ucx repair-run` command to execute correctly

- README.md
Remove install.sh references as install.sh is deprecated for non-dev type build-installs. 
May fix https://github.com/databrickslabs/ucx/issues/775
> Update README.md to remove mention of deprecated install.sh

- CHANGELOG.md
- src/databricks/labs/ucx/__about__.py
* Added `databricks labs ucx validate-groups-membership` command to validate groups to see if they have same membership across acount and workspace level ([#772](https://github.com/databrickslabs/ucx/pull/772)).
* Added baseline for getting Azure Resource Role Assignments ([#764](https://github.com/databrickslabs/ucx/pull/764)).
* Added issue and pull request templates ([#791](https://github.com/databrickslabs/ucx/pull/791)).
* Added linked issues to PR template ([#793](https://github.com/databrickslabs/ucx/pull/793)).
* Added optional `debug_truncate_bytes` parameter to the config and extend the default log truncation limit ([#782](https://github.com/databrickslabs/ucx/pull/782)).
* Added support for crawling grants and applying Hive Metastore UDF ACLs …
> Release v0.10.0

- labs.yml
- src/databricks/labs/ucx/assessment/aws.py
- src/databricks/labs/ucx/cli.py
- tests/integration/assessment/test_aws.py
- tests/unit/assessment/test_aws.py
- tests/unit/test_cli.py
CLI command to scan service principals and link to all the S3 buckets they have access to.
Genererates a CSV file.
The CSV File has the following format:
```
instance_profile_arn,resource_type,privilege,resource_path,iam_role_arn
arn:aws:iam::12345:instance-profile/role1,s3,READ_FILES,s3://bucket1,arn:aws:iam::12345:role/role1
arn:aws:iam::12345:instance-profile/role1,s3,READ_FILES,s3a://bucket1,arn:aws:iam::12345:role/role1
arn:aws:iam::12345:instance-profile/role1,s3,READ_FILES,s3://bucket2,arn:aws:iam::12345:role/role1
arn:aws:iam::12345:instance-profile/role1,s3,READ_FILES,s3a://bucket2,arn:aws:iam::12345:role/role1
```
The command relies on AWS CLI Command and require the user to setup and configure it.
Requires a working setup of AWS CLI.
[AWS CLI](https://aws.amazon.com/cli/)
The …
> Added `databricks labs ucx save-aws-iam-profiles` command to scan instance profiles identify S3 access and save a CSV with permissions

- labs.yml
- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- tests/integration/hive_metastore/test_table_move.py
- tests/unit/hive_metastore/test_table_move.py
- tests/unit/test_cli.py
> Added `databricks labs ucx alias` command to create a view of tables from one schema/catalog in another schema/catalog

- CHANGELOG.md
- src/databricks/labs/ucx/__about__.py
* Added `databricks labs ucx alias` command to create a view of tables from one schema/catalog in another schema/catalog ([#837](https://github.com/databrickslabs/ucx/pull/837)).
* Added `databricks labs ucx save-aws-iam-profiles` command to scan instance profiles identify AWS S3 access and save a CSV with permissions ([#817](https://github.com/databrickslabs/ucx/pull/817)).
* Added total view counts in the assessment dashboard ([#834](https://github.com/databrickslabs/ucx/pull/834)).
* Cleaned up `assess_jobs` and `assess_clusters` tasks in the `assessment` workflow to improve testing and reduce redundancy.([#825](https://github.com/databrickslabs/ucx/pull/825)).
* Added documentation for the assessment report ([#806](https://github.com/databrickslabs/ucx/pull/806)).
* Fixed escaping for …
> Release v0.11.0

- src/databricks/labs/ucx/install.py
- tests/unit/test_install.py
Fixing Installation Failure with actionable message
closes #835 
Resolves #835
> Improved installation failure with actionable message

- src/databricks/labs/ucx/framework/crawlers.py
- src/databricks/labs/ucx/runtime.py
- tests/unit/framework/mocks.py
- tests/unit/framework/test_crawlers.py
Looking through debug logs might sometimes be challenging due to the amount of information. This PR truncates SQL queries in debug logs by default.
> Debug logs to print only the first 96 bytes of the SQL query by default, tunable by `debug_truncate_bytes` SDK configuration property

- CHANGELOG.md
- src/databricks/labs/ucx/__about__.py
* Added "what" property for migration to scope down table migrations ([#856](https://github.com/databrickslabs/ucx/pull/856)).
* Added job count in the assessment dashboard ([#858](https://github.com/databrickslabs/ucx/pull/858)).
* Adopted `installation` package from `databricks-labs-blueprint` ([#860](https://github.com/databrickslabs/ucx/pull/860)).
* Debug logs to print only the first 96 bytes of SQL query by default, tunable by `debug_truncate_bytes` SDK configuration property ([#859](https://github.com/databrickslabs/ucx/pull/859)).
* Extract command codes and unify the checks for spark_conf, cluster_policy, init_scripts ([#855](https://github.com/databrickslabs/ucx/pull/855)).
* Improved installation failure with actionable message …
> Release v0.11.1

- labs.yml
- src/databricks/labs/ucx/assessment/aws.py
- src/databricks/labs/ucx/cli.py
- tests/integration/assessment/test_aws.py
- tests/unit/assessment/test_aws.py
- tests/unit/test_cli.py
CLI command to scan roles that are set with trust relationships with the UC master roles and the S3 buckets they have access to.
Genererates a CSV file.
The CSV File has the following format:
```
iam_role_arn,resource_type,privilege,resource_path
arn:aws:iam::12345:rolerole1,s3,READ_FILES,s3://bucket1
arn:aws:iam::12345:role/role1,s3,READ_FILES,s3a://bucket1
arn:aws:iam::12345:role/role1,s3,READ_FILES,s3://bucket2
arn:aws:iam::12345:role/role1,s3,READ_FILES,s3a://bucket2
```
The command relies on AWS CLI Command and require the user to setup and configure it.
Requires a working setup of AWS CLI.
[AWS CLI](https://aws.amazon.com/cli/)
The command saves a CSV to the UCX installation folder with the mapping.
The user has to be authenticated with AWS and the have the permissions to browse the …
> Added CLI Command `databricks labs ucx save-uc-compatible-roles`

- CHANGELOG.md
- src/databricks/labs/ucx/__about__.py
* Added CLI Command `databricks labs ucx save-uc-compatible-roles` ([#863](https://github.com/databrickslabs/ucx/pull/863)).
* Added dashboard widget with table count by storage and format ([#852](https://github.com/databrickslabs/ucx/pull/852)).
* Added verification of group permissions ([#841](https://github.com/databrickslabs/ucx/pull/841)).
* Checking pipeline cluster config and cluster policy in 'crawl_pipelines' task ([#864](https://github.com/databrickslabs/ucx/pull/864)).
* Created cluster policy (ucx-policy) to be used by all UCX compute. This may require customers to reinstall UCX. ([#853](https://github.com/databrickslabs/ucx/pull/853)).
* Skip scanning objects that were removed on platform side since the last scan time, so that integration tests are less flaky …
> Release v0.12.0

- src/databricks/labs/ucx/install.py
Fixed `WorkspaceConfig` initialization in generated` DEBUG.py` notebook to work with new package layout.
> Fixed WorkspaceConfig initialization for DEBUG notebook

- src/databricks/labs/ucx/install.py
- tests/unit/test_install.py
Added unit tests and minor code tweak as a result.
> Added tests for issue #786.

- .github/workflows/acceptance.yml
Some of the integration tests fail because of it and we don't need a subscription id anywhere
> Added `allow-no-subscriptions` to `azure/login` action

- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- src/databricks/labs/ucx/hive_metastore/tables.py
- tests/unit/hive_metastore/test_table_migrate.py
Changed the revert report to scan all table "What" types and report how many of these tables will be reverted.
closes #857 
Resolves #..
> Changed revert report to report on all "what" types rather than managed/external tables

- CHANGELOG.md
- src/databricks/labs/ucx/__about__.py
* Added CLI Command `databricks labs ucx principal-prefix-access` ([#949](https://github.com/databrickslabs/ucx/pull/949)).
* Added a widget with all jobs to track migration progress ([#940](https://github.com/databrickslabs/ucx/pull/940)).
* Added legacy cluster types to the assessment result ([#932](https://github.com/databrickslabs/ucx/pull/932)).
* Cleanup of install documentation ([#951](https://github.com/databrickslabs/ucx/pull/951), [#947](https://github.com/databrickslabs/ucx/pull/947)).
* Fixed `WorkspaceConfig` initialization for `DEBUG` notebook ([#934](https://github.com/databrickslabs/ucx/pull/934)).
* Fixed installer not opening config file during the installation ([#945](https://github.com/databrickslabs/ucx/pull/945)).
* Fixed groups in config file not considered for …
> Release v0.13.0

- src/databricks/labs/ucx/assessment/aws.py
- src/databricks/labs/ucx/cli.py
- tests/integration/assessment/test_aws.py
- tests/unit/assessment/test_aws.py
relates to  #862
closes #913 
Resolves #..
Added method to detect missing roles and add them to the AWS account.
https://github.com/databrickslabs/ucx/assets/10814065/1719f328-77b9-4636-8fea-d8b8825036f9
> Create storage credentials based on instance profiles and existing roles.

- src/databricks/labs/ucx/azure/access.py
AzureResourcePermissions.load should call Installation.load instead of Installation.save
Resolves #..
> Fixec AzureResourcePermissions.load to call Installation.load

- CHANGELOG.md
- src/databricks/labs/ucx/__about__.py
* Added secret detection logic to Azure service principal crawler ([#950](https://github.com/databrickslabs/ucx/pull/950)).
* Create storage credentials based on instance profiles and existing roles ([#869](https://github.com/databrickslabs/ucx/pull/869)).
* Enforced `protected-access` pylint rule ([#956](https://github.com/databrickslabs/ucx/pull/956)).
* Enforced `pylint` on unit and integration test code ([#953](https://github.com/databrickslabs/ucx/pull/953)).
* Enforcing `invalid-name` pylint rule ([#957](https://github.com/databrickslabs/ucx/pull/957)).
* Fixed AzureResourcePermissions.load to call Installation.load ([#962](https://github.com/databrickslabs/ucx/pull/962)).
* Fixed installer script to reuse an existing UCX Cluster policy if present …
> Release v0.13.1

- pyproject.toml
Removes warning from ruff when running `make fmt`
```
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'ignore' -> 'lint.ignore'
- 'flake8-tidy-imports' -> 'lint.flake8-tidy-imports'
- 'isort' -> 'lint.isort'
- 'per-file-ignores' -> 'lint.per-file-ignores'
```
> Fix ruff config for ruff==2.0

- CHANGELOG.md
- src/databricks/labs/ucx/__about__.py
* Fixed `AnalysisException` in `crawl_tables` task by ignoring the database that is not found ([#970](https://github.com/databrickslabs/ucx/pull/970)).
* Fixed `Unknown: org.apache.hadoop.hive.ql.metadata.HiveException: NoSuchObjectException` in `crawl_grants` task by ignoring the database that is not found ([#967](https://github.com/databrickslabs/ucx/pull/967)).
* Fixed ruff config for ruff==2.0 ([#969](https://github.com/databrickslabs/ucx/pull/969)).
* Made groups integration tests less flaky ([#965](https://github.com/databrickslabs/ucx/pull/965)).
> Release v0.13.2

- tests/integration/framework/test_crawlers.py
- tests/integration/test_installation.py
Fix 2 tests that are failing on aws
- `test_job_cluster_policy` checks for `azure_attributes`
- `test_runtime_backend_unknown_error_handled` picks up a UC cluster in aws infra
> Fix integration tests on AWS

- src/databricks/labs/ucx/runtime.py
The validation job should use Table ACL cluster otherwise it cannot validate the grants correctly.
> Update groups permissions validation to use Table ACL cluster

- src/databricks/labs/ucx/queries/assessment/main/03_0_database_summary.sql
- src/databricks/labs/ucx/queries/assessment/main/05_0_all_tables.sql
Aliases are usually not allowed in projections (as they are replaced later in the query execution phases). While the DBSQL was smart enough to handle the references via aliases, for some setups this results in an error. Changing column references to use actual names fixes this.
Resolves #980
> Renamed columns in assessment SQL queries to use actual names, not aliases

- src/databricks/labs/ucx/config.py
- tests/unit/test_config.py
Fixed `WorkspaceConfig.v1_migrate()` method to work with the Installation infrastructure.
Fixes #982
> Fixed `config.yml` upgrade from very old versions

- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- src/databricks/labs/ucx/hive_metastore/tables.py
- tests/integration/hive_metastore/test_migrate.py
- tests/unit/hive_metastore/test_table_migrate.py
Added table parameter `upgraded_from_ws` to migrated tables. The parameters contains the sources workspace id.
Resolves #899
> Added `upgraded_from_workspace_id` property to migrated tables to indicated the source workspace.

- src/databricks/labs/ucx/azure/access.py
- src/databricks/labs/ucx/azure/credentials.py
- src/databricks/labs/ucx/azure/resources.py
- tests/integration/azure/test_credentials.py
- tests/unit/azure/azure/mappings.json
- tests/unit/azure/test_access.py
- tests/unit/azure/test_credentials.py
- tests/unit/azure/test_resources.py
- tests/unit/test_cli.py
While creating StoragePermissionMapping, a principal could be managed identity which does not have directory_id. This PR will allow managed identity to be stored in StoragePermissionMapping, and allow None directory_id.
- Add `type` field to dataclass `StoragePermissionMapping` and `Principal` to indicate if a principal is service principal or managed identity.
- Allow None `directory_id` if the principal is not a service principal.
- Ignore the managed identity while migrating to UC storage credentials for now. 
fix #339
> Handle empty directory_id if managed identity encountered during the crawling of StoragePermissionMapping 

- labs.yml
- src/databricks/labs/ucx/workspace_access/groups.py
- tests/unit/workspace_access/test_groups.py
The `validate-groups-membership` command has been updated to include a comparison of group memberships at both the account and workspace levels, displaying the difference in members between the two levels in a new column. This enhancement allows for a more detailed analysis of group memberships, with the added functionality implemented in the `validate_group_membership` function in the `groups.py` file located in the `databricks/labs/ucx/workspace_access` directory. A new output field, "group\_members\_difference," has been added to represent the difference in the number of members between a workspace group and an associated account group. The corresponding unit test file, "test\_groups.py," has been updated to include a new test case that verifies the calculation of the …
> Added group members difference to the output of validate-groups-membership cli command

- src/databricks/labs/ucx/mixins/fixtures.py
- src/databricks/labs/ucx/workspace_access/generic.py
- src/databricks/labs/ucx/workspace_access/manager.py
- tests/integration/workspace_access/test_generic.py
- tests/unit/workspace_access/test_generic.py
- tests/unit/workspace_access/test_manager.py
This commit introduces permission migration support for feature tables and assigns root permissions for models and feature tables. A new fixture, `make_feature_table`, is introduced to handle the creation and deletion of feature tables via API calls. Updates to permission levels for feature tables allow for more granular control over permissions. Additionally, new functions for listing registered models and feature tables, as well as their root pages, have been added to the `manager.py` file. Three new tests have been introduced in the project's workspace access module to ensure the proper migration of permissions for feature tables and the root pages of feature tables and models. The `GenericPermissionsSupport` class in the `workspace_access` module has also been updated to include new …
> Added permission migration support for feature tables and the root permissions for models and feature tables 

- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/workspace_access/generic.py
- tests/integration/test_installation.py
- improved `_infer_error_from_job_run` and `_infer_error_from_task_run` to also catch `KeyError` and `ValueError`
- removed retries for `Unknown` errors for installation tests
> Improved installation integration test flakiness

- src/databricks/labs/ucx/account.py
- tests/unit/test_account.py
test_create_account_level_groups generally fails during the integration tests because the pattern that the code follows is not safe when there are multiple creation and deletion of groups in parallel.
The proposed changes assumes that all the groups.get() and groups.create() calls are not safe, thus they are surrounded by a try/except
> Reducing flakiness of create account groups

- src/databricks/labs/ucx/config.py
- src/databricks/labs/ucx/install.py
Added prompt is_terraform_used and updated the same in the config of WorkspaceInstaller
Resolves #393
> Prompt user if Terraform utilised for deploying infrastructure

- tests/unit/azure/test_credentials.py
Replace the plain encoded string by base64.b64encode to mitigate the gitguardian warning.
Resolves #..
> Fix gitguardian warning caused by "hello world" secret used in unit test

- src/databricks/labs/ucx/azure/credentials.py
- src/databricks/labs/ucx/azure/locations.py
- src/databricks/labs/ucx/azure/resources.py
- src/databricks/labs/ucx/hive_metastore/locations.py
- tests/integration/azure/test_locations.py
- tests/unit/azure/azure/mappings.json
- tests/unit/azure/test_locations.py
- tests/unit/azure/test_resources.py
- tests/unit/hive_metastore/test_locations.py
Create UC external locations for missing locations reported by `ExternalLocations` in `hive_metastore/locations.py`.
Partially resolve #100
> Create UC external locations in Azure based on migrated storage credentials

- README.md
- labs.yml
- src/databricks/labs/ucx/cli.py
- tests/unit/test_cli.py
Add cli command `migrate_locations` to create UC external location.
#100 
#1006
> Add `migrate-locations` command

- README.md
- labs.yml
> Fix document for `migrate-locations` command

- README.md
This PR improves documentation for the `move` command.
> Improved documentation for `databricks labs ucx move` command

- README.md
- labs.yml
- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/hive_metastore/catalog_schema.py
- tests/unit/hive_metastore/test_catalog_schema.py
- tests/unit/test_cli.py
Destination catalogs and schemas in UC is required to be created before table migration
This PR add a new command to compare existing UC catalogs and schemas with destination generated by table mapping, and create any missing destination catalogs and schemas.
Resolves #900 
Relates #670 #333
> Added 'create-catalogs-schemas' command to prepare destination catalogs and schemas before table migration

- tests/unit/test_cli.py
AWS test_migrate_locations_aws cli test is failing. This PR is to skip this so that CI test run fine.
> Skip failing `test_migrate_locations_aws`

- src/databricks/labs/ucx/framework/crawlers.py
This PR should stabilize integration tests a bit more. There are some slight hints that this may get queries done from integration tests unstuck:
> Use `max_records_per_batch=500` as default

- README.md
- pyproject.toml
- src/databricks/labs/ucx/install.py
- tests/integration/test_installation.py
- tests/unit/assessment/test_dashboard.py
- tests/unit/test_install.py
Using an environment variable `UCX_FORCE_INSTALL` you can force the installation of UCX over an existing installation.
The values for the environment variable are 'global' and 'user'.
Global Install: When UCX is installed at '/Applications/ucx'
User Install: When UCX is installed at '/Users/<user>/.ucx'
If there is an existing global installation of UCX, you can force a user installation of UCX over the existing installation by setting the environment variable `UCX_FORCE_INSTALL` to 'global'.
At this moment there is no global override over a user installation of UCX. As this requires migration and can break existing installations.
| global | user | expected install location | install_folder | mode |
| --- | --- | --- | --- |--- |
| no | no | default | `/Applications/ucx` | install |
| yes …
> Changed default UCX installation folder to `/Applications/ucx` from `/Users/<me>/.ucx` to allow multiple users users utilising the same installation

- tests/unit/test_install.py
Fix for `webbrowser.open` mock in #1048 was overridden by #1043 
Need recover it.
Resolves #..
> Fix: Recover lost fix for `webbrowser.open` mock

- src/databricks/labs/ucx/mixins/fixtures.py
- tests/integration/assessment/test_clusters.py
- tests/integration/hive_metastore/test_migrate.py
1. When `test_migrate_external_table` are being executed by two different integration tests at the same time, the latter test will fail because the first test creates an UC external table occupying the table location, since a location can only be used by one UC table. This PR proposes a new test fixture that will create a random location for UC external table migration test, and delete it when test is done to avoid the location overlapping error.
2. Update `test_policy_crawler` to add a random suffix to the cluster policy name to avoid the test failure due to leftover/uncleaned cluster policy named `test_policy_check` and `test_policy_check2`. 
Resolves #..
> Fix some integration test failures

- src/databricks/labs/ucx/config.py
- src/databricks/labs/ucx/framework/tasks.py
- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/runtime.py
- tests/integration/test_installation.py
- tests/unit/framework/test_tasks.py
- tests/unit/test_install.py
- tests/unit/test_runtime.py
Add migrate-tables workflow. This PR includes the workflow only described in milestone 1 in https://github.com/databrickslabs/ucx/issues/1035
table_migration_progress table is out of scope in this PR.
Relates #333 #670
> Add `migrate-tables` workflow

- src/databricks/labs/ucx/framework/tasks.py
In the latest update to the `ucx` framework, the `trigger` function in `tasks.py` has been modified to include a new argument, `install_folder`, in the `Installation` object. This object is now created within the `trigger` function and is passed to the `run_task` function. The `install_folder` is calculated by obtaining the parent directory of the `config_path` variable, converting it to a POSIX-style path, and removing the leading "/Workspace" prefix. This change ensures that the `run_task` function receives the correct installation folder for the `ucx` framework, enhancing the overall functionality and accuracy of the `ucx` framework.
> Addressed Integration Test Issue

- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- tests/integration/hive_metastore/test_migrate.py
- tests/integration/test_installation.py
- tests/unit/hive_metastore/test_table_migrate.py
Parse the result returned by SYNC command and log the failures if any
Resolves #1071
> Handle SYNC command failures

- tests/integration/test_installation.py
Skip `test_table_migration_job` integration test for now to avoid slowing down due to azure instance provisioning, until we add instance pool to cluster policy.
Resolves #..
> Skip test_table_migration_job integration test for now

- README.md
Added the detail that running UCX as a Service Principal is not supported under Installation
Resolves #..
> Update README.md for Service Principal Installation Limit

- src/databricks/labs/ucx/installer/policy.py
- tests/integration/test_installation.py
- tests/unit/installer/test_policy.py
1. Allow user to set instance pool id in the cluster policy used for assessment and migration job clusters.
2. Make `test_table_migration_job` integration test to use `env_or_skip("TEST_INSTANCE_POOL_ID")`
3. Skip `test_table_migration_job` if env `TEST_NIGHTLY` is missing or is not set to "true", so the integration test triggered by PR will not be slowed down.
Resolves #..
> Add instance pool to cluster policy

- README.md
The `cluster-remap` and `revert-cluster-remap` commands have been added to the project's open-source library to assist administrators in managing their clusters' UC settings. The `cluster-remap` command allows users to remap their clusters to UC-enabled ones by providing a comma-separated list of cluster IDs. It updates the specified clusters to UC-enabled and stores a backup of the existing cluster configuration in a JSON file. This backup can be used to revert the cluster remapping if necessary using the `revert-cluster-remap` command. This command iterates through the list of clusters from the backup folder and reverts the cluster configurations to their original state. These commands provide administrators with the ability to manage their clusters' UC settings and revert any changes …
> Updated missing documentation for cluster remap command

- src/databricks/labs/ucx/framework/tasks.py
- tests/unit/framework/test_tasks.py
Delete the log folder created by TaskLogger in unit test after the test is done.
Resolves #..
> Clean up the log folder created by TaskLogger in unit test

- src/databricks/labs/ucx/cli.py
- tests/unit/test_cli.py
Workspace Id was taj=king as string instead of list of int. Fixed the same by converting it int list of int using list comprehension.
#1090
Resolves #..
> Fixing the issue in workspace id flag in create-account-group command

- pyproject.toml
- src/databricks/labs/ucx/assessment/clusters.py
- Fix pylint warning `consider using --check-untyped-defs `
- Fix ruff warning `ruff <path> is deprecated`
> Fix pylint & ruff warning

- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/hive_metastore/catalog_schema.py
- tests/unit/hive_metastore/test_catalog_schema.py
- tests/unit/test_cli.py
In this release, we have updated the "create\_catalogs\_schemas" function in "cli.py" to create UC catalogs and schemas based on the destinations from "create\_table\_mapping". This function previously used a "CatalogSchema" object created using the workspace client, installation, and prompts, but has been modified to directly use the installation object and call the "create\_all\_catalogs\_schemas" method. We have also added a new feature for catalog validation with commit message 'Feature/create catalog validation 1101', which includes the addition of the "create\_all\_catalogs\_schemas" method in "catalog\_schema.py". The new method generates a list of missing catalogs and schemas and creates them using the "WorkspaceClient". Additionally, we have added new imports, modified the …
> Added external location validation when creating catalogs with `create-catalogs-schemas` command

- src/databricks/labs/ucx/install.py
- tests/integration/test_installation.py
- tests/unit/test_install.py
Compares the remote version and local wheel version and prompts for re-install confirmation if they are the same. 
Closes #1072
Closes #803
> Skip installation if remote and local version is the same, provide prompt to override

- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- tests/unit/hive_metastore/test_table_migrate.py
Fixed logic where list of grants are not reset between table iteration. Also updated tests to catch these issues
> Fix Table ACL migration logic

- src/databricks/labs/ucx/runtime.py
There are bugs found from the nightly test. Disable the ACL migration in table migration workflow for now until we fix the bugs.
Related #1144 #1145
> Disable table ACL migration in table migration workflow 

- src/databricks/labs/ucx/installer/workflows.py
- src/databricks/labs/ucx/runtime.py
- tests/integration/test_installation.py
- tests/unit/test_install.py
This PR addressed issues with the integration test.
We improved handling of workflow runs.
Closes #1143
The 'run\_workflow' method in 'workflows.py' has been updated to reliably handle job failures and provide better error information. Previously, the method used 'run\_now' to start a job without waiting for it to finish, which could result in an incomplete or failed job. The updated code creates a 'job\_initial\_run' using 'run\_now' and checks if a run ID is returned, indicating that the job has started successfully. If the job fails, an error is raised with more detailed information. Additionally, a new private method '_infer\_error\_from\_job\_run' is defined to infer the error from the job run object. In the `test_installation.py` file, the error handling in the integration test for …
> Fixing run_workflow functionality for better error handling.

- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- src/databricks/labs/ucx/source_code/languages.py
- src/databricks/labs/ucx/source_code/lsp.py
- src/databricks/labs/ucx/source_code/queries.py
- tests/unit/source_code/conftest.py
- tests/unit/source_code/test_languages.py
This PR fixes the bug in `Index` that was presenting non-migrated tables as migrated. It also clarifies the intent of this class by renaming it to `MigrationIndex`.
> Return correct value from `Index.is_upgraded()`

- tests/unit/hive_metastore/test_tables.py
Sort queries before comparing them, otherwise parallel execution will randomly fail unit tests like in https://github.com/databrickslabs/ucx/actions/runs/8479114292/job/23232581236?pr=1166 for https://github.com/databrickslabs/ucx/pull/1166
```
E       AssertionError: assert ['SELECT * FR...abase.table1'] == ['SELECT * FR...abase.table2']
E         
E         At index 2 diff: 'DESCRIBE TABLE EXTENDED hive_metastore.database.table2' != 'DESCRIBE TABLE EXTENDED hive_metastore.database.table1'
E         
E         Full diff:
E           [
E               'SELECT * FROM hive_metastore.default.tables',
E               'SHOW TABLES FROM hive_metastore.database',
E         +     'DESCRIBE TABLE EXTENDED hive_metastore.database.table2',
E               'DESCRIBE TABLE EXTENDED …
```
> Fixed flaky `test_tables_crawler_should_filter_by_database`

- src/databricks/labs/ucx/hive_metastore/tables.py
- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/installer/workflows.py
- src/databricks/labs/ucx/runtime.py
- tests/integration/test_installation.py
- tests/unit/hive_metastore/test_tables.py
1. Deploy `udfs` table in inventory database when install, which avoids the potential race condition that two parallel workflow tasks are trying to create this missing table at the same time.
2. Catch NotFound exception when listing table in schema in `TablesCrawler._crawl`. During the integration test, schema are being created and deleted and there is a chance the schema is deleted when trying list tables inside it. In this case, RuntimeBackend will raise NotFound and it needs to be handled.
3. Table migration workflow need to use shared mode cluster so it can crawl table ACLs, in case the `grants` table is empty.
4. Upload wheel to WSFS instead of DBFS if table migration job cluster, because shared mode cluster cannot use DBFS wheel.
5. Improve table migration workflow integration test: …
> Improve table migration workflow test and add ACL migration back

- src/databricks/labs/ucx/runtime.py
- src/databricks/labs/ucx/workspace_access/groups.py
- tests/integration/test_installation.py
- tests/integration/workspace_access/test_generic.py
- tests/integration/workspace_access/test_redash.py
- tests/integration/workspace_access/test_scim.py
- tests/integration/workspace_access/test_secrets.py
- tests/integration/workspace_access/test_tacl.py
- tests/performance/test_performance.py
- tests/unit/test_runtime.py
- tests/unit/workspace_access/test_manager.py
This PR removes verification step from the experimental group migration job, as platform already replaces permissions from workspace group to account group and old validation method is not required anymore.
> Use experimental Permissions Migration API also for Legacy Table ACLs

- src/databricks/labs/ucx/mixins/fixtures.py
- tests/integration/test_installation.py
Fix two failed integration tests `test_check_inventory_database_exists` and `test_compare_remote_local_install_versions` due to changes made in #1166 
Resolves #..
> Fix integration tests failure from #1166

- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/installer/workflows.py
- tests/integration/test_installation.py
- tests/unit/test_install.py
#1055 removed the prompts for configuring the auto-scale and parallelism for table migration job cluster.
This PR add the prompts back in the ~~WorkflowInstallation, and update the WorkspaceConfig to persist the config values.~~ `WorkspaceInstaller._configure_new_installation`
Resolves #..
> Add back prompts for table migration job cluster configuration

- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/installer/workflows.py
- tests/integration/test_installation.py
- tests/unit/test_install.py
WorkflowsDeployment handles workflow deployment only and should not be dependent on prompts. Remove prompts from the class and only inject the prompts when uploading wheels to non writeable dbfs and need to use override cluster.
Resolves #..
> Remove prompts dependency from WorkflowsDeployment

- src/databricks/labs/ucx/source_code/languages.py
- src/databricks/labs/ucx/source_code/pyspark.py
- src/databricks/labs/ucx/source_code/queries.py
- tests/unit/source_code/test_pyspark.py
Enhance SparkSql linter/fixer to support migration of spark.sql function calls that receive a table name as parameter
Resolves # 1082
missing integration tests
> Support table migration to Unity Catalog in Python code

- src/databricks/labs/ucx/installer/workflows.py
- tests/integration/test_installation.py
test_running_real_assessment_job fails due to java TimeoutException. Now it raises TimeoutError instead and retry added for the same.
Resolves #1146
> Raise TimeoutError if tests contain java TimeoutException

- src/databricks/labs/ucx/hive_metastore/mapping.py
- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- tests/unit/hive_metastore/test_mapping.py
- tests/unit/hive_metastore/test_table_migrate.py
Add try except in following places to avoid the schema NotFound error caused by test schemas from other integration test runs are deleted at the same time the table migration test are trying to access them.
- When `MigrationStatusRefresher` lists catalogs and schemas to check the migration status of the tables.
- When `TableMapping` describe schema to check the skip property.
Resolves #1217
> Fix flaky table migration test due to schema not found

- tests/integration/hive_metastore/test_migrate.py
use proper scope when calling `migrate_tables`
Resolves #1235 
Resolves #1236 
Resolves #1237
Pending verification on staging environment
> Fix failing integration tests for table migration

- src/databricks/labs/ucx/hive_metastore/table_migrate.py
remove *args from migrate_tables prototype to avoid masking incorrect calls
None
> remove *args from migrate_tables prototype

- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/installer/mixins.py
- src/databricks/labs/ucx/installer/workflows.py
- tests/unit/test_install.py
Refactoring required for https://github.com/databrickslabs/ucx/pull/1209
> Split `DeployedWorkflows` out of `WorkflowsDeployment`

- tests/integration/hive_metastore/test_migrate.py
- tests/integration/test_installation.py
1. Update `test_installation.py` integration tests with new `DeployedWorkflows`
2. Speed up table migration tests by preparing test data for `tables`, `grants`, `groups` inventory database table to avoid crawling them from scratch which slows down the test. This fixes #1245, #1243
3. Fix timed out test #1242 , because the issue [here](https://github.com/databrickslabs/ucx/commit/5d82ae024c7529cd8b549fb2372cd12dd3655efd#r140584433) caused infinite retry until timeout, as source table has `What.EXTERNAL_SYNC` but the test is trying to upgrade `What. DBFS_ROOT_DELTA `
Resolves #1242
Resolves #1245
Resolves #1243
> Fix integration test with new DeployedWorkflows

- src/databricks/labs/ucx/workspace_access/manager.py
- tests/unit/workspace_access/test_manager.py
closes #1228 
The PermissionManager class in manager.py has been updated to ignore errors caused by disabled features in specific regions when inventorying permissions. A new attribute, ERRORS\_TO\_IGNORE, has been added and is initialized with ["FEATURE\_DISABLED"]. Errors not in this list will be logged and raise a ManyError exception if present. This change allows for disabling features without causing inventory errors.
> Addressed Issue with Disabled Feature in certain regions

- pyproject.toml
`isort` and `pylint` disagree on import order with:
```
from databricks.sdk.service.workspace import Language
from sqlglot import ParseError as SQLParseError
from sqlglot import parse as parse_sql
```
the solution is to remove `isort` from the `make fmt` build command
remove sort from build checks
None
> remove `isort`

- pyproject.toml
> disable annotation-unchecked mypy warning

- src/databricks/labs/ucx/queries/assessment/main/40_2_logs.sql
The logs query might not work when multiple log lines match with the max timestamp. 
Resolves #1283
> Select DISTINCT job_run_id

- src/databricks/labs/ucx/hive_metastore/migration_status.py
- tests/unit/hive_metastore/test_table_migrate.py
- `test_revert_migrated_table` was failing, due to new output of `SHOW TBLPROPERTIES` - previously, it is blank if a tbl prop is missing, now it shows `Table <table> does not have property: <prop>`
> Handled new output format of `SHOW TBLPROPERTIES` command

- tests/integration/hive_metastore/test_migrate.py
`test_migrate_view` timed out because `migration_status_refresher` table was not created
> Fixed `test_migrate_view` timeout

- src/databricks/labs/ucx/contexts/application.py
- tests/integration/hive_metastore/test_migrate.py
- tests/integration/test_installation.py
Temporarily disabled tests that do not work on AWS, for 2 reasons:
- `make_dbfs_data_copy` does not work with mounts on aws
- `principal_acl` does not have aws implementation yet
> Temporarily disabled tests that do not work on aws

- tests/integration/test_installation.py
- Fixed missing prompt for integration tests when cluster policies with ext hms are detected on the workspace
> Fixed integration tests failing on workspaces with external hms cluster policies

- src/databricks/labs/ucx/contexts/workflow_task.py
Fixing configuration include_paths_in_mount not being propagated to the RuntimeContext properly
> Fixing include_paths_in_mounts not being propagated

- src/databricks/labs/ucx/source_code/notebook.py
- tests/unit/source_code/samples/notebook-with-pip-cell.py.txt
- tests/unit/source_code/samples/notebook-with-shell-cell.py.txt
- tests/unit/source_code/test_notebook.py
add SHELL CellLanguage 
#1202
Resolves #1399
> add support for %sh cells

- src/databricks/labs/ucx/assessment/aws.py
- tests/unit/assessment/test_aws.py
closes #1333 
1. A bug in the AWS Unity Catalog (UC) Role's trust policy update feature has been addressed with new method `_databricks_trust_statement` in `aws.py` file.
2. Trust policy for UC role is updated correctly with modifications in `create_uc_role` and `update_uc_trust_role` methods and new unit tests added for functionality assurance.
3. `test_update_uc_trust_role` function has been updated and renamed to `test_update_uc_trust_role_append`, now includes mocked AWS CLI command for updating trust relationship policy, with a new trust policy document having a single statement with two principals and external ID matching condition.
> Addressed a bug with AWS UC Role Update. Adding unit tests.

- src/databricks/labs/ucx/azure/access.py
- tests/unit/azure/test_access.py
Give all access connectors STORAGE_BLOB_DATA_CONTRIBUTOR access.
More fine-grained access is configured within unity catalog. We give all access connectors (one for each storage account) the highest data access, i.e. data contributor.
Resolves #1383
> Give all access connectors `Storage Blob Data Contributor` role

- tests/integration/test_ext_hms.py
Mark the unused arguments with the `_ = <parameter>` convention to avoid the linter complaining
> Fix unused arguments in CommandContextBackend

- tests/integration/workspace_access/test_groups.py
Give the API five seconds to delete the group.
Resolves #1277
> Fix test failure: `test_delete_ws_groups_should_delete_renamed_and_reflected_groups_only`

- tests/integration/conftest.py
- tests/integration/hive_metastore/test_migrate.py
- Combined `with_dummy_aws_resource_permission` and `with_dummy_azure_resource_permission` into a single fixture `with_dummy_resource_permission`
- Re-enable migration tests that were skipped on aws previously
> Re-enable migration tests on aws environments

- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- src/databricks/labs/ucx/hive_metastore/tables.py
- tests/unit/hive_metastore/tables/external_src_non_sync.json
- tests/unit/hive_metastore/test_table_migrate.py
relates to #1340
A new feature allows migration of external tables in Databricks' Hive metastore using "Create Table (No Sync)" method, with new methods `_migrate_non_sync_table` and `_get_create_in_place_sql` for migration and SQL query generation. The `_migrate_dbfs_root_table` and `_migrate_acl` methods have also been updated. A new test case demonstrates migration of external tables while preserving their location and properties.
> Added functionality to migrate external tables using Create Table (No Sync)

- src/databricks/labs/ucx/source_code/base.py
- src/databricks/labs/ucx/source_code/dependencies.py
- src/databricks/labs/ucx/source_code/dependency_linters.py
- src/databricks/labs/ucx/source_code/files.py
- src/databricks/labs/ucx/source_code/notebook.py
- src/databricks/labs/ucx/source_code/python_linter.py
- src/databricks/labs/ucx/source_code/whitelist.py
- tests/unit/source_code/samples/s3fs-python-compatibility-catalog.yml
- tests/unit/source_code/test_notebook.py
- tests/unit/source_code/test_python_linter.py
- tests/unit/source_code/test_s3fs.py
In order to report the location of imports that are either deprecated or will be migrated automatically, the location of the origin source code needs to be preserved. The graph of package dependencies now propagates location information such that reporting can indicate the hierarchy of dependencies that led to discovery of the deprecated import, or one that will be automatically migrated.
Resolves #1418
> Propagate source location information within the import package dependency graph

- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- src/databricks/labs/ucx/hive_metastore/tables.py
- src/databricks/labs/ucx/mixins/fixtures.py
- tests/integration/hive_metastore/test_migrate.py
- tests/unit/hive_metastore/tables/dbfs_parquet.json
- tests/unit/hive_metastore/tables/external_src_non_sync.json
- tests/unit/hive_metastore/test_table_migrate.py
Migrate Non-Delta DBFS root tables to Managed Delta tables.
closes #1340
This release enhances migration for non-delta DBFS tables, supporting more table types and configurations. New methods improve CTAS functionality with safer SQL statement generation. Additional table format compatibility, new creation methods, and updated integration tests are included. Grant assignments during migration are now supported.
> Migrate non delta dbfs tables using Create Table As Select (CTAS). Convert such tables to Delta tables.

- src/databricks/labs/ucx/installer/logs.py
- src/databricks/labs/ucx/mixins/fixtures.py
- tests/integration/conftest.py
- tests/integration/framework/test_fixtures.py
- tests/integration/hive_metastore/test_migrate.py
- Fix `TypeError: 'tuple' object is not callable` for `test_migrate_external_table`
- Fix tests that migrate external tables failed due to UC blocking tables with overlapping paths
- Fix assessment tests that failed due to expected error messages in `parse_logs`, by skipping over these error messages if ucx version is testing
Resolves #1436, #1424
> Fix integration tests flakiness

- tests/integration/hive_metastore/test_tables.py
- `make_table` now creates external tables that are identified as `DBFS_ROOT_NON_DELTA`. This was a change introduced in #1434
> Fix `test_describe_all_tables_in_databases`

- tests/integration/hive_metastore/test_migrate.py
- make sure `test_migrate_managed_tables_with_principal_acl_azure` only runs on Azure
> Fix `test_migrate_managed_tables_with_principal_acl_azure`

- src/databricks/labs/ucx/installer/policy.py
- tests/integration/hive_metastore/test_migrate.py
- tests/unit/installer/test_policy.py
In AWS, `aws_attributes.availability` now conflicts with `instance_pool_id` in a cluster policy
> Fix UCX policy creation when instance pool is specified

- .github/workflows/push.yml
v4 of codecov-action no longer supports tokenless upload. ~Let's try avoiding tokens altogether by using OIDC.~ OIDC doesn't seem to work: https://github.com/codecov/codecov-action/issues/1378, using managed `CODECOV_TOKEN` secrets.
> Use managed upload token for codecov.io

- tests/integration/test_installation.py
- tests/integration/workspace_access/test_groups.py
Due to eventual consistency, wait up to 2 minutes before failed tests involved group APIs
> Extended wait time for group checking during tests

- pyproject.toml
- src/databricks/labs/ucx/assessment/azure.py
- src/databricks/labs/ucx/hive_metastore/locations.py
- src/databricks/labs/ucx/source_code/lsp.py
- src/databricks/labs/ucx/source_code/table_creation.py
- tests/unit/test_install.py
- tests/unit/workspace_access/test_generic.py
This PR enforces the removal of commented code:
```
cmd [4] | pylint --output-format=colorized -j 0 src tests
************* Module databricks.labs.ucx.hive_metastore.locations
src/databricks/labs/ucx/hive_metastore/locations.py:105:0: C8920: Remove commented out code: # dbtable = result_dict.get("dbtable", "") (dead-code)
```
> Enforced removal of commented-out code on `make fmt`

- src/databricks/labs/ucx/install.py
- tests/integration/conftest.py
- tests/integration/test_installation.py
- tests/unit/assessment/test_dashboard.py
- tests/unit/test_install.py
- refactor `WorkspaceInstaller` using service factory.
- this removes the need for `sql_backend_factory` and `wheel_builder_factory`
- there is no more logic inside of `main` function in `install.py`, so we can achieve better test coverage through unit testing
- remove obsolete reference to `WorkspaceInstaller` in `unit/test_dashboard.py`
This follows #1209
> Refactor `WorkspaceInstaller` using service factory

- tests/integration/hive_metastore/test_migrate.py
Not sure why didn't the integration test run in PR #1413 catch the failure of this test `test_migrate_external_tables_with_spn_azure`, but we need this fix to avoid the  `ValueError: too many values to unpack (expected 2)` error.
Resolves #1497
> Fix failed integration test `test_migrate_external_tables_with_spn_azure`

- labs.yml
- src/databricks/labs/ucx/assessment/aws.py
- src/databricks/labs/ucx/aws/access.py
- src/databricks/labs/ucx/aws/credentials.py
- tests/unit/assessment/test_aws.py
- tests/unit/aws/test_credentials.py
- tests/unit/test_cli.py
- added missing flags to `migrate-credential` command
- passed AWS profile explicitly to all awscli commands
- passed IAM role name when updating trust policy instead of IAM ARN
Resolves #1332
> Fix `migrate-credentials` command on aws

- src/databricks/labs/ucx/install.py
- tests/integration/test_installation.py
A warehouse might be manually deleted. This will break the uninstallation process as the warehouse, for example, because the warehouse is required for dropping the database. This PR checks if the warehouse still exists during the uninstallation, it requests the use to reinstall the warehouse if it does not exist anymore
Resolves #1467
> Prompt for warehouse choice in uninstall if the original chosen warehouse does not exist anymore

- src/databricks/labs/ucx/hive_metastore/view_migrate.py
- tests/unit/hive_metastore/tables/tables_and_views.json
- tests/unit/hive_metastore/test_views_sequencer.py
Added check for circular view dependency
fixes #1158 
Existing test for circular view dependency is satisfied, and a new test to check chained circular dependency (A->B, B->C, C->A) has been added.
> Added check for circular view dependency

- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- src/databricks/labs/ucx/hive_metastore/tables.py
- src/databricks/labs/ucx/hive_metastore/workflows.py
- src/databricks/labs/ucx/runtime.py
- tests/integration/hive_metastore/test_migrate.py
- tests/integration/test_runtime.py
- tests/unit/hive_metastore/tables/external_no_sync.json
- tests/unit/hive_metastore/tables/external_no_sync_missing_location.json
- tests/unit/hive_metastore/test_table_migrate.py
- tests/unit/hive_metastore/test_workflows.py
Add CTAS migration workflow for:
1. HiveSerde external tables.
2. Other type of external tables that have to be CTAS migrated.
Resolves #889
> Add CTAS migration workflow for external tables cannot be in place migrated

- src/databricks/labs/ucx/azure/access.py
- src/databricks/labs/ucx/azure/resources.py
- tests/integration/azure/test_access.py
Grant uber principal on Azure blob contributor permission, to match the implementation on AWS where uber principal is granted write permission to all the s3 buckets
https://github.com/databrickslabs/ucx/blob/10ca568cf8c7b465c513bba42431bf02669f1a61/src/databricks/labs/ucx/assessment/aws.py#L245-L257
Resolves #939
> Grant uber principal write permissions so that SYNC command will succeed

- src/databricks/labs/ucx/source_code/pyspark.py
- tests/unit/source_code/test_notebook_linter.py
- tests/unit/source_code/test_pyspark.py
Uses the Pyspark linter, which detects the use of table names that should be migrated, to also detect the use of direct access to cloud storage. Additional deprecation advisories are issued when direct cloud access is detected.
Resolves #1133
> Detect direct access to cloud storage and raise a deprecation warning

- src/databricks/labs/ucx/installer/policy.py
- src/databricks/labs/ucx/installer/workflows.py
- src/databricks/labs/ucx/mixins/fixtures.py
- tests/integration/test_installation.py
- tests/unit/installer/test_policy.py
- tests/unit/test_install.py
- Choose instance types with 16GB memory to avoid OOM for assessment tasks
Resolves #1364
-  Switch cluster policy to minimum 16gb RAM, as instances with 8gb RAM only has 710MB memory for executors
> Increased memory for ucx clusters

- src/databricks/labs/ucx/source_code/dependencies.py
- src/databricks/labs/ucx/source_code/dependency_loaders.py
- src/databricks/labs/ucx/source_code/dependency_resolvers.py
- src/databricks/labs/ucx/source_code/files.py
- src/databricks/labs/ucx/source_code/notebook.py
- src/databricks/labs/ucx/source_code/notebook_migrator.py
- tests/unit/__init__.py
- tests/unit/source_code/test_dependencies.py
- tests/unit/source_code/test_notebook.py
- tests/unit/source_code/test_s3fs.py
- tests/unit/source_code/test_whitelist.py
dependencies.py has become too big and is split into 3 smaller files
None
@nfx supersedes #153, rebased from latest main
> split dependencies.py

- src/databricks/labs/ucx/workspace_access/groups.py
- tests/unit/workspace_access/test_groups.py
- `RegexSubStrategy` will fail if the strategy generated a non-existent account group
- Add more unit tests
> Fixed edge case for `RegexSubStrategy`

- pyproject.toml
- src/databricks/labs/ucx/aws/credentials.py
- src/databricks/labs/ucx/contexts/cli_command.py
- tests/integration/aws/test_credentials.py
- tests/unit/assessment/test_clusters.py
- tests/unit/aws/test_access.py
- tests/unit/aws/test_credentials.py
- tests/unit/azure/test_access.py
- tests/unit/azure/test_credentials.py
- tests/unit/azure/test_locations.py
- tests/unit/conftest.py
- tests/unit/framework/test_tasks.py
- tests/unit/hive_metastore/test_catalog_schema.py
- tests/unit/hive_metastore/test_mapping.py
- tests/unit/hive_metastore/test_table_migrate.py
- tests/unit/hive_metastore/test_views_sequencer.py
- tests/unit/source_code/test_dependencies.py
- tests/unit/source_code/test_files.py
- tests/unit/source_code/test_notebook_migrator.py
- tests/unit/test_account.py
- tests/unit/test_cli.py
- tests/unit/test_install.py
- tests/unit/workspace_access/test_clusters.py
- tests/unit/workspace_access/test_generic.py
- tests/unit/workspace_access/test_groups.py
- tests/unit/workspace_access/test_manager.py
- tests/unit/workspace_access/test_redash.py
- tests/unit/workspace_access/test_secrets.py
Enforce check defined in:
- https://github.com/databrickslabs/pylint-plugin/pull/44
> Remove hidden bugs from unit tests by enforcing mocks

- src/databricks/labs/ucx/hive_metastore/locations.py
- src/databricks/labs/ucx/hive_metastore/tables.py
- tests/unit/hive_metastore/test_locations.py
Adding a filter to remove tables in mounts that have been identified by the assessment.
As the assessment job will identify tables in hive metastore, these tables can be considered as tables in mounts later by the scan tables in mounts job.
We should filter those tables as it will yields duplicates during the mapping and migration phase. Plus UCX yields better support to migrate tables that are registered in HMS.
> Adding seen tables feature

- tests/unit/hive_metastore/test_catalog_schema.py
Add unit test to show that the `create-catalogs-schemas` logic works with tables defined as mount paths.
Resolves #1039
> Test if `create-catalogs-schemas` works with tables defined as mount paths

- src/databricks/labs/ucx/hive_metastore/catalog_schema.py
- tests/unit/hive_metastore/test_catalog_schema.py
If tables in the schema source schema are mapped to different target schemas, a collision occurs when building the grants mapping. This PR fixes the bug created by that collision.
Resolves #1580
> Fix: catalog/schema grants when tables with same source schema have different target schemas

- src/databricks/labs/ucx/hive_metastore/grants.py
- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- tests/integration/hive_metastore/test_migrate.py
- tests/unit/hive_metastore/test_principal_grants.py
- tests/unit/hive_metastore/test_table_migrate.py
`test_migrate_managed_tables_with_acl` is flaky, because there are multiple not found exceptions that are not handled, which happens when tests are running in parallel
Resolves #1549
> improved exception handling for `migrate_acl`

- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- src/databricks/labs/ucx/hive_metastore/workflows.py
- tests/integration/hive_metastore/test_workflows.py
Refresh migration status at the end of the `migrate_tables` task
Resolves #1597
> Refresh migration status at the end of the `migrate_tables` workflows

- labs.yml
- src/databricks/labs/ucx/assessment/aws.py
- src/databricks/labs/ucx/aws/access.py
- src/databricks/labs/ucx/aws/credentials.py
- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/contexts/cli_command.py
- tests/unit/aws/test_access.py
- tests/unit/test_cli.py
The `create_missing_principals` CLI command creates UC roles with `IamRoleCreation` from `databricks.labs.ucx.aws.credentials`. It updates `AWSRoleAction` with `role_arn` and adds `AWSUCRoleCandidate`. Not supported for Azure, and `migrate_credentials` is updated to migrate Azure Service Principals.
> Added CLI Command `create_missing_principals` to create the missing UC roles.

- src/databricks/labs/ucx/install.py
- tests/unit/test_install.py
- Add error handling when running `installation.load`
Resolves #1601
> Ignore existing corrupted installations when refreshing

- .github/workflows/acceptance.yml
- .github/workflows/no-cheat.yml
- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/contexts/account_cli.py
- src/databricks/labs/ucx/contexts/application.py
- src/databricks/labs/ucx/contexts/workspace_cli.py
- src/databricks/labs/ucx/install.py
- tests/integration/aws/test_access.py
- tests/integration/conftest.py
- tests/performance/test_performance.py
- tests/unit/test_cli.py
- tests/unit/test_factories.py
This PR splits `cli_command.py` into `workspace_cli.py` and `account_cli.py`
> Avoid cyclic import issues, when we need to initialize `WorkspaceContext` from `AccountContext`

- src/databricks/labs/ucx/hive_metastore/migration_status.py
- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- tests/integration/hive_metastore/test_workflows.py
- Always reset table migration status when requesting the latest snapshot within `table_migrate`
- Handle `NotFound` error when refreshing migration status
Resolves #1622, #1615
> Improved reliability of table migration status refresher

- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- src/databricks/labs/ucx/hive_metastore/workflows.py
- This was missed in #1623 where we added a new method to fully refresh the migration status. This must be called in table migration workflow task.
Resolves #1628
> Fully refreshed table migration status in table migration workflow

- tests/unit/hive_metastore/test_workflows.py
> Add unit test for calling refresh_migration_status in migrate table workflows

- README.md
- labs.yml
- src/databricks/labs/ucx/account/aggregate.py
- src/databricks/labs/ucx/account/workspaces.py
- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/contexts/account_cli.py
- src/databricks/labs/ucx/contexts/workspace_cli.py
- src/databricks/labs/ucx/install.py
- tests/unit/account/test_aggregate.py
> Aggregate UCX output across workspaces with CLI command

- src/databricks/labs/ucx/azure/access.py
- tests/unit/azure/test_access.py
A configuration parameter referencing a secret should use double curly brackets
Resolves #1629
> Fix Spark configuration parameter referencing secret

- tests/integration/conftest.py
Similarly to the prefix catalogs with "C", tables with "T" and schemas with "S", also prefix random test group names with "G". 
Hopefully it narrows the KeyError in: #1616
> Prefix random test group names with capital G

- tests/integration/hive_metastore/test_workflows.py
Reqwrite migration status test to have one assert in an attempt to better understand when it fails.
Hopefully provides more information for #1615
> Let migration status test have one assert

- README.md
- docs/troubleshooting.md
- src/databricks/labs/ucx/account/workspaces.py
- src/databricks/labs/ucx/install.py
- tests/unit/account/test_aggregate.py
- tests/unit/account/test_workspaces.py
- Automatically retrying with `auth_type=azure-cli` when constructing `workspace_clients` on Azure
- Resolved TODO items for `AccountWorkspaces`
- Added relevant suggestions in `troubleshooting.md`
Closes #1574, closes #1430
> Automatically retrying with `auth_type=azure-cli` when constructing `workspace_clients` on Azure

- tests/unit/aws/test_access.py
- tests/unit/test_cli.py
- tests/unit/test_install.py
- tests/unit/workspace_access/test_clusters.py
- Replaced all usage of `create_autospec(Installation)` with `MockInstallation`
- One final usage requires https://github.com/databrickslabs/blueprint/pull/101
> Used `MockInstallation` consistently instead of `create_autospec(Installation)`

- README.md
- labs.yml
- src/databricks/labs/ucx/cli.py
- tests/unit/test_cli.py
This change adds support for migrate-tables-ctas into the existing cli cmd for migrate-tables.
Checks for the presence of an external table which cannot be synced and prompts the user to run the additional workflow
Also updated relevant readme doc
Resolves #1659
> Add support for migrate-tables-ctas workflow in the cmd `databricks labs ucx migrate-tables`

- tests/unit/test_install.py
- Codecov flakiness comes from `installer/workflows.py`, in particular this line  
https://github.com/databrickslabs/ucx/blob/9c67520c3a32e105b1acd85210cc1254a7de262a/src/databricks/labs/ucx/installer/workflows.py#L331-L333
> fix codecov flakiness

- README.md
- src/databricks/labs/ucx/config.py
- src/databricks/labs/ucx/install.py
The outcome of the prompt is not used and might confuse users. (We received feedback that it does confuse an user.) Moreover, in the near future we don't expect to use the Terraform state for ucx migration.
Was introduced for #393
> Remove the "Is Terraform used" prompt

- tests/integration/test_ext_hms.py
Assert if group name is in cluster policy
Does not resolve the issue, but asserts the key to avoid the key error in #1616
> Assert if group name is in cluster policy

- src/databricks/labs/ucx/installer/policy.py
A period and space were missing in the prompt for using external metastore
> Fix prompt for using external metastore

- tests/integration/hive_metastore/test_workflows.py
- Test there are any migration statuses
- Log migration statuses with test failure
In addition to #1651, hopefully provides more information for #1615
> Let migration status test assert all migration statuses

- src/databricks/labs/ucx/mixins/wspath.py
- tests/integration/mixins/test_wspath.py
This PR removes the dependency on internal `pathlib._Flavor` implementations, which could be not available on Windows.
> Removed dependency on internal `pathlib` implementations

- src/databricks/labs/ucx/mixins/fixtures.py
- tests/integration/conftest.py
- tests/integration/test_ext_hms.py
(We think that) sometimes groups are not created before the test run, e.g. [this](https://github.com/databrickslabs/ucx/actions/runs/9002466231?pr=1532) and [that](https://github.com/databrickslabs/ucx/issues/1616). This PR extends the `make_group` with an optional flag to wait for the groups to be created before continuing with the test. To limit impact on performance, we don't wait for the groups to be created by default.  
Hopefully esolves #1616
> Fix test failing due to groups not being created yet

- src/databricks/labs/ucx/hive_metastore/mapping.py
- tests/unit/hive_metastore/test_mapping.py
- improved error handling for `migrate-tables` workflows
Resolves #1673
> improved error handling for `migrate-tables` workflows

- tests/integration/test_ext_hms.py
- Used correct cluster for  `test_running_real_assessment_job_ext_hms`
Resolves #1682
> Fixed `test_running_real_assessment_job_ext_hms` failure

- src/databricks/labs/ucx/source_code/graph.py
- src/databricks/labs/ucx/source_code/notebooks/cells.py
- tests/unit/source_code/notebooks/test_cells.py
Logic for registering import installed in a pip cell
#1642
Follow up on #1692
>  Add pip cell installs to dependency graph

- src/databricks/labs/ucx/mixins/fixtures.py
- tests/integration/source_code/test_jobs.py
Add an integration test validating a library import can not be resolved if the PyPI dependency is not defined.
Part of #1642
> Add integration test for linting task with pip dependency

- docs/assessment.md
The recent release of DBR 14+ make `spark.catalog.x` functions 'safe' to run on shared compute so updating guidance.
Update assessment readme, updating user guidance for shared compute fixes to `spark.catalog.*` functions
> Update assessment.md - `spark.catalog.x` guidance needed updating

- src/databricks/labs/ucx/mixins/fixtures.py
- tests/integration/assessment/test_jobs.py
Add RemoveAfter tag on all UCX jobs, so that they're cleaned up by watchdog even if they are in the approved instance pool
Partial work from #977
> Add RemoveAfter tag on all UCX jobs for cleanup

- src/databricks/labs/ucx/hive_metastore/table_size.py
- tests/unit/hive_metastore/test_table_size.py
- Always refresh HMS stats when getting table size, to avoid getting stale stats
Resolves #1712
> Always refresh HMS stats when getting table size

- labs.yml
- src/databricks/labs/ucx/assessment/aws.py
- src/databricks/labs/ucx/aws/access.py
- src/databricks/labs/ucx/aws/credentials.py
- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/contexts/workspace_cli.py
- tests/integration/aws/test_access.py
- tests/unit/aws/test_access.py
- tests/unit/test_cli.py
- Automatically retrieved `aws_account_id` from aws profile instead of prompting users for this.
- Documented the optional kms-key flag for create roles
cc: @mohanab-db 
Resolves #1714
> Automatically retrieved `aws_account_id` from aws profile instead of prompting

- .github/codecov.yml
- Allow the coverage to drop by 0.5% to avoid failures for small fixes.
- Per https://docs.codecov.com/docs/codecovyml-reference#coveragestatus and https://docs.codecov.com/docs/commit-status
Resolves #1727
> Added `codecov.yml` and set threshold to 0.5%

- src/databricks/labs/ucx/source_code/python_libraries.py
- tests/unit/source_code/test_python_libraries.py
Rewrite `PipResolver._locate_dist_info` to use `Path`
Resolves #1750
> Rewrite `PipResolver._locate_dist_info` to use `Path`

- tests/integration/azure/test_credentials.py
- tests/integration/azure/test_locations.py
Update tests to use non-external access connector within testing. 
Part of #1384
> Use non external access connector in testing

- src/databricks/labs/ucx/mixins/fixtures.py
- tests/integration/framework/test_fixtures.py
Add RemoveAfter tag to additional artifacts
Add it as tag to:
- clusters
- instance pools
- sql warehouse
Add it a property to:
- schemas
- tables
Introduces #977
> [internal] Add RemoveAfter tag/property to additional testing artifacts

- src/databricks/labs/ucx/contexts/application.py
- src/databricks/labs/ucx/source_code/files.py
- src/databricks/labs/ucx/source_code/graph.py
- src/databricks/labs/ucx/source_code/whitelist.py
- tests/unit/source_code/test_dependencies.py
- tests/unit/source_code/test_files.py
- tests/unit/source_code/test_graph.py
- tests/unit/source_code/test_jobs.py
- tests/unit/source_code/test_path_lookup_simulation.py
- tests/unit/source_code/test_s3fs.py
Remove chain of import resolvers in favor of a single resolver.
Supersedes #1709 
Resolves #1707
> [internal] Simplify import resolvers

- pyproject.toml
- src/databricks/labs/ucx/config.py
- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/installer/policy.py
- src/databricks/labs/ucx/installer/workflows.py
- tests/integration/test_installation.py
- tests/unit/test_install.py
`upload_dependencies` flag has been added to WorkspaceConfig to upload dependencies to air-gapped workspaces. This flag is set by the user through the installation prompt.
Resolves #573
> Added ability to install UCX on workspaces without Public Internet connectivity

- .editorconfig
- Makefile
- pyproject.toml
This PR includes some trivial repository updates:
- An [EditorConfig](https://editorconfig.org) profile to set basic code formatting, set to match the files already in the repo. (IntelliJ/PyCharm should pick this up out of the box.)
- A warning when running the `make verify` target is eliminated.
- The `Makefile` targets are now marked as [phony](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html), which is more of a hygiene thing than anything else.
> EditorConfig specification for the project and minor tooling improvements

- src/databricks/labs/ucx/installer/workflows.py
- tests/unit/test_install.py
This PR fixes the issue when the upload_dependencies flag is set to True.
Currently the order of the library installation in each workflow task is
sdk-->blueprint-->lsql-->sqlglot-->ucx. 
Since lsql is dependent on sqlglot its failing in no internet workspaces.
This PR changes the order to below
sdk-->blueprint-->sqlglot-->lsql-->ucx. 
Resolves #1795
> Change order of Library installation when upload_dependencies flag is True

- src/databricks/labs/ucx/source_code/files.py
- src/databricks/labs/ucx/source_code/notebooks/sources.py
- tests/unit/source_code/notebooks/test_sources.py
- tests/unit/source_code/samples/nonascii.py
Fix linting non-utf8 encoded files. The linter and fixer would fail with non-utf8 encoded file
> Fix linting or fixing non-utf8 encoded files

- src/databricks/labs/ucx/source_code/jobs.py
- tests/integration/source_code/test_jobs.py
- tests/unit/source_code/test_jobs.py
> Added library linting for jobs launched on shared clusters

- src/databricks/labs/ucx/source_code/spark_connect.py
- tests/unit/source_code/test_spark_connect.py
Add new linters to check for uses of spark logging, `sc.conf` access and `rdd.mapPartitions` 
Resolves [#1805](https://github.com/databrickslabs/ucx/issues/1805), enhances [#1603](https://github.com/databrickslabs/ucx/issues/1603), [#1604](https://github.com/databrickslabs/ucx/issues/1604)
> Add linters to check for spark logging and configuration access

- src/databricks/labs/ucx/hive_metastore/view_migrate.py
- tests/unit/hive_metastore/test_table_migrate.py
> Fix issue when creating view using `WITH` clause

- src/databricks/labs/ucx/hive_metastore/grants.py
- tests/integration/hive_metastore/test_grants.py
- tests/unit/hive_metastore/test_grants.py
- In our legacy table ACLs, there are DENY operations. These permissions are shown with `DENIED` prefix. Apply them correctly when applying permissions for group migrations
Resolves #1803
> Handle legacy ACL `DENY` permission in group migration

- src/databricks/labs/ucx/source_code/jobs.py
- tests/integration/source_code/test_jobs.py
- tests/unit/source_code/test_jobs.py
This PR downloads a wheel dependency locally (in a temporary location) to register it to the dependency graph
Part of #1640
> Download wheel dependency locally to register it to the dependency graph

- src/databricks/labs/ucx/source_code/linters/pyspark.py
- tests/unit/source_code/linters/test_pyspark.py
This PR drops the 'register' lint matcher on the Spark context. This is being dropped because:
- The method is not on the Spark session, but is accessed via the `spark.udf`.
- The name argument is not the name of a table; rather it's the name of a (local) table function which doesn't pose a problem for migration.
Resolves #1779
> Drop pyspark 'register' lint matcher

- src/databricks/labs/ucx/installer/logs.py
- tests/unit/installer/test_logs.py
Handle parsing corrupted log files
Resolves #1763
> Handle parsing corrupted log files

- src/databricks/labs/ucx/source_code/known.py
- tests/unit/source_code/test_known.py
Improve the devex around `known.json`:
- Improve logging so that it's clearer what it's doing, in particular when there aren't any new distributions to scan.
- Handle building from scratch when `known.json` has been removed.
- Only rewrite the known.json file if it has changed.
- Use `importlib` instead of `pkgutil` when loading `known.json` (the latter is deprecated from python 3.12).
> Improve make known devex

- src/databricks/labs/ucx/source_code/jobs.py
- src/databricks/labs/ucx/source_code/linters/table_creation.py
- tests/unit/source_code/linters/test_table_creation.py
This pull request removes a spurious incompatible-format warning for `DataFrameWriter.insertInto()`. The `.insertInto()` operation uses the existing format of the underlying table; any specified format is ignored. As such use of this operation be flagged as a potential problem due to the change of the default format from `parquet` to `delta`.
Incidental changes included in this PR:
- Removed an unnecessary linting suppression.
> Remove false warning on DataFrame.insertInto() about the default format changing from parquet to delta

- src/databricks/labs/ucx/source_code/linters/spark_connect.py
- tests/unit/source_code/linters/test_spark_connect.py
- tests/unit/source_code/samples/functional/jvm-access.py
- tests/unit/source_code/samples/functional/rdd-apis.py
- tests/unit/source_code/samples/functional/spark-logging.py
- tests/unit/source_code/test_functional.py
This PR adds deduplication of errors emitted by Spark Connect linter. It also adds more functional tests using the new framework
> Deduplicate errors emitted by Spark Connect linter

- src/databricks/labs/ucx/source_code/jobs.py
- src/databricks/labs/ucx/source_code/path_lookup.py
- tests/integration/source_code/test_jobs.py
- tests/unit/source_code/test_jobs.py
- tests/unit/source_code/test_path_lookup.py
Support linting python wheel tasks
Resolves #1640
> Support linting python wheel tasks

- src/databricks/labs/ucx/hive_metastore/grants.py
- tests/integration/workspace_access/test_tacl.py
- tests/unit/workspace_access/test_tacl.py
- Legacy TACL migration logic currently grouped all permissions in a single `GRANT` statement. Split this into 2 separate statements, one for `DENY` and one for `GRANT`
- Added more unit tests, and added integration tests
> Further fix for DENY permissions

- tests/integration/test_installation.py
- tests/integration/workspace_access/test_groups.py
Fix test failure `test_delete_ws_groups_should_delete_renamed_and_reflected_groups_only`
Resolves #1830
Resolves #1841
> Fix test failure `test_delete_ws_groups_should_delete_renamed_and_reflected_groups_only`

- src/databricks/labs/ucx/mixins/fixtures.py
- tests/integration/hive_metastore/test_workflows.py
Fix test failure: `test_table_migration_job_refreshes_migration_status[regular-migrate-tables]` by adding a retry on `InvalidParameterValue` and waiting for provisioning of the mount created for testing. 
Resolves #1826
> Fix test failure: `test_table_migration_job_refreshes_migration_status[regular-migrate-tables]`

- src/databricks/labs/ucx/source_code/linters/dbfs.py
- src/databricks/labs/ucx/source_code/linters/imports.py
- src/databricks/labs/ucx/source_code/linters/pyspark.py
- src/databricks/labs/ucx/source_code/linters/python_ast.py
- tests/unit/source_code/linters/test_pyspark.py
- tests/unit/source_code/linters/test_python_ast.py
- tests/unit/source_code/samples/functional/file-access/direct-fs2.py
- tests/unit/source_code/samples/sys-path-with-fstring.py
- tests/unit/source_code/test_dependencies.py
Add support for f-strings not natively supported by astroid
Adjust existing linters accordingly
Works for simple f-strings such as:
```
a = "value"
some_function(f"some {a}")
```
but not for f-strings of f-strings such as:
```
a = "value"
b = f"some {a}"
some_function(f"{b} is better than none")
```
Resolves #1871 
Progresses #1205
> Infer simple f-string values when computing values during linting

- tests/integration/source_code/test_libraries.py
- tests/unit/source_code/samples/pip_install_multiple_packages.py
- tests/unit/source_code/samples/pip_install_pytest_with_index_url.py
Install pytest from https index url. Pip complained about the http link
> Install pytest from https index url instead for http in integration test

- CHANGELOG.md
- src/databricks/labs/ucx/__about__.py
* Fixed typo in `known.json` ([#1899](https://github.com/databrickslabs/ucx/issues/1899)). A fix has been implemented to correct a typo in the `known.json` file, an essential configuration file that specifies dependencies for various components of the project. The typo was identified in the `gast` dependency, which was promptly rectified by modifying an incorrect character. This adjustment guarantees precise specification of dependencies, thereby ensuring the correct functioning of affected components and maintaining the overall reliability of the open-source library.
> Release v0.27.1

- docs/assessment.md
- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/queries/assessment/main/35_0_grants.sql
- src/databricks/labs/ucx/queries/assessment/main/40___last_summary.md
- src/databricks/labs/ucx/queries/views/grant_detail.sql
- src/databricks/labs/ucx/queries/views/objects.sql
- tests/integration/conftest.py
- tests/integration/hive_metastore/test_grant_detail.py
- tests/integration/hive_metastore/test_grants.py
This PR adds support for flagging DENY permissions on objects, which cannot be migrated to UC.
It also adds some new integration tests for existing grant-scanning.
Resolves #1869, supersedes #1890.
> Include findings on `DENY` grants during assessment

- src/databricks/labs/ucx/queries/assessment/main/00_0_compatibility.sql
This PR modifies the dashboard to display N/A instead of NULL as the readiness during assessment startup when there isn't any data available yet.
> Dashboard: N/A instead of NULL readiness while assessment job hasn't yet provided any data

- tests/unit/source_code/linters/test_python_ast.py
> more inference tests

- tests/unit/test_install.py
Remove redundant state setting in test
> Remove redundant state setting in test

- src/databricks/labs/ucx/workspace_access/groups.py
- src/databricks/labs/ucx/workspace_access/workflows.py
- tests/unit/source_code/linters/test_python_imports.py
- tests/unit/workspace_access/test_workflows.py
This PR updates permission migration so that if an error occurs while migrating the permissions for a group it moves onto the next group instead of stopping immediately. Any errors are raised at the end instead.
At present the information about which groups succeeded and failed is logged but not persisted in any other way.
Progresses #1914.
> Group migration: continue permission migration even if one or more groups fails

- src/databricks/labs/ucx/azure/resources.py
This PR is stacked on #1943; it is stacked to verify the type hinting changes via the CI environment.
The situation is:
- The Databricks SDK has partially implemented type hints for the credentials handlers.
- The `CredentialsProvider` is the fundamental type for a callable factory that can be used to obtain credentials.
- The `CredentialsStrategy` is the type that can be used for a function that can be used to obtain a provider, given the `Config`.
- The `@credentials_strategy` decorator is used to fuse the two:
1. It decorates a function that, given a `Config`, returns a `CredentialsProvider`.
2. The decorated function that it returns is a `CredentialsStrategy`.
- The type upstream type hinting for the `@credentials_strategy` decorator is incomplete: the return type is omitted. This …
> Adjust type hints in credentials handling for Azure API client

- src/databricks/labs/ucx/workspace_access/groups.py
- tests/unit/workspace_access/test_groups.py
Renaming groups is eventually consistent. This PR updates the task that renames workspace groups so that it does not complete until the renaming is visible via direct get on the group and via group enumeration.
The integration tests already dealt with the eventual consistency problem, but downstream tasks in the workflow might also run into problems and this wasn't being handled. Ensuring that renaming has completed before the task prevents this from being an issue.
> Group renaming: wait for consistency before completing task

- src/databricks/labs/ucx/workspace_access/groups.py
- tests/unit/workspace_access/test_groups.py
Fix substituting regex with empty string
Resolves #1922
> Fix substituting regex with empty string

- src/databricks/labs/ucx/install.py
After successful workspace UCX installation, the installer fails with an Unauthenticated error if account admin credentials are not used. Handling the error with a warning to use the right account admin credentials and run cli command to join collection.
Resolves #1881
> Handle unauthenticated exception while joining collection

- README.md
- src/databricks/labs/ucx/mixins/fixtures.py
`make fmt` was picking this up. I don know why it just came up now, the change dates back to 16th of April
> Explain unused variable

- src/databricks/labs/ucx/source_code/jobs.py
Raise lint errors after persisting workflow problems to visualize the workflow problems which are known.
Part of resolving #1952
> Raise lint errors after persisting workflow problems in the inventory database

- src/databricks/labs/ucx/source_code/linters/imports.py
- src/databricks/labs/ucx/source_code/linters/pyspark.py
- src/databricks/labs/ucx/source_code/notebooks/cells.py
- tests/unit/source_code/samples/functional/file-access/direct-fs2.py
- tests/unit/source_code/samples/functional/missing-resolved-notebook.py
- tests/unit/source_code/samples/functional/pyspark/catalog/spark-catalog-cache-table.py
- tests/unit/source_code/samples/functional/pyspark/catalog/spark-catalog-create-external-table.py
- tests/unit/source_code/samples/functional/pyspark/catalog/spark-catalog-create-table.py
- tests/unit/source_code/samples/functional/pyspark/catalog/spark-catalog-get-table.py
- tests/unit/source_code/samples/functional/pyspark/catalog/spark-catalog-is-cached.py
- tests/unit/source_code/samples/functional/pyspark/catalog/spark-catalog-list-columns.py
- tests/unit/source_code/samples/functional/pyspark/catalog/spark-catalog-recover-partitions.py
- tests/unit/source_code/samples/functional/pyspark/catalog/spark-catalog-refresh-table.py
- tests/unit/source_code/samples/functional/pyspark/catalog/spark-catalog-table-exists.py
- tests/unit/source_code/samples/functional/pyspark/catalog/spark-catalog-uncache-table.py
- tests/unit/source_code/samples/functional/pyspark/dataframe-write-insert-into.py
- tests/unit/source_code/samples/functional/pyspark/dataframe-write-save-as-table.py
- tests/unit/source_code/samples/functional/pyspark/spark-table.py
- tests/unit/source_code/samples/functional/widgets.py
- tests/unit/source_code/test_dependencies.py
- tests/unit/source_code/test_notebook.py
use dedicated advice code for uncomputed values
None
None
> Use dedicated advice code for uncomputed values

- src/databricks/labs/ucx/source_code/notebooks/loaders.py
- src/databricks/labs/ucx/source_code/notebooks/sources.py
- tests/unit/source_code/notebooks/test_loader.py
- tests/unit/source_code/notebooks/test_sources.py
Handle missing permissions when reading files during linting
Resolves #1942
Partially resolves #1952
> Handle missing permission to read file

- pyproject.toml
- src/databricks/labs/ucx/source_code/base.py
- src/databricks/labs/ucx/source_code/linters/context.py
- src/databricks/labs/ucx/source_code/lsp_plugin.py
- tests/unit/source_code/linters/test_dbfs.py
- tests/unit/source_code/test_lsp_plugin.py
Add a PyLSP plugin entrypoint for UCX code linters. When a user has `python-lsp-server` installed, UCX will automatically register an LSP plugin on installation.
> Expose code linters as a LSP plugin

- src/databricks/labs/ucx/__init__.py
- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/runtime.py
- tests/unit/test_useragent.py
This PR adds `User-Agent` OtherInfo elements:
* `ucx/<version>` for all requests where UCX is imported as a library
* `cmd/install` for all installations/upgrades
* `cmd/<workflow>` for all managed job invocations
Relevant PRs:
- https://github.com/databrickslabs/lsql/pull/206
- https://github.com/databrickslabs/blueprint/pull/114
> Added tracking for UCX workflows and as-library usage

- README.md
This requirement has been taken care of as part of [#573](https://github.com/databrickslabs/ucx/issues/573).
> Removing the workspace network requirement info in README.md

- src/databricks/labs/ucx/workspace_access/manager.py
- tests/unit/workspace_access/test_manager.py
Avoid `AttributeError` error when exceptions without an `error_code` attribute are caught during the assessment job crawling permissions.
Resolves #2078 
- [ x] added unit tests
> Handle exceptions with no error_code attribute while crawling permissions

- src/databricks/labs/ucx/source_code/known.json
This PR fixes our `known.json` file to make it valid JSON: at present it won't load because of the presence of a trailing comma that renders it invalid JSON. (This was accidentally introduced by PR #2099.)
> Fix invalid JSON (`known.json`)

- .github/workflows/nightly.yml
- src/databricks/labs/ucx/hive_metastore/tables.py
- src/databricks/labs/ucx/mixins/fixtures.py
- tests/integration/conftest.py
- tests/integration/hive_metastore/test_grants.py
- tests/integration/hive_metastore/test_workflows.py
- tests/integration/source_code/test_jobs.py
- tests/integration/test_ext_hms.py
- tests/integration/test_installation.py
- tests/integration/test_runtime.py
- tests/unit/hive_metastore/test_tables.py
This PR adds ability to skip running tests with `modified_or_skip` fixture when none of the three conditions are met:
1. Debugger is running
2. `TEST_NIGHTLY` environment variable is present
3. `git diff` on current branch doesn't have a relevant file changed.
Use with care.
> Skip running certain integration tests when no relevant packages modified

- tests/integration/assessment/test_ext_hms.py
- tests/integration/hive_metastore/test_workflows.py
- tests/integration/install/test_installation.py
> Remove flaky tests

- src/databricks/labs/ucx/source_code/known.json
> whitelist dbignite

- src/databricks/labs/ucx/source_code/notebooks/cells.py
fix crasher when parsing unsupported magic syntax
None
None
Was discovered when running `make solacc`. Fixes 1 of the 2 issues.
> fix bug when parsing unsupported magic syntax

- src/databricks/labs/ucx/source_code/linters/python_ast.py
- tests/unit/source_code/linters/test_python_ast.py
Don't drop existing statements for globals when appending trees
None
None
Was discovered when running make solacc. Fixes 1 of the 2 issue. Other issue is fixed by #2157
> Fix infinite recursion when checking module of expression

- .github/workflows/no-cheat.yml
- tests/unit/no_cheat.py
- tests/unit/test_no_cheat.py
improve no-cheat CI check
Currently we get blocked when we change a line of code that already contains a cheat. 
For example, changing from:
`some_function("abc") # pylint: disable=some-code`
to:
`some_function("xyz") # pylint: disable=some-code`
triggers a no-cheat erroneously.
We want to avoid that, and also get better feedback on the new cheats.
The current script diffs the incoming branch with main, not the target branch. 
This PR changes that by using `$GITHUB_BASE_REF`.
The logic is too complex for bash, so delegating the analysis to python.
None
None
> improve no-cheat CI check

- tests/integration/assessment/test_jobs.py
From discussions it appears that some API calls incorrectly return a 400 instead of a 404. Adding InvalidParameterValue as a retry condition for test_job_run_crawler
Resolves #1887 
None
None
> tentatively fix test_job_run_crawler

- src/databricks/labs/ucx/hive_metastore/grants.py
log warning instead of error when this exception is raised
Resolves #1957 
None
Not tested
See comments in #1957 re the proposed resolution approach
> Fix "Table Access Control is not enabled on this cluster" error

- src/databricks/labs/ucx/source_code/known.json
Remove the lint message for DuckDB from `knownd.json` as it does not use Spark, nor does it change behavior based on the Databricks runtime. See [this comment](https://github.com/databrickslabs/ucx/pull/2134#discussion_r1674006987) for more context
> Remove DuckdbDB lint message from `known.json`

- .github/workflows/push.yml
- CONTRIBUTING.md
- pyproject.toml
- tests/unit/source_code/linters/test_files.py
> Test UCX over Python v3.10, v3.11, and v3.12

- src/databricks/labs/ucx/source_code/jobs.py
- tests/integration/source_code/test_jobs.py
Create DependencyProblem if job on runtime DBR14+ and using .egg dependency
Fix #1793
> Yield `DependencyProblem` if job on runtime DBR14+ and using .egg dependency

- tests/integration/source_code/test_jobs.py
Some of the integration tests for jobs request fixtures that they don't use; this PR removes them.
> Job integration tests: remove unused fixtures

- src/databricks/labs/ucx/queries/assessment/main/01_3_count_table_by_type_location_format.sql
New widgets gives table counts summary by type (external/managed), location (dbfs root/mount/cloud) and format (delta, parquet etc).
Introduces #1916
> Add new widget to get table count

- src/databricks/labs/ucx/source_code/jobs.py
- src/databricks/labs/ucx/source_code/path_lookup.py
- tests/integration/source_code/test_jobs.py
- tests/unit/source_code/test_jobs.py
This PR updates the way we track the tasks dependencies when assessing workflows; DBFS-located paths are now supported for:
- Wheels and eggs that a task depends on.
- The location of `requirements.txt` files that specify task dependencies.
- The location of PySpark jobs.
Resolves #1558.
- modified existing workflow: `assessment`
- added unit tests
> Added support for DBFS when building the dependency graph for tasks

- README.md
This PR updates the documentation to clarify that principal-prefix-access cli cmd for azure will only list abfss://  storage account. storage account used as adl:// or wasb:// will not be listed as those will not be used for credential migration
#1065 
Resolves #1552
> added doc to clarify that principal-prefix-access for azure will only list abfss storage accounts

- src/databricks/labs/ucx/source_code/python_libraries.py
- tests/unit/source_code/notebooks/test_cells.py
- tests/unit/source_code/test_jobs.py
- tests/unit/source_code/test_python_libraries.py
This PR disables Pip's built-in version check when using it to install dependencies. Pip itself is outside the control of UCX, and the version check often produces a lot of noise in the pip-related errors and finding messages.
- modified existing workflow: `...`
- manually tested
- unit tests
> Disable the builtin pip version check when running pip commands

- src/databricks/labs/ucx/workspace_access/groups.py
- tests/unit/workspace_access/test_workflows.py
This PR updates the format of the logged messages when permissions migration fails during the experimental group migration workflow.
The new format is as-suggested [here](https://github.com/databrickslabs/ucx/issues/1914#issuecomment-2233315439), although both the source and destination account names are mentioned (because they can be different).
Progresses #1914.
- modified existing workflow: `group-migration-experimental`
- added unit tests
> Group migration: change error logging format

- src/databricks/labs/ucx/source_code/python_libraries.py
Fix mypy flags `import distutils` in python 3.12. Local `make lint` fails with Python 3.12.
> Fix mypy flags `import distutils` in Python 3.12

- src/databricks/labs/ucx/source_code/graph.py
- src/databricks/labs/ucx/source_code/linters/files.py
- tests/integration/source_code/test_jobs.py
- tests/unit/source_code/linters/test_files.py
- tests/unit/source_code/test_dependencies.py
The current code lints local files without considering parent/child relationships (where a given 'parent' file imports or runs a 'child' file).
This makes it impossible to lint files in context, where a child file uses variables inherited from a parent file.
This PR is progress towards that, by linting child dependencies recursively.
Progresses #2155 
Progresses #2156
> Lint child dependencies recursively

- src/databricks/labs/ucx/source_code/graph.py
- src/databricks/labs/ucx/source_code/linters/files.py
- src/databricks/labs/ucx/source_code/notebooks/cells.py
- tests/unit/source_code/notebooks/test_cells.py
Rename `GraphBuilderContext` to `DependencyGraphContext` for clarity
This is in preparation of https://github.com/databrickslabs/ucx/pull/2236
Progresses https://github.com/databrickslabs/ucx/issues/2155
Progresses https://github.com/databrickslabs/ucx/issues/2156
None
> Rename `GraphBuilderContext` to `DependencyGraphContext` for clarity

- src/databricks/labs/ucx/source_code/base.py
- src/databricks/labs/ucx/source_code/graph.py
- src/databricks/labs/ucx/source_code/linters/files.py
- src/databricks/labs/ucx/source_code/linters/pyspark.py
- src/databricks/labs/ucx/source_code/linters/python_ast.py
- src/databricks/labs/ucx/source_code/linters/spark_connect.py
- src/databricks/labs/ucx/source_code/linters/table_creation.py
- src/databricks/labs/ucx/source_code/notebooks/cells.py
- tests/unit/source_code/linters/test_pyspark.py
- tests/unit/source_code/linters/test_python_ast.py
- tests/unit/source_code/notebooks/test_cells.py
Enhance python abstract syntax tree API in preparation of linting with inherited context
Move Tree static methods to TreeHelper class to avoid 'too many public methods' linting error
Progresses #2155 
Progresses #2156 
None
> enhance python abstract syntax tree API

- src/databricks/labs/ucx/workspace_access/groups.py
- tests/integration/conftest.py
- tests/integration/install/test_installation.py
- tests/integration/workspace_access/test_groups.py
- tests/unit/workspace_access/test_groups.py
This PR updates the group manager so that deleting workspace groups is more reliable. Changes include:
- We no longer skip deletion of groups that don't appear to be present. Due to eventual consistency issues this was occurring with groups that had recently been renamed (to their temporary name).
- Deletion now waits for the effects of deletion to be visible by double-checking that a group can no longer be directly retrieved from the API, and that it no longer appears in the list of groups during enumeration. (Due to API limitations this is not a guarantee that the groups are no longer visible, but it does decrease the likelihood of anything noticed afterwards.)
- Improved logging.
A subsequent PR will update group renaming to use a similar approach to that here.
Resolves #2227.
- …
> Group migration: improve robustness while deleting workspace groups

- tests/integration/source_code/solacc.py
Fix failing solacc
None
None
`make solacc` output:
INFO [verify-accelerators] Skipped: 9, parseable: 100% (1155/1155), missing imports: 213, not computed: 757
> fix failing solacc

- src/databricks/labs/ucx/contexts/workspace_cli.py
- src/databricks/labs/ucx/hive_metastore/migration_status.py
Don't fatally fail when loading data from `hive_metastore.migration_status` fails
Resolves #2221 
None
Not tested
> Tentatively fix failure when running assessment without a hive_metastore

- src/databricks/labs/ucx/installer/workflows.py
UCX manages all object dependencies via subclasses of `GlobalContext`. All UCX workflows use `RuntimeContext` instance for any object lookup, so this PR simplifies debugging by pre-initializing `RuntimeContext` the correct way.
> Init `RuntimeContext` from debug notebook to simplify interactive debugging flows

- src/databricks/labs/ucx/install.py
- tests/integration/install/test_installation.py
- tests/unit/install/conftest.py
- tests/unit/install/test_install.py
- tests/unit/install/test_install_dashboards.py
- tests/unit/test_install.py
Handle corrupted dashboard state in installation process. See linked issue for more details
Resolves #2261
> Handle corrupted dashboard state in installation process

- src/databricks/labs/ucx/installer/workflows.py
Recently, Astroid was added as a dependent library for UCX, but this was not included in upload_wheel_dependencies due to this assessment not running in a blocked workspace. This changes adds astroid to the dependent library
Resolves #2257
> adding astroid in the upload_dependencies

- src/databricks/labs/ucx/workspace_access/groups.py
- tests/unit/workspace_access/test_groups.py
This PR updates the way we check for the completion of group renames; similar to deletion we now double-check before assuming the rename has taken effect.
Follows on from #2247.
- modified existing workflows:
- `migrate-groups`
- `migrate-groups-experimental`
> Group migration: improve robustness when renaming groups

- tests/integration/conftest.py
This PR updates the `make_ucx_group()` fixture that creates a pair of workspace & account groups to include a purge suffix in the group name(s) if none is supplied. This ensures that the groups are not purged while the integration test is running.
> Integration tests: purge suffix for more group fixtures

- src/databricks/labs/ucx/config.py
- src/databricks/labs/ucx/install.py
- tests/unit/install/test_install.py
Fix dashboard queries fail when default catalog is not `hive_metastore` by always adding the `hive_metastore` namespace to the dashboard queries.
Resolves #2277
> Fix dashboard queries fail when default catalog is not `hive_metastore`

- tests/integration/conftest.py
- tests/unit/install/test_install_dashboards.py
This PR updates some of the unit-testing fixtures to mock `WheelsV2` where this is referenced instead of the real thing; this avoids lengthy wheel-building during unit tests.
(Wheel-building can easily exceed the 30s unit-testing deadline, especially on developer laptops with the solacc dataset present.)
> Mock WheelsV2 in unit-tests to avoid lengthy wheel-building.

- README.md
1. Fix broken #table-migration-workflow links in README. 
2. Add mermaid flow chart to demonstrate the table migration workflows.
> Fix broken table migration workflow links in README

- src/databricks/labs/ucx/source_code/notebooks/cells.py
- tests/unit/source_code/linters/test_python_imports.py
Filter out missing import problems for imports within a try-except clause with ImportError 
Resolves #1705 
None
> Filter out missing import problems for imports within a try-except clause with ImportError

- src/databricks/labs/ucx/queries/migration/groups/00_0_migration_overview.md
- src/databricks/labs/ucx/queries/migration/groups/01_0_group_migration_failures.md
- src/databricks/labs/ucx/queries/migration/groups/01_1_group_migration_failures.sql
This PR updates the dashboard for group migration:
- The documentation widgets have been adjusted.
- The failed-migration widget now displays formatted information about the failure, and links to the failed job run.
- Only failures from the latest workflow run (with logs) are displayed.
Improves upon #2333.
Relates to #1914.
- Updated dashboard: _UCX Migration (Groups)_
> Improve group migration error reporting

- src/databricks/labs/ucx/framework/utils.py
- src/databricks/labs/ucx/source_code/python_libraries.py
- tests/integration/source_code/test_libraries.py
- tests/unit/source_code/test_python_libraries.py
Current implementation only accepts a full command line, which it splits on spaces. This breaks when the command line contains arguments with spaces, such as `'some stuff'` (note the enclosing quotes)
The new implementation adds support for argument lists, which are passes 'as is' to `Popen`
Resolves #1859 
None
> Support spaces in run cmd args

- src/databricks/labs/ucx/install.py
Update TODO about dashboard installation retry on `InternalError` to be more descriptive and actionable.
Resolves #2172
Resolves #2173
Resolves #2198
> Update TODO about dashboard installation retry on `InternalError`

- src/databricks/labs/ucx/queries/migration/main/02_0_code_compatibility_problems.md
- src/databricks/labs/ucx/queries/migration/main/02_1_code_compatibility_problems.sql
In our Code Compatibility dashboard, this PR fixes two problems:
- The link to the workflow in the Markdown panel didn't have the correct #anchor; now it does.
- The links in the table widget to the workflow and task definitions was not being rendered correctly and therefore didn't work. Now they do.
- modified dashboard: _UCX Migration (Main)_
Before:
After:
> Code Compatibility Dashboard: Fix broken links

- pyproject.toml
- src/databricks/labs/ucx/hive_metastore/migration_status.py
- src/databricks/labs/ucx/source_code/base.py
- src/databricks/labs/ucx/source_code/linters/spark_connect.py
- src/databricks/labs/ucx/source_code/lsp_plugin.py
- tests/unit/source_code/linters/test_spark_connect.py
- tests/unit/source_code/samples/functional/spark-connect/catalog-api_13_3.py
- tests/unit/source_code/samples/functional/spark-connect/catalog-api_14_3.py
- tests/unit/source_code/samples/functional/spark-connect/command-context.py
- tests/unit/source_code/samples/functional/spark-connect/jvm-access.py
- tests/unit/source_code/samples/functional/spark-connect/python-udfs_13_3.py
- tests/unit/source_code/samples/functional/spark-connect/python-udfs_14_3.py
- tests/unit/source_code/samples/functional/spark-connect/rdd-apis.py
- tests/unit/source_code/samples/functional/spark-connect/spark-logging.py
- tests/unit/source_code/test_lsp_plugin.py
Make LSP linter plugin configurable with cluster information. This config can be provided either in a file or by a client and its provisioning is handled by pylsp infrastructure.
Spark Connect linter is now applied only to UC Shared clusters, as Single-User clusters are running in Spark Classic mode.
> Make ucx pylsp plugin configurable

- README.md
This PR fixes some typos in the project documentation for one of our workflows where we mistakenly referred to `create-missing-principals` as `create-missing-pricipals`.
> Fix documentation typos: `create-missing-pricipals` -> `create-missing-principals`

- src/databricks/labs/ucx/mixins/fixtures.py
This PR updates the cluster-policy fixtures created during integration tests so that they have the purge-time encoded as a suffix in their name. This will prevent the fixture from being removed while the test runs and causing spurious integration test failures.
Progresses: #2353
- integration tests
> Integration tests: mark cluster policy fixtures with a purge-suffix

- src/databricks/labs/ucx/mixins/fixtures.py
This PR simplifies the handling of the optional `spark_conf` and `libraries` arguments for the `make_job()` fixture used by integration tests.
- integration tests
> Tech debt: simplify handling of the `spark_conf` and `libraries` arguments for the `make_job` integration test fixture

- src/databricks/labs/ucx/workspace_access/base.py
Remove an internal `TODO` marker: it refers to #411, an issue which has been closed and won't be done.
> Remove `TODO` referring to #411 (won't do)

- src/databricks/labs/ucx/source_code/linters/pyspark.py
- tests/unit/source_code/linters/test_pyspark.py
- tests/unit/source_code/samples/functional/pyspark/catalog/spark-catalog-list-tables.py
Check originating module when linting for pyspark calls
None
None
> Avoid false positives when linting for pyspark patterns

- src/databricks/labs/ucx/source_code/jobs.py
- src/databricks/labs/ucx/source_code/linters/files.py
When linting jobs, the linting sequence was not consistent with the sequence of linting files i.e. root -> leaf, and did not provide inherited context. This PR ensures that linting is consistent across linting scenarios.
None
None
> Lint dependencies consistently

- src/databricks/labs/ucx/framework/crawlers.py
- tests/unit/hive_metastore/test_table_migrate.py
- tests/unit/hive_metastore/test_workflows.py
This PR updates the `.reset()` implementation for crawlers to use `TRUNCATE TABLE` instead of `DELETE FROM`. This is slightly more efficient and idiomatic (but not an issue of correctness).
> Crawlers: Use `TRUNCATE TABLE` instead of `DELETE FROM` when resetting crawler tables.

- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/hive_metastore/mapping.py
- src/databricks/labs/ucx/hive_metastore/tables.py
- tests/integration/hive_metastore/test_migrate.py
- tests/integration/hive_metastore/test_tables.py
- tests/unit/hive_metastore/test_mapping.py
- tests/unit/test_cli.py
Add support for skipping views when migrating tables and views
Resolves #1937
> Add support for skipping views when migrating tables and views

- tests/integration/hive_metastore/test_migrate.py
Use `load_table` instead of deprecated `is_view` in failing integration test `test_mapping_skips_tables_databases`
Resolves #2410 2410
> Use `load_table` instead of deprecated `is_view` in failing integration test `test_mapping_skips_tables_databases`

- src/databricks/labs/ucx/aws/access.py
- src/databricks/labs/ucx/azure/access.py
- tests/unit/aws/test_access.py
- tests/unit/azure/test_access.py
1. Fix `InvalidParameterValue: Endpoint security policy is required and must be one of NONE, DATA_ACCESS_CONTROL, PASSTHROUGH.` error in #2405 
2. Print new SQL warehouse data access config in the log when `databricks.sdk.errors.platform.InvalidParameterValue: enable_serverless_compute is required.` error in #2405 occurs. With that users can manually copy paste the config in UI to finish setting up the uber principal,
> Fix missing `security_policy` when updating SQL warehouse config

- src/databricks/labs/ucx/azure/access.py
- src/databricks/labs/ucx/azure/resources.py
- tests/integration/azure/test_access.py
- tests/integration/azure/test_resources.py
- tests/unit/azure/__init__.py
- tests/unit/azure/azure/mappings.json
- tests/unit/azure/test_access.py
- tests/unit/azure/test_resources.py
- tests/unit/test_cli.py
Clean up the resources created for the Azure uber principal if the creation fails (half way).
Partially resolves #2360 (the azure part)
Resolves #2363
> Clean up left over uber principal resources for Azure

- src/databricks/labs/ucx/hive_metastore/table_size.py
- tests/unit/hive_metastore/test_table_size.py
When performing table size, we are getting exception for table with DELTA_INVALID_FORMAT , this PR converts the error to a warning and proceeds with rest of the table
Resolves #1913
> Bug: Generate custom warning when doing table size check and encountering DELTA_INVALID_FORMAT exception

- src/databricks/labs/ucx/install.py
During installation, if there is an error due to external metastore connectivity, the installation raises an exception which may be confusing. This PR raises a custom exception msg and points user to the installation instruction for UCX to ext metastore.
Resolves #1967 
Tested by trying to install the ucx on a workspace with incorrect ext metastore connectivity
> Generate custom error during installation due to external metastore connectivity issues

- src/databricks/labs/ucx/hive_metastore/table_move.py
- tests/integration/hive_metastore/test_table_move.py
Table fails with [DELTA_CREATE_TABLE_WITH_DIFFERENT_PROPERTY] during move but the source table is already dropped. Dropping table is moved after the new table creation so that the process fails if there are issues during creation and the source table is preserved
Resolves #2424
> Drop source table after successful table move not before

- src/databricks/labs/ucx/__init__.py
Fix #2447
Fix #2446
Fix #2445
Fix #2444
Fix #2443
Fix #2442
Fix #2441
Fix #2440
Fix #2439
Fix #2438
Fix #2437
Fix #2436
Fix #2435
Fix #2434
Fix #2433
Fix #2432
> [internal] Fixed User-Agent error caused by SDK regression

- src/databricks/labs/ucx/aws/access.py
- tests/unit/aws/test_access.py
When running create-missing-credential, code is trying to match locations with uc_roles_access.csv entries.
If a role is already created, running the command tries the create the role again. due to the line of code here
path = PurePath(external_location.location)
matching_role = False
for role in compatible_roles:
if path.match(role.resource_path):
Ex:
path = PurePath(“s3://labs-things/a/b/”)
path.match(“s3://labs-things”)
the above code returns False, when it should be True due to which its trying to create the role again.
changed it to use location.startswith()
#2336 
Resolves #2413
> Fix issue when running create-missing-credential cmd tries to create the role again if already created

- src/databricks/labs/ucx/installer/policy.py
This PR increases the min memory of the workflow job from 16GB to 32GB, this is to avoid driver crashes during assessment run
Resolves #2398
> Fix Driver OOM error by increasing the min memory requirement for node from 16GB to 32 GB

- src/databricks/labs/ucx/source_code/base.py
> Make lint log references clickable

- src/databricks/labs/ucx/aws/access.py
- src/databricks/labs/ucx/aws/credentials.py
- tests/integration/aws/test_access.py
- tests/unit/aws/test_access.py
create-missing-principals does not enforce role uniqueness on AWS. Add a method to generate role name.
Resolves #2336
> Appends metastore_id or location_name to roles for uniqueness

- src/databricks/labs/ucx/installer/workflows.py
Changes the security mode of the assessment 'main' cluster.
LEGACY_SINGLE_USER_STANDARD does not have passthrough enabled.
Resolves #1717
> Changes the security mode for assessment cluster

- labs.yml
- src/databricks/labs/ucx/azure/resources.py
- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/install.py
- tests/unit/__init__.py
- tests/unit/test_cli.py
- tests/unit/test_collection.py
This PR enables principal-prefix-access to run as a collection. It also wraps common functionalities into get_workspace_context function.
https://github.com/user-attachments/assets/a82eecb7-50b9-4afe-832a-979bd641bdf1
#1782
> Enable `principal-prefix-access` command to run as collection

- tests/integration/hive_metastore/test_migrate.py
Verify last added privilege. CI failed before: https://github.com/databrickslabs/ucx/actions/runs/10596452524/job/29364449153?pr=2499
> Fix failing test `test_migrate_managed_tables_with_acl`

- src/databricks/labs/ucx/source_code/graph.py
- src/databricks/labs/ucx/source_code/jobs.py
- src/databricks/labs/ucx/source_code/linters/files.py
There is redundant code for walking a dependency graph 'properly' i.e. from roots to leaves, populating python globals etc...
This PR makes it trivial to reuse the correct code, and reuses it for local code linting and jobs linting.
This will also be used by #2371 
None
None
> Implement dependency graph walker

- tests/integration/hive_metastore/test_migrate.py
Filter the grant created for the test user instead of assuming it to be the last grant.
Resolves #2511
> Fix `test_migrate_managed_tables_with_acl` by filtering the grant created for the test user

- src/databricks/labs/ucx/hive_metastore/grants.py
- tests/unit/hive_metastore/test_grants.py
Improve log warning about skipped grants. Missing information when verifying ucx behavior of ACL migration
> Improve log warning about skipped grants

- src/databricks/labs/ucx/source_code/linters/python_ast.py
- tests/integration/source_code/test_jobs.py
- tests/unit/azure/test_credentials.py
- tests/unit/mixins/test_cached_workspace_path.py
- tests/unit/source_code/linters/test_files.py
This PR fixes some warnings at build-time that are produced by our `mypy`/`pylint`/`pytest` tooling:
- Pylint warnings due to unnecessary suppressions. (Removed.)
- Mypy warnings about bodies with hints not being linted. (Now they are.)
- Pytest warnings about not being able to collect tests. (Now it doesn't try.)
> Fix various `mypy`/`pylint`/`pytest` build warnings

- src/databricks/labs/ucx/hive_metastore/locations.py
- tests/unit/hive_metastore/test_locations.py
This PR removes the `Mounts.inventorize_mounts()` method; it was only used by unit tests that could use the `.snapshot()` API instead. This was noted as part of #2404, and is part of general cleanup of patterns we use for the crawlers:
https://github.com/databrickslabs/ucx/blob/68ecb02df0f02fcef1b5dc44a8421ccf480431c6/src/databricks/labs/ucx/hive_metastore/locations.py#L240
Relates to #2404.
> Remove unnecessary crawler API: `Mounts.inventorize_mounts()`

- README.md
- labs.yml
- src/databricks/labs/ucx/cli.py
- tests/unit/test_cli.py
Add a `download` cli command to download file from a collection of workspaces.
Progresses #1783
>  Add `download` cli command to download file from a collection of workspaces

- tests/integration/workspace_access/test_groups.py
This PR updates an integration test that started failing after the Databricks 0.32.0 release. In this test we check the error message associated with an expected failure, but the message changed with the new version of the SDK so the test now fails.
_Note: This is probably a bug introduced in the upstream SDK release._ For a call to `ws.groups.get(id)` where the ID doesn't exist:
- Previously we would get the message: `Group with id $ID not found.`
- As of the new release we get: `None request failed`
Resolves #2539.
- updated integration test
> Bugfix: `test_delete_ws_groups_should_delete_renamed_and_reflected_groups_only`

- src/databricks/labs/ucx/framework/utils.py
- src/databricks/labs/ucx/recon/base.py
- src/databricks/labs/ucx/recon/migration_recon.py
- tests/unit/framework/test_utils.py
Following on from #2485, this PR:
- Updates a missed SQL statement in one of the crawlers where the identifiers should be escaped.
- Adds in a missing (and not well known) corner-case for the escaping of identifiers: Spark/Databricks supports backticks in the names of identifiers, and these need to be doubled when quoting in the same manner as single-quotes in SQL strings.
- Updates SQL escaping for the same thing in another part of the code where the same thing is done in the `migrate-data-reconciliation` workflow when working with the workspace resources.
Follows #2485.
- modified existing workflow: `migrate-data-reconciliation`
> More escaping of SQL identifiers

- src/databricks/labs/ucx/installer/workflows.py
Retry deploy workflow on `InternalError` to improve resilience of deploying workflow, e.g. failed https://github.com/databrickslabs/ucx/actions/runs/10676861894
Resolves #2522
> Retry deploy workflow on `InternalError`

- README.md
Following on from some discussions yesterday, this PR updates the project document to clarify that the `assessment` job is only intended to be run once and should not be re-run to refresh the inventory and/or findings. The intent is that UCX should be reinstalled first if the assessment needs to be re-run.
As part of #2074 a new (daily) job will be introduced that refreshes parts of the inventory; however the `assessment` job will remain as-is. (These documentation changes are intended to reflect the status quo.)
- updated user documentation
> Document: clarify that the `assessment` job is not intended to be re-run.

- src/databricks/labs/ucx/installer/workflows.py
pip install wheel is surrounded by [ ] which fails the notebook run. 
Quick fix
> Fixes pip install statement in debug notebook

- src/databricks/labs/ucx/aws/access.py
- src/databricks/labs/ucx/installer/mixins.py
- tests/unit/aws/test_access.py
- tests/unit/install/test_install.py
Uses PermissionDenied instead of PermissionError for handling Databricks' object errors
Resolves #2407 
Used existing tests
> Uses PermissionDenied instead of PermissionError

- src/databricks/labs/ucx/contexts/application.py
- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/installer/workflows.py
- tests/integration/conftest.py
- tests/unit/install/test_install.py
- tests/unit/install/test_install_dashboards.py
- tests/unit/installer/test_workflows.py
Since the attribute is not used except in the repair_run method, refactoring accordingly.
Resolves #2383
> Refactors verify_timeout property on DeployedWorkflows

- src/databricks/labs/ucx/source_code/graph.py
- tests/integration/source_code/test_graph.py
- tests/unit/source_code/samples/import-sqlglot.py
- tests/unit/source_code/test_graph.py
- tests/unit/source_code/test_notebook.py
- tests/unit/source_code/test_path_lookup_simulation.py
When visiting a dependency graph, infinite recursion can happen.
For example, many files in sqlglot package import sqlglot itself
When visiting the graph with a 'visited' set, this is naturally prevented.
However, when computing dependency roots, we can't have a 'visited' set.
This PR fixes the issue by only visiting once parent/child pairs 
Progresses #2350 (PR #https://github.com/databrickslabs/ucx/pull/2526 blocked by this bug)
None
n.b. this PR also drops a test method to avoid a pylint `too-many-methods` error
> Fix infinite recursion when visiting a dependency graph

- tests/integration/hive_metastore/test_migrate.py
Fix schema collision in `test_migrate_table_in_mount` by suffixing a random name
Resolves #2569
> Fix schema collision in `test_migrate_table_in_mount`

- src/databricks/labs/ucx/framework/crawlers.py
- src/databricks/labs/ucx/hive_metastore/grants.py
- src/databricks/labs/ucx/hive_metastore/locations.py
- src/databricks/labs/ucx/hive_metastore/workflows.py
- tests/integration/conftest.py
- tests/unit/assessment/test_clusters.py
- tests/unit/assessment/test_init_scripts.py
- tests/unit/assessment/test_jobs.py
- tests/unit/assessment/test_pipelines.py
- tests/unit/framework/test_crawlers.py
- tests/unit/hive_metastore/test_locations.py
- tests/unit/workspace_access/test_manager.py
This PR updates the crawler internals so that when requesting a snapshot a refresh can be forced. In addition, the default semantics for crawlers have been updated so that they use an overwrite operation to write the data rather than appending (with the assumption that the table is already empty).
- Progresses: #2074
- Resolves: #2576
- Closes: #2597
- modifies all existing crawlers
> Crawler snapshots: allow refreshing

- tests/integration/workspace_access/test_groups.py
Fix failing integration test `test_reflect_account_groups_on_workspace_skips_groups_that_already_exists_in_the_workspace` by waiting for the groups used for testing to be provisioned (instead of in the process of being provisioned).
Resolves #2559
> Fix failing integration test `test_reflect_account_groups_on_workspace_skips_groups_that_already_exists_in_the_workspace`

- src/databricks/labs/ucx/workspace_access/groups.py
- tests/integration/workspace_access/test_groups.py
Also check for **workspace** groups to exists with the same name. Follow up on #2615
In hindsight, what might have happened before: the workspace group was not created before the account group was reflected in the workspace, thus the test passes. With the changes in PR #2615, we got more consistent behaviour because we wait for the workspace group to exists before running the to-be-tested code. However, the code did not handle that situation. This PR handles when a workspace group has the same name as an to-be-reflected-in-the-workspace account group
Resolves #2623
> Fix failing integration test: `test_reflect_account_groups_on_workspace_skips_groups_that_already_exists_in_the_workspace`

- src/databricks/labs/ucx/install.py
Lower chance on failing install `test_running_real_assessment_job_ext_hms` by retrying on `InternalError`
Resolves #2620
> Retry create database on `InternalError`

- tests/integration/workspace_access/test_workflows.py
Fix test integration failure: `test_running_real_migrate_groups_job` by waiting for the test group to be provisioned. Also the test assert failure is improved by first checking if the group is found.
Resolves #2628
> Fix test integration failure: `test_running_real_migrate_groups_job` 

- tests/integration/account/test_account.py
- tests/integration/framework/test_fixtures.py
This PR updates two integration tests that were using a fixed name for the fixture objects that they create. These can sometimes (spuriously) fail due to concurrent test runs against the same infrastructure.
- updated integration tests
> Integration test reliability: update some tests to ensure they use unique group names

- labs.yml
- src/databricks/labs/ucx/cli.py
- tests/unit/test_cli.py
Let `validate-groups-membership` command to run as collection
Resolves #2613
> Let `validate-groups-membership` command to run as collection

- labs.yml
- src/databricks/labs/ucx/cli.py
- tests/unit/test_cli.py
Let `migrate-dbsql-dashboards` command to run as collection
Resolves #2612
> Let `migrate-dbsql-dashboards` command to run as collection

- labs.yml
- src/databricks/labs/ucx/cli.py
- tests/unit/test_cli.py
Let `migrate-tables` command to run as collection
Resolves #2610
> Let `migrate-tables` command run as collection

- labs.yml
- src/databricks/labs/ucx/aws/locations.py
- src/databricks/labs/ucx/azure/locations.py
- src/databricks/labs/ucx/cli.py
- tests/unit/test_cli.py
Let `validate-external-locations` command to run as collection
Resolves #2608
> Let `migrate-locations` command run as collection

- src/databricks/labs/ucx/source_code/base.py
- src/databricks/labs/ucx/source_code/graph.py
- src/databricks/labs/ucx/source_code/notebooks/cells.py
- src/databricks/labs/ucx/source_code/notebooks/sources.py
- src/databricks/labs/ucx/source_code/python/python_analyzer.py
- tests/unit/source_code/test_base.py
- tests/unit/source_code/test_s3fs.py
Our code implements 'replace' methods on some dataclasses with no benefit over the builtin method.
This PR fixes that.
None
None
> Drop replace methods with builtin

- src/databricks/labs/ucx/contexts/workspace_cli.py
- src/databricks/labs/ucx/source_code/linters/files.py
- tests/integration/source_code/test_jobs.py
- tests/unit/source_code/linters/test_files.py
LocalCodeLinter is unable to normalize python code at notebook cell level
This PR fixes the issue
None
None
> Fix failing solution accelerator verification tests

- src/databricks/labs/ucx/assessment/workflows.py
This PR updates the way UDFs are crawled/scanned during the `assessment` workflow:
- Prior to this PR the UDFs are crawled/scanned implicitly by the `GrantsCrawler`: it requests a snapshot from the `UDFSCrawler` but that hasn't executed prior to this point in the workflow.
- With this PR, the UDFs are crawled/scanned as their own task in parallel with tables before grants crawling commences.
Progresses #2574, where grants and UDFs need to be refreshable but only once within a given workflow run.
- modified existing workflow: `assessment`
> Assessment: crawl UDFs as a task in parallel to tables instead of implicitly during grants

- src/databricks/labs/ucx/source_code/jobs.py
Blueprint 0.8.3 implements path.stat() for workspace paths.
This PR removes the corresponding workaround
None
None
> drop workspace path.stat() workaround

- tests/integration/install/test_installation.py
Increase timeout of inner task
Resolves #2639 
None
> fix test_running_real_remove_backup_groups_job timeout

- labs.yml
- src/databricks/labs/ucx/cli.py
- tests/unit/test_cli.py
Let `migrate-acls` command to run as collection
Resolves #2611
> Let `migrate-acls` command run as collection

- labs.yml
- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/hive_metastore/catalog_schema.py
- tests/unit/test_cli.py
Let `validate-external-locations` command to run as collection
Resolves #2609
> Let `create-catalog-schemas` command run as collection

- labs.yml
- src/databricks/labs/ucx/cli.py
- tests/unit/test_cli.py
Let `validate-external-locations` command to run as collection
Resolves #2607
> Let `validate-external-locations` command run as collection

- labs.yml
- src/databricks/labs/ucx/azure/access.py
- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/contexts/application.py
- src/databricks/labs/ucx/contexts/workspace_cli.py
- tests/unit/test_cli.py
Let `create-uber-principal` command run on a collection of workspaces.
Resolves #2605
> Let `create-uber-principal` command run on collection of workspaces

- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/queries/views/directfs.sql
- src/databricks/labs/ucx/source_code/directfs_access.py
- src/databricks/labs/ucx/source_code/jobs.py
- src/databricks/labs/ucx/source_code/queries.py
- tests/integration/source_code/test_jobs.py
- tests/unit/source_code/test_directfs_access.py
Current code implements DirectFsAccessInPath with fields conveying data already present in the source_lineage field.
This PR simplifies the code by dropping this specialization
Relates to #2350
> Simplify DirectFsAccess storage

- README.md
- labs.yml
- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/contexts/workspace_cli.py
- tests/integration/conftest.py
- tests/unit/test_cli.py
- tests/unit/test_factories.py
Support multiple subscription ids for `create-uber-principal` command. See linked issue for motivation
Resolves #2645
> Support multiple subscription ids for command line commands

- labs.yml
- src/databricks/labs/ucx/cli.py
- tests/unit/test_cli.py
This PR enables create-missing-principals command to run as a collection.
Linked issues
https://github.com/databrickslabs/ucx/issues/1782
Resolves #2606
> Added ability to run create-missing-principals command as collection

- tests/integration/assessment/test_assessment.py
[Pytester](https://github.com/databrickslabs/pytester) adopted return type `WorkspacePath` for `make_notebook` Changes for `make_notebook` fixture applied in this PR
Resolves #2670
> Fix test failure: `test_workspace_object_crawler`

- src/databricks/labs/ucx/hive_metastore/tables.py
- tests/unit/hive_metastore/test_tables.py
This PR updates the code in the new Py4J-based table crawler that is used to describe tables. Changes include:
- Improved logging, including the python backtrace when an error occurs on the JVM side of the bridge.
- Each table property is now fetched over the bridge on its own line, to help pinpoint the origin of errors that occur.
- Fixes to unboxing the Scala `Option` values. (We now use a technique which only calls simple Scala methods.)
- A small optimization when detecting if a table is partitioned: instead of materialising the collection we just check if it's non-empty.
- The table's `.viewText()` property is properly handled as a Scala `Option`.
- Explicitly verify that the supplied `catalog` argument is `hive_metastore`: that's the only value that is supported.
Follows on from …
> Fast table crawler: suggestions/fixes for describing tables

- tests/integration/install/test_installation.py
- tests/integration/workspace_access/test_groups.py
Verify the "remove-workspace-local-backup-groups" finished successfully before checking the group was deleted
(Hopefully) Resolves #2691. The eventual consistency of the groups API makes testing difficult.
> Fix test failure: `test_running_real_remove_backup_groups_job`

- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/hive_metastore/mapping.py
🔧 This is still in progress...
Resolves #1938
> Adding unskip CLI command to undo a skip on schema or a table

- tests/integration/assessment/test_ext_hms.py
- tests/integration/assessment/test_workflows.py
- tests/integration/conftest.py
Ensure 'assessment' workflow only runs minimal assessment in integration tests
None
None
> Fix failing integration tests that perform a real assessment

- README.md
Updated the doc to explain the concept of collection and how to use the join-collection cmd and the related collection-eligible commands
> Update documentation to explain the usage of collections and eligible commands

- README.md
- labs.yml
- src/databricks/labs/ucx/account/metastores.py
- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/config.py
- src/databricks/labs/ucx/contexts/account_cli.py
- src/databricks/labs/ucx/contexts/application.py
- src/databricks/labs/ucx/contexts/workspace_cli.py
- src/databricks/labs/ucx/hive_metastore/catalog_schema.py
- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/source_code/queries.py
- tests/integration/conftest.py
- tests/integration/hive_metastore/test_catalog_schema.py
- tests/unit/account/test_metastores.py
- tests/unit/conftest.py
- tests/unit/hive_metastore/test_catalog_schema.py
- tests/unit/install/test_install.py
- tests/unit/source_code/test_queries.py
- tests/unit/test_cli.py
- tests/unit/test_config.py
Add `create-ucx-catalog` cli command to create the catalog (going to be) used for migration tracking (possibly) accross multiple workspaces.
Resolves #2571
> Add `create-ucx-catalog` cli command

- src/databricks/labs/ucx/source_code/linters/from_table.py
- tests/integration/hive_metastore/test_migrate.py
- tests/unit/hive_metastore/test_view_migrate.py
The alias for the source table is disappearing while converting the create view sql from legacy hive metastore to uc catalog.
Resolves #2661
> Fixes source table alias dissapearance during migrate_views

- src/databricks/labs/ucx/assessment/secrets.py
- tests/unit/assessment/test_secrets.py
Harden configuration reading by verifying the type before reading the "value" using `.get`
Resolves #2581 (hopefully the second get is the issue, type hinting should cover that, but who knows)
> Harden configuration reading

- README.md
- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/hive_metastore/mapping.py
- tests/unit/hive_metastore/test_mapping.py
Add unskip CLI command to undo a skip on schema or a table 
Resolves #1938
> Add unskip CLI command to undo a skip on schema or a table 

- src/databricks/labs/ucx/source_code/base.py
- tests/integration/source_code/solacc.py
`solacc` currently lints on a per-file basis, which is incorrect
this PR implements linting a per solution basis, thus improving dependency resolution
None
None
> Improve solacc linting

- src/databricks/labs/ucx/source_code/base.py
- tests/integration/source_code/solacc.py
Current implementation clones all `solacc` repos at once, occupying 1.5g which brings us close to limits in CI
This PR fixes that by cloning repos 1 by 1 and deleting them once linting is done
None
None
> Clone solacc repos 1 by 1 and delete them once linting is done

- docs/table_persistence.md
This PR adds updates the table utilization table:
- Missing linter tables.
- Since #2678 the assessment workflow also writes to `workflow_problems`.
> Documentation: table utilization updates

- src/databricks/labs/ucx/source_code/notebooks/cells.py
- tests/integration/source_code/test_cells.py
Current implementation fails when pip command is preceded by non MAGIC comments
This PR fixes the issue
None
None
> strip preliminary comments in pip cells

- README.md
- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/contexts/workflow_task.py
- src/databricks/labs/ucx/contexts/workspace_cli.py
- src/databricks/labs/ucx/framework/tasks.py
- src/databricks/labs/ucx/installer/workflows.py
- src/databricks/labs/ucx/progress/install.py
- src/databricks/labs/ucx/progress/workflow_runs.py
- src/databricks/labs/ucx/progress/workflows.py
- tests/integration/conftest.py
- tests/integration/progress/test_install.py
- tests/integration/progress/test_workflow_runs.py
- tests/integration/progress/test_workflows.py
- tests/unit/progress/test_install.py
- tests/unit/progress/test_workflow_runs.py
- tests/unit/test_cli.py
Add and populate workflow runs table
Resolves #2600
> Add and populate UCX `workflow_runs` table

- src/databricks/labs/ucx/source_code/known.json
> Whitelists dataclasses-json

- tests/unit/source_code/python/test_python_ast.py
Increase test coverage
None
None
> Increase test coverage

- tests/unit/hive_metastore/test_table_size.py
Failed in [this CI](https://github.com/databrickslabs/ucx/actions/runs/11160366280/job/31020685817?pr=2807)
> Fix failure: `test_table_size_crawler`

- src/databricks/labs/ucx/contexts/application.py
- src/databricks/labs/ucx/source_code/used_table.py
- tests/unit/contexts/test_application.py
Fix missing arguments to `WorkflowLinter`
Resolves #2808
> Fix missing arguments to `WorkflowLinter`

- src/databricks/labs/ucx/source_code/known.json
> Added `confection` library to known list

- src/databricks/labs/ucx/account/aggregate.py
- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/contexts/account_cli.py
- src/databricks/labs/ucx/contexts/application.py
- src/databricks/labs/ucx/contexts/workflow_task.py
- src/databricks/labs/ucx/contexts/workspace_cli.py
- src/databricks/labs/ucx/hive_metastore/locations.py
- src/databricks/labs/ucx/hive_metastore/tables.py
- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/source_code/known.py
- src/databricks/labs/ucx/source_code/python_libraries.py
- src/databricks/labs/ucx/workspace_access/generic.py
- tests/integration/conftest.py
Add type hints for cached properties and resolve the linting issues found after adding the type hints. Would have caught the integration test issues introduced in #2772
> [TECH DEBT] Add type hints for cached properties

- src/databricks/labs/ucx/contexts/application.py
- src/databricks/labs/ucx/source_code/queries.py
- tests/integration/source_code/test_queries.py
- tests/unit/source_code/test_queries.py
Similarly to what is done for workflows, collect used tables as part of running report
None
> collect used tables as part of running report

- tests/integration/workspace_access/test_permissions_manager.py
- tests/unit/__init__.py
- tests/unit/account/test_aggregate.py
- tests/unit/conftest.py
- tests/unit/hive_metastore/test_migrate_acls.py
- tests/unit/hive_metastore/test_table_migrate.py
- tests/unit/recon/test_migration_recon.py
- tests/unit/test_collection.py
This PR introduces a `ws` fixture for the unit tests, and refactors some of the existing unit tests that were using their own custom fixtures.
We now have an upstream dependency (`pytester`) that provides a fixture of the same name, but it is intended for use with integration tests. Without `ws` as part of the local `conftest.py` for unit tests it is easy to inadvertently inject the upstream fixture (which doesn't work as intended.)
> Unit test updates: workspace client fixture (`ws`)

- tests/integration/source_code/test_jobs.py
`greenlit` library is added to the known list in #2830, thus not unknown anymore
Resolves #2845
Resolves #2844
> Replace `greenlit` with unknown library in integration tests

- src/databricks/labs/ucx/hive_metastore/locations.py
- src/databricks/labs/ucx/hive_metastore/tables.py
- src/databricks/labs/ucx/queries/assessment/main/10_0_database_summary.sql
- src/databricks/labs/ucx/queries/assessment/main/10_1_all_tables.sql
- src/databricks/labs/ucx/queries/views/objects.sql
- src/databricks/labs/ucx/queries/views/table_estimates.sql
- tests/unit/hive_metastore/test_locations.py
- tests/unit/hive_metastore/test_tables.py
Make delta format case sensitive
Resolves #2858
Relevant to #2840
> Make delta format case sensitive

- src/databricks/labs/ucx/contexts/workflow_task.py
- tests/integration/assessment/test_ext_hms.py
- tests/integration/assessment/test_workflows.py
- tests/integration/conftest.py
- tests/integration/progress/test_workflows.py
Scope resources to run the assessment workflow for in integration tests to shorten the time it takes for the assessment to run:
- Move the populate for linting logic to the context
- Set the `include_job_ids` to the job ids created by the populate for linting logic
- Set the `include_dashboard_ids` to the dashboard ids created by the populate for linting logic
- Move the create job based on Python file fixture to [pytester](https://github.com/databrickslabs/pytester/pull/60)
Resolves #2637
Resolves #2849
- `test_running_real_assessment_job`
- `test_running_real_assessment_job_ext_hms`
- `test_running_real_migration_progress_job`
> Limit resources to assess in integration tests that run the `assessment` workflow

- pyproject.toml
This PR updates the minimum required version of `pytester` from 0.2.1 to 0.3.0. As of #2852 our integration tests depends on changes introduced in databrickslabs/pytester#60 (and released with 0.3.0).
> Upgrade minimum required version of `pytester`: 0.2.1 → 0.3.0

- src/databricks/labs/ucx/account/workspaces.py
- tests/unit/account/test_workspaces.py
Handle `PermissionDenied` when retrieving `WorkspaceClient`s from account
Resolves #2874
> Handle `PermissionDenied` when retrieving `WorkspaceClient`s from account

- tests/integration/source_code/test_jobs.py
This PR updates some linting related integration tests that weren't testing what they expected:
- The tests were intending to verify linting of notebooks, and set up a notebook with code to trigger a linting record.
- The linting code was failing prematurely due to the notebook extension, not due to the problem in source.
Some usage of `greenlet` has also been replaced: it was previously unknown to the linter and various integration tests assumed this. Since #2830 these tests have no longer been working correctly.
Overlaps with #2852.
Overlaps with #2867.
Overlaps with #2868.
Resolves #2843.
Resolves #2844.
Resolves #2845.
Resolves #2846.
> Update linter integration tests to ensure notebook source is linted

- tests/integration/conftest.py
- tests/integration/hive_metastore/test_migrate.py
- tests/integration/hive_metastore/test_table_move.py
Replace hard-coded dir name with random one
Resolves #2797 
None
> Avoid resource conflicts in integration tests by using a random dir name

- tests/integration/framework/test_owners.py
This updates an integration test to more thoroughly verify that we can locate the user-name of an administrator.
Follows: #2774
- updated integration test
> Integration test update: `test_fallback_admin_user`

- src/databricks/labs/ucx/source_code/linters/imports.py
- src/databricks/labs/ucx/source_code/notebooks/cells.py
- src/databricks/labs/ucx/source_code/path_lookup.py
- tests/unit/hive_metastore/test_table_migrate.py
This PR updates/fixes the way Python's builtin [`next()`](https://docs.python.org/3/library/functions.html#next) function is used. Specifically, in a few places the code assumed that `None` will be returned if there is no next value but this is incorrect.
> Tech debt: fix situations where `next()` isn't being used properly

- src/databricks/labs/ucx/source_code/base.py
- src/databricks/labs/ucx/source_code/jobs.py
- src/databricks/labs/ucx/source_code/linters/pyspark.py
- tests/unit/source_code/test_context.py
> Fixed `AttributeError: 'UsedTable' has no attribute 'table'` by adding more type checks

- src/databricks/labs/ucx/hive_metastore/catalog_schema.py
- tests/unit/hive_metastore/test_catalog_schema.py
- tests/unit/test_cli.py
Ran into a couple improvements when manually testing #2744:
- We request the catalog location also when the catalog already exists. Solved by checking if a catalog exists before requesting the storage location
- Multiple loops over the storage locations are not supported as the iterator is empty after first loop. Solved by emptying the external locations in a list.
- More consistent:
- Logging
- Matching storage locations
Resolves #2879
> Improve creating UC catalogs

- README.md
Remove duplicate "`export-assessment` command" section in README
> Remove duplicate "`export-assessment` command" section in README

- README.md
Document preparing external locations when creating catalogs.
> Document preparing external locations when creating catalogs

- src/databricks/labs/ucx/hive_metastore/catalog_schema.py
- tests/unit/hive_metastore/test_catalog_schema.py
Improve logging when skipping grant a in `create-catalogs-schemas`
> Improve logging when skipping grant a in `create-catalogs-schemas`

- src/databricks/labs/ucx/source_code/python/python_infer.py
- tests/unit/source_code/python/test_python_infer.py
Log when inferring node results in `KeyError`.
Fixes #2908
> Fixed `KeyError` from `assess_workflows` task

- src/databricks/labs/ucx/source_code/notebooks/loaders.py
- tests/integration/source_code/test_cells.py
Workspace API does not support relative subpaths such as "/a/b/../c".
This PR fixes the issue by resolving workspace paths before calling the API.
Resolves #2882 
Requires #https://github.com/databrickslabs/blueprint/pull/156
Requires #https://github.com/databrickslabs/blueprint/pull/157
None
> Fixed absolute path normalisation in source code analysis

- src/databricks/labs/ucx/source_code/jobs.py
> Fixed `OSError: [Errno 95]` bug in `assess_workflows` task by skipping GIT-sourced workflows from static code analysis

- src/databricks/labs/ucx/source_code/jobs.py
> Fixed `InvalidParameterValue` failure for scanning jobs running on interactive clusters that got deleted

- src/databricks/labs/ucx/source_code/base.py
- src/databricks/labs/ucx/source_code/linters/pyspark.py
- tests/unit/source_code/samples/functional/table-access.py
- tests/unit/source_code/samples/functional/table-access.sql
PR #2895 introduced a workaround for #2887, although the issue was not reproduced.
Careful analysis shows that this workaround is not necessary.
Tests were added recently in `test_context.py`.
Running the above tests against v0.39 reproduces the issue:
However, running the above tests against v0.40 and above does not reproduce the issue:
The issue was already fixed in `pyspark.py` by PR #2841 and it is likely that the bug reporter was running v0.39
This PR:
- rolls back the workaround from #2895
- renames TableInfoNode to UsedTableNode for clarity
#2887 
None
> Revert workaround for #2887

- src/databricks/labs/ucx/hive_metastore/catalog_schema.py
- tests/unit/hive_metastore/test_catalog_schema.py
Improve logging when skipping legacy grant in `create-catalogs-schemas`
Follow up on #2917
Progresses #2932
> Improve logging when skipping legacy grant in `create-catalogs-schemas`

- src/databricks/labs/ucx/source_code/base.py
- src/databricks/labs/ucx/source_code/linters/pyspark.py
- tests/unit/source_code/test_context.py
Current code does not populate `is_read` or `is_write` for spark calls.
This PR fixes the issue.
Resolves #2893 
None
> Set UsedTable.is_read/is_write for spark calls

- pyproject.toml
In #2920 we introduced a change to ensure that notebook paths are normalised, resolving #2882. This change depended on an upstream fix (databrickslabs/blueprint#157) included in the 0.9.1 release of the dependency. This PR ensures that we run against that release or later.
> Dependency update: ensure we install with at least version 0.9.1 of `databricks-labs-blueprint`

- src/databricks/labs/ucx/contexts/application.py
- src/databricks/labs/ucx/hive_metastore/__init__.py
- src/databricks/labs/ucx/hive_metastore/grants.py
- src/databricks/labs/ucx/hive_metastore/locations.py
- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- src/databricks/labs/ucx/hive_metastore/workflows.py
- tests/integration/aws/test_access.py
- tests/integration/aws/test_credentials.py
- tests/integration/azure/test_credentials.py
- tests/integration/azure/test_locations.py
- tests/integration/conftest.py
- tests/integration/hive_metastore/test_external_locations.py
- tests/integration/hive_metastore/test_federation.py
- tests/integration/hive_metastore/test_migrate.py
- tests/unit/assessment/test_workflows.py
- tests/unit/aws/test_access.py
- tests/unit/azure/test_access.py
- tests/unit/azure/test_locations.py
- tests/unit/hive_metastore/test_locations.py
- tests/unit/hive_metastore/test_principal_grants.py
- tests/unit/hive_metastore/test_table_migrate.py
- tests/unit/hive_metastore/test_tables.py
- tests/unit/test_cli.py
This PR streamlines resolution of tables and mounts into external locations. previously dependencies were not direct and explicit
> Make `ExternalLocations` explicitly depend on `TablesCrawler` and `MountsCrawler`

- README.md
- labs.yml
- src/databricks/labs/ucx/cli.py
- tests/unit/test_cli.py
Clarify `skip` and `unskip` commands work on views. To make it even more clear: added the `--view` flag to both commands.
> Clarify `skip` and `unskip` commands work on views

- tests/integration/install/test_installation.py
- tests/integration/workspace_access/test_groups.py
Increase timeout of tests that delete groups in order to cope with eventual consistency
Resolves #2931
Resolves #2910 
None
> Increase timeout for tests that delete groups

- src/databricks/labs/ucx/hive_metastore/locations.py
- tests/integration/hive_metastore/test_external_locations.py
- tests/unit/hive_metastore/test_locations.py
This PR removes duplicate code for determining overlapping storage prefixes. this also lays down some groundwork for federated SQL connections
> Use `LocationTrie` to infer a list of UC external locations

- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- tests/unit/hive_metastore/test_table_migrate.py
Warn when table has column without no name during table migration. 
The code goes with a "do first, apologize later" approach to avoid an additional call to retrieve the column schema.
Resolves #2891
> Warn when table has column without no name during table migration

- src/databricks/labs/ucx/contexts/application.py
- src/databricks/labs/ucx/hive_metastore/locations.py
- tests/integration/assessment/test_workflows.py
- tests/unit/hive_metastore/test_locations.py
This PR adds a DBFS Resolver which is used by HMS federation to resolve the DBFS root locations.
TODO:
co-authored by @vihangk-db
> Added DBFS Root resolution when HMS Federation is enabled

- src/databricks/labs/ucx/hive_metastore/grants.py
- tests/integration/conftest.py
- tests/integration/hive_metastore/test_catalog_schema.py
- tests/unit/hive_metastore/test_principal_grants.py
Skip applying permissions for workspace system groups because they do not exist on the account level.
Resolves #2986
ACL related code
> Skip applying permissions for workspace system groups to Unity Catalog resources

- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- src/databricks/labs/ucx/hive_metastore/table_migration_status.py
Return `False` when failed to migrate.
> Return `False` when failed to migrate table

- src/databricks/labs/ucx/framework/owners.py
This PR trivially removes a dead class; this was detritus left over from an intermediate version of the ownership mechanism that limited `Record` to `dataclass` classes. However this limitation was removed prior to the original code being merged (and the mechanism can be used with any class).
> Remove a dead (ownership-related) class

- src/databricks/labs/ucx/source_code/python_libraries.py
- tests/integration/source_code/test_libraries.py
- tests/unit/source_code/samples/pip_install_pytest_twice.py
Handle installing libraries multiple times in `PipResolver`:
- 
Resolves #3022
Resolves #3023
> Handle installing libraries multiple times in `PipResolver`

- docs/table_persistence.md
- src/databricks/labs/ucx/contexts/workflow_task.py
- src/databricks/labs/ucx/progress/workflows.py
- tests/unit/progress/test_workflows.py
This PR updates the `experimental-migration-progress` workflow so that it also re-runs the linting tasks for dashboard queries and notebooks that are associated with jobs. (It was always the intention that this happen once linting was part of the `assessment` workflow.)
Relates #2678.
- modified existing workflow: `migration-progress-experimental`
- added unit tests
> Update migration progress workflow to also re-lint dashboards and jobs

- src/databricks/labs/ucx/source_code/jobs.py
- tests/unit/source_code/linters/test_directfs.py
Our current implementation logs warnings when encountering notebook cells that are not Python or SQL
This PR fixes that
Resolves #2977 
None
> Fixed errors related to unsupported cell languages

- src/databricks/labs/ucx/source_code/directfs_access.py
- src/databricks/labs/ucx/source_code/used_table.py
- tests/integration/source_code/test_jobs.py
- tests/unit/source_code/test_queries.py
This PR fixes an issue with the DFSA and used-table crawlers that could prevent loading of the snapshots. When loading they convert the rows to dictionaries using `.as_dict()` which isn't available on rows provided by the spark-based lsql backend. Instead `.asDict()` needs to be used.
Incidental changes:
- An existing integration test was updated to also test snapshot loading for these crawlers.
- Another test was renamed to fix a typo in the name.
Relates to #3036, #3039.
- existing unit tests
> Fixed snapshot loading for DFSA and used-table crawlers

- src/databricks/labs/ucx/source_code/python/python_ast.py
- tests/unit/source_code/python/test_python_ast.py
Our current implementation does not properly collect imports when source code uses indirect import patterns such as:
```
from importlib import import_module
module = import_module("some-module")
```
This PR fixes that
None
None
> Fix import member issue

- src/databricks/labs/ucx/progress/history.py
- tests/unit/progress/test_history.py
This PR cherry-picks some changes from #3039 that updated the `HistoryEncoder` to work correctly with databases that are declared with `__future__.__annotations__` in effect. 
When this annotation is in effect, python converts all type-hints during import/declaration into strings and then performs deferred resolution at a later stage. (This is why forward references work.) Unfortunately the dataclass mechanism captures field types prior to deferred resolution. This PR ensures that our type checking works anyway.
Cherry-picks from #3039.
> Tech debt: let `HistoryEncoding` work with string-based type annotations in addition to the normal type-based ones

- src/databricks/labs/ucx/source_code/linters/imports.py
- src/databricks/labs/ucx/source_code/python/python_ast.py
- tests/integration/source_code/test_graph.py
- tests/unit/source_code/python/test_python_ast.py
- tests/unit/source_code/samples/import-module.py
Our current implementation doesn't infer import names when calling `importlib.import_module(some_name)`
This PR fixes that.
None
None
> Fix dynamic import issue

- src/databricks/labs/ucx/workspace_access/manager.py
- src/databricks/labs/ucx/workspace_access/secrets.py
- tests/unit/workspace_access/test_secrets.py
This PR updates the secret scope support so that permissions crawling doesn't fail when a secret scope is listed but disappears before the ACLs can be retrieved. Instead of failing the task we now log a warning and complete normally.
- modified existing workflow: `assessment`
- added unit tests
> Update permissions crawling so that it doesn't fail if a secret scope disappears during crawling

- src/databricks/labs/ucx/progress/history.py
Add method to `HistoryLog` for encoding `Historical`. Some pre-work for the remainder of the issues in 3064. 
Progresses #3064
> Add method to `HistoryLog` for encoding `Historical`

- src/databricks/labs/ucx/framework/owners.py
- src/databricks/labs/ucx/hive_metastore/ownership.py
- src/databricks/labs/ucx/source_code/directfs_access.py
`LegacyQueryOwnership` takes a `str` as record type which obfuscates the meaning of that str and creates risk of collision in the ownership factory
This PR fixes that by introducing a `LegacyQueryPath` data class as a wrapper around the `str`
None
None
> Use LegacyQueryPath dataclass as record for LegacyQueryOwnership

- src/databricks/labs/ucx/contexts/workflow_task.py
- src/databricks/labs/ucx/progress/grants.py
- src/databricks/labs/ucx/progress/tables.py
- src/databricks/labs/ucx/progress/workflows.py
- tests/unit/progress/test_grants.py
- tests/unit/progress/test_tables.py
- tests/unit/progress/test_workflows.py
Add pipeline progress encoder
Resolves #3061
Resolves #3064
> Add table progress encoder

- src/databricks/labs/ucx/source_code/lsp_plugin.py
This PR disables the following advice codes from being propagated in our notebook editor:
- 'cannot-autofix-table-reference',
- 'default-format-changed-in-dbr8',
- 'dependency-not-found',
- 'not-supported',
- 'notebook-run-cannot-compute-value',
- 'sql-parse-error',
- 'sys-path-cannot-compute-value',
- 'unsupported-magic-line',
> Ignore failed inference codes when presenting results to Databricks Runtime

- tests/integration/hive_metastore/test_migrate.py
- tests/unit/source_code/test_directfs_access.py
This change unskips the two integration test which are failing.
The underlying issue is fixed as part of https://github.com/databrickslabs/ucx/pull/3020
Resolves #3054 
Resolves #3055
> Fix Integration test failure of migration_tables

- src/databricks/labs/ucx/assessment/sequencing.py
- src/databricks/labs/ucx/contexts/workflow_task.py
- tests/integration/assessment/test_sequencing.py
- tests/unit/assessment/test_sequencing.py
- tests/unit/source_code/test_directfs_access.py
Add a `MigrationSequencer` class to sequence the migration steps for jobs. 
The PR includes the following resources in its sequence:
- Jobs
- Job tasks
- Job tasks dependencies
- Job clusters
- Cluster
Other elements part of the sequence are added later
Progresses #1415 
Supersedes #2980
> Add `MigrationSequencer` for jobs

- src/databricks/labs/ucx/source_code/jobs.py
Log warning instead of raising the error to ensure job task run success.
Resolves #3214
> Warn about errors instead to avoid job task failure

- src/databricks/labs/ucx/source_code/notebooks/sources.py
Notebok cells such as the following will crash the dependency builder.
This PR fixes the issue.
```
#only run this step if you are running below Databricks runtime 13.2 GPU; if using 13.2 and above this is not needed.
%sh
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
sudo add-apt-repository -y "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
sudo apt-get update
```
None
None
> Cater for empty python cells

- src/databricks/labs/ucx/source_code/graph.py
- tests/integration/source_code/test_graph.py
improve MISSING_SOURCE_PATH handling
None
None
> use a path instance for MISSING_SOURCE_PATH and add test

- tests/unit/__init__.py
- tests/unit/conftest.py
- tests/unit/source_code/test_notebook.py
> Replace MockInstallation with MockPathLookup for testing fixtures

- tests/unit/source_code/samples/functional/es-1285042.py
Bug was fixed in v0.46.0
- https://github.com/databrickslabs/ucx/pull/3000
- https://github.com/databrickslabs/ucx/pull/3027
See:
- https://github.com/databrickslabs/ucx/issues/2976
`default-format-changed-in-dbr8` and `sql-parse-error` are ignored for LSP plugin output.
> [chore] Added tests to verify linter not being stuck in the infinite loop

- tests/integration/hive_metastore/test_table_move.py
> [internal] Temporarily disable integration tests due to ES-1302145

- src/databricks/labs/ucx/source_code/known.json
Added `pytesseract` to known list
> Added `pytesseract` to known list

- src/databricks/labs/ucx/config.py
- src/databricks/labs/ucx/contexts/application.py
- src/databricks/labs/ucx/source_code/jobs.py
- src/databricks/labs/ucx/source_code/queries.py
This pull request introduces a new configuration option, `debug_listing_upper_limit`, to control the number of objects listed by large-scale scanners, primarily for debugging purposes. The changes span across multiple files to integrate this new option into various components.
* [WorkspaceConfig](diffhunk://#diff-e968835e310907c0bd91b566de17d346583886b114a5871e1f478fe4f8ae82dfR81-R83): Added `debug_listing_upper_limit` attribute.
* [ApplicationContext](diffhunk://#diff-f5067fb24dbf36380ff6250d2274083d96f167de7f32aed9fc993ebd4d0369a6R508): Passed `debug_listing_upper_limit` to `workflow_linter` and `query_linter` methods. [[1]](diffhunk://#diff-f5067fb24dbf36380ff6250d2274083d96f167de7f32aed9fc993ebd4d0369a6R508) [[2]](diffhunk://#diff-f5067fb24dbf36380ff6250d2274083d96f167de7f32aed9fc993eb …
> [internal] Added `debug_listing_upper_limit` to skip debug listing large workspaces

- tests/unit/aws/test_access.py
unit test case test_get_uc_compatible_roles is mocking the mock_installation.load to simulate save_uc_compatible_roles call through load_uc_compatible_roles. This change removes the mocking code and instead calls save_uc_compatible_roles directly which is what the code is testing.
Resolves #3126
> Tech Debt: Fixed issue with Incorrect unit test practice

- src/databricks/labs/ucx/aws/access.py
- tests/unit/aws/test_access.py
`databricks labs ucx create-missing-principals` can sometime fail due to permission issue resulting in incomplete list of roles created. This PR handles those failure and removes the created ones to bring it back to it initial state
Resolves #2358
> Fix issue with cleanup of failed `create-missing-principals` command

- tests/integration/install/test_installation.py
> Fixed `test_experimental_permissions_migration_for_group_with_same_name` integration test failure

- src/databricks/labs/ucx/source_code/jobs.py
- src/databricks/labs/ucx/source_code/queries.py
Follow up to #3242
This PR fixes properly utilises python iterators to reduce query linting time for
to
`assess_workflows` is a CPU-bound task and can scale vertically from driver node having more CPUs, bottlenecking at the rate limit of `WorkspacePath(...).read_text()` underlying API calls.
> Properly handle Python iterators together with `debug_listing_upper_limit` in slow tasks

- src/databricks/labs/ucx/source_code/jobs.py
- src/databricks/labs/ucx/source_code/known.py
- src/databricks/labs/ucx/source_code/linters/files.py
- src/databricks/labs/ucx/source_code/linters/from_table.py
- src/databricks/labs/ucx/source_code/redash.py
- src/databricks/labs/ucx/source_code/sql/sql_parser.py
This pull request includes several changes to improve error handling and logging in the `databricks/labs/ucx/source_code` module. The most important changes include adding a new error type, handling specific errors in temporary file operations, and updating log levels for various error messages.
* [`src/databricks/labs/ucx/source_code/jobs.py`](diffhunk://#diff-e9b8a0fc1055c1e7d799d63ee6c440b3db47fdbcb8dccd5880f1a72db5df5837L20-R20): Added `DatabricksError` to the list of imported errors and used it to handle exceptions in the `_temporary_copy` method. This change ensures that specific Databricks-related errors are caught and re-raised as `InvalidPath` errors. [[1]](diffhunk://#diff-e9b8a0fc1055c1e7d799d63ee6c440b3db47fdbcb8dccd5880f1a72db5df5837L20-R20) …
> Improve error handling for `assess_workflows` task

- src/databricks/labs/ucx/queries/assessment/main/10_0_database_summary.sql
Database names are now clickable and opens a new tab with the database page
Resolves #3258
> Add hyperlink to database names in database summary dashboard

- src/databricks/labs/ucx/progress/workflows.py
This PR updates the `migration-progress-experimental` workflow so that it uses the `main` cluster instead of the `tacl` one to crawl for tables.
Crawling from the `tacl` cluster fails: the Py4j bridge isn't available (which the crawler relies on).
Resolves #3268 
- modified existing workflow: `migration-progress-experimental`
- manually tested
> Update `migration-progress-experimental` workflow to crawl tables from the `main` cluster

- pyproject.toml
- tests/integration/conftest.py
> Fixed backwards compatibility breakage from Databricks SDK

- pyproject.toml
Pin Databricks SDK to minor version to circumvent the problems with the [0.37.0 release](https://github.com/databricks/databricks-sdk-py/releases/tag/v0.37.0). Will unpin later when we resolved that issues. 
Waiting on solution in:
> Pin Databricks SDK to minor version

- src/databricks/labs/ucx/assessment/workflows.py
- src/databricks/labs/ucx/contexts/application.py
- src/databricks/labs/ucx/progress/workflows.py
- src/databricks/labs/ucx/source_code/queries.py
- tests/integration/source_code/test_directfs_access.py
- tests/integration/source_code/test_jobs.py
- tests/integration/source_code/test_queries.py
- tests/unit/progress/test_workflows.py
- tests/unit/source_code/test_queries.py
Follow the more common pattern of expect objects in a class signature. Those objects are passed on from the context. Makes testing more straightforward
Breaking down the linked PR below.
Progresses #3045
Breaks up #3112
> [CHORE] Moving `QueryLinter` input objects to signature

- tests/integration/conftest.py
This PR modifies some properties on the integration test context so that they don't cache their return values; these properties are based on internal mutable state and the current caching situation makes it difficult to know if they are yielding the current value or an earlier one that might no longer be correct.
> Tech debt: avoid caching with some test context properties

- src/databricks/labs/ucx/source_code/base.py
- src/databricks/labs/ucx/source_code/jobs.py
- src/databricks/labs/ucx/source_code/notebooks/sources.py
- tests/integration/source_code/test_base.py
- tests/unit/source_code/notebooks/test_sources.py
Handle reading 
Resolves #3386
> Safe read files in more places

- README.md
- src/databricks/labs/ucx/config.py
- src/databricks/labs/ucx/contexts/application.py
- src/databricks/labs/ucx/hive_metastore/grants.py
- src/databricks/labs/ucx/install.py
- tests/unit/hive_metastore/test_grants.py
- tests/unit/install/test_install.py
> Allowing skipping TACLs migration during table migration.

- src/databricks/labs/ucx/hive_metastore/table_migration_status.py
- tests/unit/hive_metastore/test_table_migrate.py
- tests/unit/hive_metastore/test_table_migration_status.py
Handle Databricks errors during workspace listings in the table migration status refresher
Resolves #3262
> Handle Databricks errors during workspace listings in the table migration status refresher

- .github/ISSUE_TEMPLATE/bug.yml
We've switched to a new UCX project. This PR updates the template for new bugs so that they are associated with the new project that we're using instead of the old one.
> Ensure bugs are associated by default with the correct UCX project

- tests/integration/assessment/test_ext_hms.py
- tests/integration/hive_metastore/test_ext_hms.py
This PR updates the `test_running_real_assessment_job_ext_hms` integration test:
- It ensures that the workflow runs on a cluster with an external HMS, instead of faking it. (The previous method was insufficient once we switched to the fast table crawler and the Python4J bridge became needed.)
- Update the test fixture so that the resources it creates to be crawled are created in the external HMS, not the main one. Without this the assessment crawlers partially fail because the resources they are configured to crawl do not exist on the external HMS.
Resolves #3134.
Resolves #3246.
- updated integration test
> Fix integration test: `test_running_real_assessment_job_ext_hms`

- src/databricks/labs/ucx/cli.py
- tests/unit/test_cli.py
Remove `try-except` around verifying the migration progress prerequistes in the `migrate-tables` cli command as the warning is more specific inside the class
Progresses #3438
> Remove `try-except` around verifying the migration progress prerequisites in the `migrate-tables` cli command

- src/databricks/labs/ucx/workspace_access/workflows.py
Log message as error when legacy permissions API is enabled/disabled depending on the workflow ranso that the workflow fails, signaling to the user to take action
Resolves #3388
> Log message as error when legacy permissions API is enabled/disabled depending on the workflow ran

- tests/integration/conftest.py
- tests/integration/hive_metastore/test_ext_hms.py
- tests/integration/hive_metastore/test_workflows.py
- tests/integration/workspace_access/test_workflows.py
Exclude TACL migration in table migration integration tests because these were not asserted, and to speed up the tests and reduce flakiness
Attempt to reduce flakiness blocking CI in #3239
Similar to #3437 in the sense that both PR scope integration tests to a smaller set of resources
> Exclude TACL migration in table migration integration tests

- src/databricks/labs/ucx/aws/access.py
- src/databricks/labs/ucx/aws/locations.py
- src/databricks/labs/ucx/azure/locations.py
- src/databricks/labs/ucx/cli.py
- src/databricks/labs/ucx/contexts/application.py
- src/databricks/labs/ucx/contexts/workspace_cli.py
- src/databricks/labs/ucx/hive_metastore/federation.py
- src/databricks/labs/ucx/hive_metastore/locations.py
- tests/integration/hive_metastore/test_federation.py
- tests/unit/hive_metastore/test_federation.py
- tests/unit/hive_metastore/test_locations.py
Added support for SQL Based HMS (MySQL) when creating an HMS Federated Catalog
> MySQL External HMS Support for HMS Federation

- src/databricks/labs/ucx/hive_metastore/table_migrate.py
- src/databricks/labs/ucx/installer/policy.py
- tests/integration/hive_metastore/test_workflows.py
- tests/integration/install/test_installation.py
Use LTS  Databricks runtime version because the convert to external table migration strategy fails on the latest runtime
> Note: This postpones the problem! Which is preferred for the next release as users can experience this problem with the latest UCX release. However, it does not solve the problem.
Resolves #3453 (for now)
Reslves #3461
> Use LTS  Databricks runtime version

- src/databricks/labs/ucx/hive_metastore/table_migration_status.py
- tests/unit/hive_metastore/test_table_migration_status.py
Skip listing built-in catalogs to update table migration process
Resolves #3462
> Skip listing built-in catalogs to update table migration process

- CHANGELOG.md
- src/databricks/labs/ucx/__about__.py
* Removed `packaging` package dependency ([#3469](https://github.com/databrickslabs/ucx/issues/3469)). In this release, we have removed the dependency on the `packaging` package in the open-source library to address a release issue. The import statements for "packaging.version.Version" and "packaging.version.InvalidVersion" have been removed. The function _external_hms in the federation.py file has been updated to retrieve the Hive Metastore version using the "spark.sql.hive.metastore.version" configuration key and validate it using a regular expression pattern. If the version is not valid, the function logs an informational message and returns None. This change modifies the Hive Metastore version validation logic and improves the overall reliability and maintainability of the library.
> Release v0.53.1

- src/databricks/labs/ucx/assessment/dashboards.py
- src/databricks/labs/ucx/contexts/application.py
- tests/unit/assessment/test_dashboards.py
Exclude ucx dashboards from Lakeview dashboard crawler as this would be a false positive dashboard
Resolves #3441
> Exclude ucx dashboards from Lakeview dashboard crawler

- src/databricks/labs/ucx/workspace_access/workflows.py
This PR fixes a trivial typo in an error message where the wrong workflow name is given.
> Fix typo in workflow name (in error message)

- tests/integration/conftest.py
Add dummy id for jobs to include on `MockInstallationContext.config` to avoid assessing all workflows.
A more proper solution would be to resolve: https://github.com/databrickslabs/blueprint/issues/179
> Add dummy id for jobs to include on `MockInstallationContext.config`

- README.md
- src/databricks/labs/ucx/source_code/python/python_ast.py
- tests/unit/source_code/notebooks/test_cells.py
- tests/unit/source_code/test_notebook.py
Create specific failure for Python syntax error while parsing with Astroid.
If we parse Python code with a syntax error, the user needs to manually check the code:
1. Create a specific failure for this case.
2. Rename `system-error` to `python-parse-error` to match `sql-parse-error` and explain in the README so user knows what to do.
3. Keep generic failure with direction to create Github issues to surface other issues.
Closes #3457
> Create specific failure for Python syntax error while parsing with Astroid

- README.md
- src/databricks/labs/ucx/framework/tasks.py
- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/installer/workflows.py
- src/databricks/labs/ucx/progress/workflows.py
- src/databricks/labs/ucx/queries/progress/main/00_0_migration_progress.md
- src/databricks/labs/ucx/runtime.py
- tests/integration/cmds.py
- tests/integration/conftest.py
- tests/integration/progress/test_workflows.py
- tests/integration/recon/test_migrate_recon.py
- tests/integration/workspace_access/test_workflows.py
- tests/unit/install/test_install.py
- tests/unit/install/test_install_dashboards.py
- tests/unit/installer/test_workflows.py
- tests/unit/progress/test_workflows.py
- tests/unit/test_workflows.py
This PR updates the UCX installation so that the migration progress workflow runs automatically once per day.
Changes include:
- Refactoring some of the plumbing that we use for managing/installing workflows.
- Allowing workflows to have a (Cron-based) schedule attached to them.
- ~Allowing the default schedule to be overridden via configuration during installation.~ (Will be addressed in a new PR.)
- Configuring the migration progress workflow to run daily, by default at 5 a.m. (UTC).
- updated relevant user documentation
- modified existing workflow: `migration-progress-experimental`
- added and existing unit tests
- added and existing integration tests
> Schedule the migration progress workflow to run daily

- src/databricks/labs/ucx/assessment/aws.py
- src/databricks/labs/ucx/aws/access.py
- tests/unit/aws/test_access.py
> AWS role issue with external locations pointing to the root of a storage account

- src/databricks/labs/ucx/source_code/notebooks/sources.py
Delete stale code: `NotebookLinter._load_source_from_run_cell`
Progresses #3514
> Delete stale code: `NotebookLinter._load_source_from_run_cell`

- src/databricks/labs/ucx/source_code/graph.py
- src/databricks/labs/ucx/source_code/jobs.py
- src/databricks/labs/ucx/source_code/python/python_analyzer.py
- src/databricks/labs/ucx/source_code/python/python_ast.py
- tests/unit/source_code/python/test_python_ast.py
Rename Python AST's `Tree` methods for clarity
- Add docstrings
- Rename `append_` to `attach_` and `extend_` to more precisely describe what the methods do
- Let `attach_` and `extend_` always return `None`
- Extend unit testing
Progresses #3514
Precedes #3520
> Rename Python AST's `Tree` methods for clarity

- src/databricks/labs/ucx/source_code/python/python_ast.py
Make link to issue template url safe using Python's urllib
Introduced in #3498
> Make link to issue template url safe

- tests/integration/install/test_installation.py
The reinstallation is starting before the first installation is done. This is causing the warning to not be raised and the test fails
> Add assert to make sure installation is finished before re-installation

- src/databricks/labs/ucx/hive_metastore/pipelines_migrate.py
- tests/integration/hive_metastore/test_pipeline_migrate.py
- tests/unit/hive_metastore/test_pipeline_migrate.py
Let `PipelinesMigrator` skip unfound jobs. This might happen when jobs are deleted inbetween assessment and running pipelines migration
Resolves #3490
> Let `PipelinesMigrator` skip unfound jobs

- src/databricks/labs/ucx/source_code/linters/table_creation.py
- tests/unit/source_code/linters/test_files.py
- tests/unit/source_code/linters/test_table_creation.py
- tests/unit/source_code/samples/functional/_child_that_uses_missing_value.py
- tests/unit/source_code/samples/functional/_child_that_uses_value_from_parent.py
- tests/unit/source_code/samples/functional/es-1285042.py
- tests/unit/source_code/samples/functional/pyspark/spark-table.py
- tests/unit/source_code/samples/functional/spark-connect/_child_that_uses_missing_value.py
- tests/unit/source_code/samples/functional/table-access.py
- tests/unit/source_code/samples/functional/table-access.sql
- tests/unit/source_code/samples/functional/table-migration/table-migration-notebook.py
- tests/unit/source_code/samples/functional/values_across_cells.py
- tests/unit/source_code/samples/functional/values_across_notebooks_dbutils_notebook_run.py
- tests/unit/source_code/samples/functional/values_across_notebooks_magic_line.py
- tests/unit/source_code/samples/functional/values_across_notebooks_run_cell.py
- tests/unit/source_code/samples/parent-child-context/child.py
- tests/unit/source_code/test_jobs.py
Remove the linting false positive for missing table format warning when using `spark.table`
Resolves #3545
> Remove the linting false positive for missing table format warning when using `spark.table`

- docs/ucx/docs/process/index.mdx
- docs/ucx/docs/reference/commands/index.mdx
Extend code migration progress documentation by detailing:
- Start with linting then do the migration
- Use dashboards
- Use local commands
- Reference default catalog resource
- Add section for finalising the migration
Resolves #2231
> Extend code migration progress documentation

- src/databricks/labs/ucx/source_code/base.py
- src/databricks/labs/ucx/source_code/graph.py
- src/databricks/labs/ucx/source_code/jobs.py
- src/databricks/labs/ucx/source_code/linters/files.py
- tests/integration/source_code/solacc.py
- tests/integration/source_code/test_graph.py
- tests/unit/source_code/test_base.py
- tests/unit/source_code/test_graph.py
- tests/unit/source_code/test_jobs.py
While graph building for linting, the `DependencyProblem` are converted to `LocatedAdvice`. This PR aligns the two classes
Progresses #3514
Breaks up #3520
> Align `DependencyProblem` with `LocatedAdvice`

- src/databricks/labs/ucx/source_code/files.py
- tests/unit/source_code/test_files.py
Use `Language` on `LocalFile`, not `CellLanguage`, as a file might consist of cells when it is a notebook, but the file language is not a cell language
Breaks up #3586
> [TECH DEBT] Use `Language` on `LocalFile`, not `CellLanguage`

- src/databricks/labs/ucx/source_code/known.py
- src/databricks/labs/ucx/source_code/linters/context.py
- src/databricks/labs/ucx/source_code/linters/files.py
- src/databricks/labs/ucx/source_code/linters/folders.py
- src/databricks/labs/ucx/source_code/linters/graph_walkers.py
- src/databricks/labs/ucx/source_code/linters/jobs.py
- tests/unit/source_code/linters/test_graph_walkers.py
- tests/unit/source_code/notebooks/test_sources.py
- tests/unit/source_code/test_functional.py
Make session state public on `LinterContext` and access it from the context instead of passing it along.
Breaks up #3586
> [TECH DEBT] Make session state public on `LinterContext` and access it from the context

- src/databricks/labs/ucx/source_code/files.py
- src/databricks/labs/ucx/source_code/folders.py
- tests/unit/conftest.py
- tests/unit/source_code/test_dependencies.py
- tests/unit/source_code/test_files.py
Improve file handling by `FileLoader`:
- Verify the `FileLoader` resolves files using the `PathLookup`
- Handle file opening errors, like `PermissionError`, `FileNotFoundError`
- Handle file with BOM encodings
- Handle empty files
Breaks up #3586
> [TECH DEBT] Improve file handling by `FileLoader`

- src/databricks/labs/ucx/source_code/files.py
- src/databricks/labs/ucx/source_code/graph.py
- src/databricks/labs/ucx/source_code/notebooks/loaders.py
- tests/unit/source_code/notebooks/test_loaders.py
- tests/unit/source_code/test_dependencies.py
- tests/unit/source_code/test_files.py
Support ignoring files and notebooks
Progresses #3645
> Support ignoring files and notebooks

- docs/ucx/docs/reference/commands/index.mdx
- docs/ucx/docs/reference/workflows/index.mdx
- src/databricks/labs/ucx/queries/assessment/estimates/01_0_group_migration.md
Document to run `validate-groups-membership` before groups migration, not after, as this is the correct order.
Resolves #3506
> Document to run `validate-groups-membership` before groups migration, not after

- src/databricks/labs/ucx/source_code/base.py
- src/databricks/labs/ucx/source_code/files.py
- src/databricks/labs/ucx/source_code/linters/files.py
- src/databricks/labs/ucx/source_code/linters/graph_walkers.py
- src/databricks/labs/ucx/source_code/notebooks/loaders.py
Rename and document getting supported file language helper function to make more clear what it does.
IMO it was not clear that this function contains essential decision power as it is the filter for passing files to the linter only if they are supported (in contrast with inferring any language - also the non-supported ones). 
For example, before #3655, the `FileLinter` contains filters for extensions, however this redundant as that is already handled by this helper function.
The rename makes it more explicit what this function does. The documentation makes it more clear how to use the function
> Rename file language helper function

- src/databricks/labs/ucx/source_code/python/python_infer.py
Catch `AttributeError` in `InfferedValue._safe_infer_internal` to make the inference safer. 
It is a bug in Astroid https://github.com/pylint-dev/astroid/issues/2683
Resolves #3659
> Catch `AttributeError` in `InfferedValue._safe_infer_internal`

- docs/ucx/docs/process/index.mdx
- docs/ucx/docs/reference/commands/index.mdx
Added documentation for HMS Fed
> HMS Federation Documentation

- src/databricks/labs/ucx/recon/base.py
- src/databricks/labs/ucx/recon/metadata_retriever.py
- src/databricks/labs/ucx/recon/schema_comparator.py
- tests/unit/recon/test_schema_comparator.py
closes #3568 
Added case sensitive flag for metadata comparison. To consider/ignore column name case.
> Case sensitive/insensitive table validation

- docs/ucx/docs/reference/workflows/index.mdx
Explain when to run `remove-workspace-local-backup-groups` workflow as the documentation was not clear about this.
> [DOCS] Explain when to run `remove-workspace-local-backup-groups` workflow

- src/databricks/labs/ucx/source_code/base.py
- tests/unit/source_code/test_base.py
Broaden safe read text exception scope to be more safe when reading a text file. Also the tests are extended.
Relates to #3703
Relates to #3704
> Broaden safe read text caught exception scope

- src/databricks/labs/ucx/__init__.py
- src/databricks/labs/ucx/github.py
- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/source_code/known.py
- src/databricks/labs/ucx/source_code/linters/base.py
- src/databricks/labs/ucx/source_code/linters/files.py
- src/databricks/labs/ucx/source_code/linters/pyspark.py
- src/databricks/labs/ucx/source_code/notebooks/sources.py
- src/databricks/labs/ucx/source_code/python/python_ast.py
- src/databricks/labs/ucx/source_code/python_libraries.py
- tests/integration/source_code/linters/test_files.py
- tests/unit/source_code/linters/test_base.py
- tests/unit/source_code/linters/test_files.py
- tests/unit/source_code/linters/test_folders.py
- tests/unit/source_code/notebooks/test_sources.py
- tests/unit/source_code/test_notebook.py
- tests/unit/test_github.py
Add notebook fixing to `NotebookLinter`
- Implement `Notebook.apply` 
- Call `Notebook.apply` from `FileLiner.apply` for `Notebook` source container
- Remove legacy `NotebookMigrator`
- Introduce `PythonLinter` to run apply on a AST tree
- Allow to 
Progresses #3514
Breaks up #3520
> Fix notebook sources with `NotebookLinter.apply`

- src/databricks/labs/ucx/assessment/jobs.py
- src/databricks/labs/ucx/contexts/application.py
- src/databricks/labs/ucx/contexts/workflow_task.py
- tests/integration/assessment/test_jobs.py
Check for include_job_ids in assess_jobs task
https://github.com/databrickslabs/ucx/issues/3656
Resolves #3656
> Scope crawled jobs in `JobsCrawler` with `include_job_ids`

- src/databricks/labs/ucx/queries/assessment/main/00_3_count_total_tables.sql
Fix `Total Tables` widget in assessment dashboard by filtering out views
Resolves #3252
> Fix `Total Tables` widget in assessment to only show table counts

- src/databricks/labs/ucx/assessment/workflows.py
- src/databricks/labs/ucx/contexts/application.py
- src/databricks/labs/ucx/source_code/linters/jobs.py
- tests/integration/assessment/test_workflows.py
- tests/integration/source_code/test_directfs_access.py
- tests/unit/source_code/test_jobs.py
Let `WorkflowLinter.refresh_report` lint jobs from `JobsCrawler` so that we only lint what is within scope
Resolves #3662
Progresses #3722
> Let `WorkflowLinter.refresh_report` lint jobs from `JobsCrawler`

- tests/integration/conftest.py
Scope linted dashboards on mock runtime context. We should use `make_dashboard` instead of the dashboard fixture directly `_make_dashboard`. Also changed one dashboard to a `LakeviewDashboard` so that we lint that too
> Scope linted dashboards on mock runtime context

- src/databricks/labs/ucx/install.py
- src/databricks/labs/ucx/queries/progress/main/02_0_owner.filter.yml
Dashboard names should only contain alphanumeric characters (a-z, A-Z, 0-9), hyphens (-), or underscores (_)
Fix for failing tests in https://github.com/databrickslabs/ucx/actions/runs/13559322493
Resolves #3761
Resolves #3762 
Resolves #3763 
Resolves #3764 
Resolves #3769 
Resolves #3770 
Resolves #3771
Resolves #3772 
Resolves #3773 
Resolves #3774 
Resolves #3775
Resolves #3776 
Resolves #3777 
Resolves #3778
Resolves #3779
Resolves #3780
Resolves #3781 
Resolves #3782 
Resolves #3783 
Resolves #3784
Resolves #3785 
Resolves #3786 
Resolves #3787 
Resolves #3788
> Let dashboard name adhere to naming convention

- src/databricks/labs/ucx/assessment/jobs.py
- src/databricks/labs/ucx/contexts/application.py
- src/databricks/labs/ucx/contexts/workflow_task.py
- tests/integration/assessment/test_jobs.py
- tests/integration/conftest.py
- tests/integration/hive_metastore/test_grant_detail.py
- tests/unit/__init__.py
- tests/unit/assessment/test_jobs.py
- tests/unit/hive_metastore/test_pipeline_migrate.py
Exclude UCX jobs from crawling to avoid confusing for users when they see UCX jobs in their assessment report.
Fixes #3656
Resolves #3722
Follow up on #3732
Relates to #3731
> Merged the following PRs into this branch in an attempt to let the CI pass. Those PRs contain fixes for integration tests
From #3767:
Scope linted dashboards on mock runtime context. We should use `make_dashboard` instead of the dashboard fixture directly `_make_dashboard`. Also changed one dashboard to a `LakeviewDashboard` so that we lint that too
From #3759
Add retry mechanism to wait for the grants to exists before crawling
Resolves #3758
> Exclude UCX jobs from crawling

- src/databricks/labs/ucx/queries/progress/main/02_0_owner.filter.yml
Puts back the owner filter in the migration progress dashboard
Partially reverts #3789
Reverts c24e6eafb8f7f3b89fb0edf49d14d3e6a48e3aa7
Requires lsql release after merging https://github.com/databrickslabs/lsql/pull/357
> Partial revert "Let dashboard name adhere to naming convention"

- pyproject.toml
Pin dependencies to minor releases to test dependency changes before users are affected by them.
The reasoning for choosing between pinned vs loose requirements is:
1. For applications (like UCX), pin the dependency minor versions to minimize instability due to changes in dependencies while still receiving dependency bug/patch fixes. We automatically test dependency changes in Dependabot's PRs.
2. For libraries (like pytest, lsql and blueprint), prefer loose requirements so that the libraries and projects that use your library have the freedom to chose their preferred version, especially important to increase the likelihood for finding a library version that fits the constrains of all dependencies and sub-dependencies (dependencies of dependencies of dependencies ...).
We prefer the …
> Pin dependencies to minor releases

- src/databricks/labs/ucx/contexts/application.py
Convert UCX job ids to integers before passing to `JobsCrawler`
Resolves #3722
> Convert UCX job ids to `int` before passing to `JobsCrawler`

- src/databricks/labs/ucx/queries/assessment/main/10_1_all_tables.sql
For the table types widget
1. Table names are clickable
2. Rows are orders by type and then name
Resolves #3259
> Add hyperlinks to tables and order the rows by type, name

- src/databricks/labs/ucx/installer/workflows.py
Adjusted the Lakeview dashboard Assessment Main dashboard path to the new naming format (Now looks for the dashboard name dynamically to avoid hardcoded values) in the  EXPORT_ASSESSMENT_TO_EXCEL Notebook.
https://github.com/user-attachments/assets/dcbf6df4-a6f0-4fae-836a-0fcec861d86c
> Fixed Assessment Exporter Notebook

- src/databricks/labs/ucx/source_code/known.json
- tests/integration/assessment/test_dashboards.py
- tests/integration/conftest.py
- tests/integration/install/test_installation.py
- tests/integration/progress/test_dashboards.py
- tests/integration/progress/test_jobs.py
- tests/integration/queries/test_migration_progress.py
- tests/integration/source_code/test_directfs_access.py
- tests/integration/source_code/test_queries.py
- tests/integration/source_code/test_redash.py
Skip integration tests with legacy dashboard creation as it is deprecated. Skipping until we can work with product team and enable it only for Labs workspaces
> Skip integration tests with legacy dashboard creation as it is deprecated

- src/databricks/labs/ucx/assessment/jobs.py
- src/databricks/labs/ucx/progress/workflows.py
- src/databricks/labs/ucx/source_code/linters/jobs.py
- tests/unit/source_code/test_jobs.py
> Limit crawl workflows task in assessment to workflows that ran in the last 30 days.

- src/databricks/labs/ucx/workspace_access/groups.py
After the introduction of creation of nested account groups from workspace local groups, the `reflect_account_groups_on_workspace` shoots out an error which instead should be a warning.
> Warns instead of an error while finding an acc group in workspace

- docs/ucx/docs/reference/workflows/index.mdx
Added missed documentation commit for #3963
#3960
> Added documentation for #3963

- pyproject.toml
- src/databricks/labs/ucx/account/metastores.py
Dependabot PRs are not running acceptance tests seemingly due to a permissions issue. This workaround runs the acceptance tests
#4026
> Workaround for acceptance with dependabot PR

- tests/unit/test_cli.py
This PR updates unit tests that verify logs to ensure they set up log-capturing to capture the level of the logs they're looking for. Previously this wasn't the case, and they relied on the underlying logging configuration have a level that would emit the record.
Relates databrickslabs/blueprint#238.
> Update unit tests to configure log-capturing when verifying logs

- src/databricks/labs/ucx/install.py
Integration test for invalid dashboard is failining on PermissionDenied which we currently do not handle. Add a handler for PermissionDenied so that the older one is ignored and a new dashboard is creted.
Resolves #4208
> Handle PermisssionDenied exception so that a new dashboard is created.

- src/databricks/labs/ucx/account/workspaces.py
- tests/integration/account/test_account.py
Service Principals were not being created during account group creation. This PR fixes the bug and adds a test
Resolves #4359
> Fix service principal not re-created while creating account groups

- tests/integration/workspace_access/test_tacl.py
In line with adding retries to failing integration tests (because fetching grants is taking a tad bit longer) extend the previously designed function for UDFs to Tables and Schemas in the tests
Resolves #4367
> Extends assert retries for table and schema grants

- src/databricks/labs/ucx/aws/access.py
- tests/unit/aws/test_access.py
Handle exception in `create-missing-principals` because there are no UC roles, exit gracefully with an informative message instead of failing.
Resolves #4372
> Handle exception in `create-missing-principals` because there are no UC roles

- docs/ucx/docs/reference/workflows/index.mdx
- src/databricks/labs/ucx/assessment/workflows.py
- src/databricks/labs/ucx/config.py
- src/databricks/labs/ucx/install.py
Adds an installation prompt and a configurable flag in config.yml for users to skip `assess_workflows`.
Resolves #4374
> Adds option to skip `assess_workflows` via install-time choice & config
